hi-min-study/daliy-algorithm-study

Yiseull/202312/18 LTC Binary Search.md
정렬된 정수 배열 `nums`가 주어질 때, 정수 `target`이 존재하면 인덱스를 반환하고 없다면 `-1`를 반환한다.
- 시간복잡도 O(logn) 안에 문제를 해결한다.
1. 배열의 0번째 인덱스, 마지막 인덱스를 각각 left와 right로 정의한다.
2. right가 left보다 작을 때까지 이진 검색을 반복한다.
3. left와 right의 중간 수를 mid로 정의한다.
4. nums[mid]가 target보다 큰지 작은지 비교하여 left, right를 갱신한다.
5. nums[mid]가 target과 같으면 mid를 반환하고 반복문이 끝나면 -1를 반환한다. 
이진 검색은 금방 풀지만 제출하면 시간초과가 나는 경우가 많다. 
- left와 right의 초깃값은 어떤 범위로 설정할건지
- left와 right를 어떻게 갱신할건지
- return은 left, right 중 어떤 것을 할 것인지
위의 3가지에 대해 아직 명확한 풀이 기준을 몰라서 풀 때마다 어떻게 해야하는지 헷갈리는 것 같다. 이진 검색 문제를 많이 풀어보면서 3가지에 대한 감을 확실히 잡고 가야할 것 같다.
=> [20231218] LTC / Easy / Binary Search / 박이슬

Curry4182/202312/18 BAJ N과 M (3).md
자연수 N과 M이 주어졌을 때, 아래 조건을 만족하는 길이가 M인 수열을 모두 구하는 프로그램을 작성.
- 1부터 N까지 자연수 중에서 M개를 고른 수열
- 같은 수를 여러 번 골라도 된다.
1, M개의 수열을 M개로 나눠서 생각한다.
2. 분할 된 문제는 함수 하나로 처리하고 자기 자신을 재귀호출 한다.
3. 함수가 M번 호출되면 결과를 출력한다. 
초기에 M번 호출될 때 마다 콘솔에 출력하였다. 하지만 이럴경우 너무 빈번하게 콘솔에 출력을 하여 속도가 저하된다.
따라서 StringBuilder로 메모리에 저장하고 마지막에 한번 콘솔에 출력하게 만들어 시간 초과 되지 않고 문제를 해결하였다.
=> [20231218] BAJ / 실버3 / N과M (3) / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md
문제 링크 : https://www.acmicpc.net/problem/1987
풀이 시간 : 30분
체감 난이도 : 중
문제 설명
처음 시작점부터 아직 방문하지 않은 알파벳 위치를 방문한다.
생각한 방법
이미 방문한 알파벳을 visited[]배열을 이용해서 처리한다. 이미 방문한 알파벳이면 다시 방문하지 않고, 아직 방문하지 않았으면 dfs를 다시 호출한다.
=> [20231218] BAJ/ 골드4/ 알파벳/ 구범모

HandamdeCloud/202312/19 PRG 마법의 엘리베이터.md
https://school.programmers.co.kr/learn/courses/30/lessons/148653
35분
10의 정수 단위로 나누기가 가능, 0을 맞추는 최소로 움직이는 경우의 수 찾기
**시도1**
storey의 끝자리 수를 항상 0으로 맞춘다.
0 ~ 4까지는 버림, 6 ~ 9는 올림으로 생각했다.
그래서 16의 경우 20이, 2554의 경우는 2550으로 맞춰주도록 만들었다.
5의 경우, 앞자리 숫자의 영향을 받는다. (answer 값은 5가그대로 더해짐)
앞자리 숫자가 4이하라면, 다음 if문에서 0 ~ 4의 버림 경우의 수를 탈 수 있어 최소한의 영향을 가진다.
앞자리 숫자가 5이상이라면, 다음 if문에서 6~9의 경우의 수, 혹은 0의 경우의 수를 탈 수 있어 최소한의 영향을 가질 수 있다.
1의 자리수부터 시작해서 마지막 자리수까지 검사하면서 결과를 확인한다. 시도 2 이후에 재시도 후 결과를 얻음
```
def solution(storey):
answer = 0
while storey:
remain = storey % 10 
if remain < 5:
answer += remain
storey -= remain 
elif remain > 5:
tmp = (10 - remain)
answer += tmp
storey += tmp
else:
if (storey // 10) % 10 >= 5:
storey += 10
answer += remain
storey = storey // 10
return answer
```
**시도2**
자릿수를 0에 맞추는 내용을 제외한다. 그저 앞자리 …
=> [20231219] PRG / lv2 / 마법의 엘리베이터 / 조재현

Curry4182/202312/18 BAJ N과 M (3).md, Curry4182/202312/19 BAJ N과 M (4).md
https://www.acmicpc.net/problem/15652
60분
자연수 N과 M이 주어졌을 때, 아래 조건을 만족하는 길이가 M인 모든 수열을 구한다.
- 1부터 N까지 자연수 중에서 M개를 고른 수열
- 같은 수를 여러 번 골라도 된다.
- 고른 수열은 비내림차순이어야 한다.
두 가지 방법으로 풀이할 수 있는데 이 중 두번 째 풀이에서 시간을 많이 사용함
1) 순서 
M이 주어지면 첫번째 부터 M번째 까지 수를 중복하여 비 내림차순으로 출력해야 한다.
이 때 M가지로 나누어 생각하고 각 경우를 재귀 호출하는 함수 f에서 해결 한다고 한다.
그러면 idx번째 f 함수 에서 s부터 시작하는 수를 idx번쨰 c배열에 저장하고 다음 함수를 호출한다.
idx가 m이 되면 모든 c 배열을 출력한다.
2) 선택
1부터 8까지의 수를 x가지 만큼 선택한다고 생각하자
사전순으로 출력해야 하므로 M=4일 때 1111, 1112, 1122, 1222 ... 순으로 출력해야 한다.
1에서 8까지의 수를 각각 함수 f에서 처리한다고 생각할 때 배열 c에서 1에서 8까지의 수를 최대 M개 선택하고 
다음 함수에서는 남은 수 만큼 선택하는 방법으로 해결할 수 있다. 
- 지금까지 생각한 방법말고 다른 방법으로 문제를 푸는 건 정말 어렵다 ㅜㅜ
=> [20231219] BAJ / 실버3 / N과 M (4)/ 강병곤

Yiseull/202312/19 LTC Search in Rotated Sorted Array.md
https://leetcode.com/problems/search-in-rotated-sorted-array/
60분
=> [20231219] LTC / Medium / Search in Rotated Sorted Array / 박이슬

HandamdeCloud/202312/20 PRG 단속카메라.md
https://school.programmers.co.kr/learn/courses/30/lessons/42884
60분
진입 진출점이 다른 차량들을 모두 단속카메라에 한번씩은 지나가게 해야한다.
이때, 사용하는 감시 카메라의 개수를 최소로 하도록 해야한다.
**실패**
시도1 2차원 배열을 만들어 모든 차량을 visited하는 조합을 찾기
시작점과 끝점이 아니더라도 임의의 구간에서 카메라를 둘 수 있는 경우의 수가 있다고 생각함. 
그래서 가장 최초 진입점 ~ 마지막 진출점 구간을 만들어 열로 만들고 차들이 방문했는지를 행으로 삼아 2차원 배열을 만들기를 시도함
하지만 이런 방법은 결국 조합의 한계를 찾게 만듦 O(n^2) 소요
사실 정답 풀이는 매우 단순하다. 방문 여부를 확인할 필요도 없다.
진입점과 카메라의 위치의 상대적인 관계를 파악하고 그에 따라 위치를 변경해주면 된다.
요구사항에 집착한 풀이가 되어버린 것 같다.
모든 차들이 카메라를 한번씩 통과해야 하므로 방문 여부를 확인학기 위해선 2차원 배열이 필수라고 생각했고, 그 이상의 답은 없다고 단정지었다.
그리고 다른 진출 진입 시점 내의 임의의 위치에 카메라가 존재할 가능성을 크게 신경쓷다보니 다른 문제에서 풀었던 유사한 유형이라고 생각해 문제풀이에 틀이 박혀버렸다..
최소 O(n)을 만들기 위해서 생각해야 할 작은 요구사항들을 머저 떠올리는 연습이 필요해보인다.
=> [20231220] PRG / lv3 / 단속카메라 / 조재현

Curry4182/202312/20 PRG 수레 움직이기.md
https://school.programmers.co.kr/learn/courses/30/lessons/250134
600분
빨강, 파랑 수레를 정해진 목표 까지 움직일 때 최소로 움직이는 값을 반환하는 문제
- bfs로 que에 값이 결과에 도달하면 바로 answer를 반환하고 que 사이즈가 0이면 0을 반환한다. 
- 가로 세로가 최대 4이기 때문에 bfs 보다 dfs나 백트래킹을 사용하여 푸는게 더 깔끔하게 풀 수 있을 것 같다.
=> [20231220] PRG / lv3 / 수레 움직이기 / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md
https://www.acmicpc.net/problem/1332
60 분
문제를 풀 수 있는 많은 경우의 수 중, 최소의 문제를 풀어서 조건을 만족시키는 최적화 문제.
dfs + 완탐을 이용하여 최소 문제를 만족하는 방법을 찾고, return한다.
다만 시간복잡도 계산이 어려워서 완탐이 아닌 줄 알았으나, 놀랍게도 완탐이였던 문제..
시간복잡도 계산이 어려웠다. 코테에서 만났으면 그래도 완탐으로 풀었을 거 같긴 하다.
=> [20231220] BAJ/골드3/풀자/구범모

Yiseull/202312/21 PRG 등굣길.md
15분
격자의 크기 m, n과 물이 잠긴 지역의 좌표를 담은 2차원 배열 puddles이 매개변수로 주어질 때, 오른쪽과 아래쪽으로만 움직여 집에서 학교까지 갈 수 있는 최단경로의 개수를 1,000,000,007로 나눈 나머지를 반환한다.
1. 격자의 크기 m, n의 크기로 dp를 진행할 리스트 mapp을 정의하면서 값을 1로 모두 초기화한다.
2. 물이 잠긴 지역은 mapp 값을 0으로 변경한다. 테두리 지역인 경우는 물이 잠긴 지역 다음에 있는 지역들도 0으로 변경한다.
3. 테두리 지역을 제외하고 mapp(1, 1)부터 dp를 진행한다.
4. (i, j)까지 갈 수 있는 최단경로의 개수는 오른쪽 위에서 오는 경로와 왼쪽에서 오는 경로의 합이기 때문에 `mapp[i - 1][j] + mapp[i][j - 1]`이다.
5. 학교 위치의 map[m - 1][n - 1]를 반환할 때, 문제 요구사항에 맞게 1,000,000,007로 나눈 나머지를 반환한다.
Lv3지만 체감 난이도는 Lv2였고 전형적인 DP 문제였다. 약간 생각이 필요한 부분은 테두리 지역에서 물이 잠긴 지역 이후는 길이 없다는 것 정도인 것 같다.
=> [20231221] PRG / lv3 / 등굣길 / 박이슬

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md
https://www.acmicpc.net/problem/2234
40분
방의 갯수, 각 방의 넓이, 벽을 하나만 부순 이후 방의 넓이의 최댓값을 구하는 문제.
방의 갯수 + 넓이는 단순 bfs로 처리한 이후, clustering한다.
이후 cluster가 나눠지면 dfs로 탐색하여 자신의 방 번호와 다른 방 번호를 만났을 때, 넓이의 합을 갱신하여 최댓값을 찾으면 된다.
벽 부순 이후 방 넓이의 합을 어떻게 구할지 감이 잘 안왔는데, dfs가 제일 무난했던 것 같다.
또한 입력을 이진수로 바꿨어야 해서 종합적으로 재밌었던 문제.
=> [20231221] BAJ/골드3/성곽/구범모

HandamdeCloud/202312/20 PRG 단속카메라.md, HandamdeCloud/202312/21 BOJ 1197 최소 스패닝 트리.md
https://www.acmicpc.net/problem/1197
30분
모든 노드를 들리면서 가중치가 최소인 수를 출력하라
MST 유형
최소 신장  트리라는 그래프의 모든 정점을 포함하는 트리를 의미한다.
문제를 푸는 방법에는 2가지가 있는데, 이번에는 크루스칼 알고리즘을 사용했다.
크루스칼 알고리즘은, 모든 노드를 방문하면서도, greedy알고리즘을 사용한다. 
현재 노드에서 가장 최소가 되는 값을 선택하고, 선택 이후에 사이클이 생기지 않도록 한다.
그래서 이 경우 union and find라는 알고리즘을 사용한다.
find를 통해서 연결된 사이클이 먼저 있는지 확인하고, 연결되어있지 않다면, 그 둘을 연결하는 로직을 만든다.
방문 여부를 파악하는 방법은 parent 리스트에 자기자신의 번호를 처음에 두고, 이 값이 변경되면 어떻게 연결되어있는지 그 흐름을 파악해나간다. 이런 방식으로 노드를 파악하고 연결하면 최소 가중치를 획득할 수 있다.
mst는 굉장히 오랜만이 풀면서, 이런 유형에 대한 경험이 많이 없어 여러번 풀어봐야겠다고 생각했다.
크루스칼, 그리고 프림 알고리즘은 bfs나 dfs처럼 고정된 형식에서 약간의 변형만 이루어지기 때문에 문제에 대한 경험을 한동안 계속 키워나가야할 것 같다.
=> [20231221] BOJ / 골드4 / 최소 스패닝 트리 / 조재현

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md
https://www.acmicpc.net/problem/15655
40분
N과 M이 주어졌을 때 아래 조건을 만족하는 길이가 M인 수열을 구하시오
- N개의 자연수 중에서 M개를 고른 수열
- 고른 수열은 오름차순이어야 한다.
M개의 자연수를 M개씩 각 함수 f에서 재귀로 결정한다.
- 이 때 N가지 모든 수를 고려하면 O(N!) 이다.
- 하지만 각 함수 f에서 각 수를 결정할지 안 할지 선택하면 O(2^N)으로 풀 수 있다.
- 기존에는 O(N!) 풀이만 생각하였지만 O(2^N)으로도 쉽게 풀 수 있다는것을 이번기회에 알게되었다.
=> [20231221] BAJ/실버3/N과 M(6)/강병곤

Yiseull/202312/22 PRG 
https://www.acmicpc.net/problem/1208
분
=> [20231222] BAJ / 골드1 / 부분수열의 합 2 / 박이슬

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md
https://www.acmicpc.net/problem/21736
10 분
만날 수 있는 친구수 세기
단순 bfs
시간이 많지 않아 기본 bfs문제를 풀어보았다.
=> [20231222] BAJ/실버2/헌내기는 친구가 필요해/구범모

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md
https://www.acmicpc.net/problem/15654
30분
N개의 자연수와 자연수 M이 주어졌을 때, 아래 조건을 만족하는 길이가 M인 수열 출력
- N개의 자연수 중에서 M개를 고른 수열 
- N개의 자연수를 M개 선택한다고 하였을 때 각각을 함수 f에 위임 하는 방식으로 풀이
- O(N!) 풀이할 수 있다.
- 이전 방식과 무엇이 다른지 고민 하였다. O(2^N)방식으로 풀 수 없는 이유와 백트래킹이 어떤 것을 의미하는지 생각하며 코드를 작성하였다.
=> [20231222] BAJ/실버3/N과 M(5)/강병곤

born-A/202312/22 PRG 여행경로.md
https://school.programmers.co.kr/learn/courses/30/lessons/43164
50분
항공권 정보가 담긴 2차원 배열 tickets가 매개변수로 주어질 때, 방문하는 공항 경로를 배열에 담아 return 한다.
가능한 경로가 2개 이상 나오는 경우에 알파벳 오름차순 정렬하기 쉽게 하기 위해 이동 경로를 String 타입으로 저장한다. 
기존에 내가 작성한 코드는 너무 길고 복잡해 다른 사람의 코드를 참조하였다.
다시 풀어봐야겠다 !
=> [20231222] PRG / lv3 / 여행경로 / 신예진

born-A/202312/22 PRG 여행경로.md, born-A/202312/26 PRG N으로 표현.md
https://school.programmers.co.kr/learn/courses/30/lessons/42895
60분
숫자 N과 number가 주어질 때, N과 사칙연산만 사용해서 표현 할 수 있는 방법 중 
N 사용횟수의 최솟값을 return 하도록 solution 함수를 작성한다.
N을 1개씩 추가해서 구한 결과를 Set에 추가해서 set에 number가 있는지 확인한다.
dp 문제를 오랜만에 풀어서 좀 헤맸다. 내일 다른 dp문제를 풀면서 풀이 방식을 익혀야겠다.
=> [20231226] PRG / lv3 / N으로 표현 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md
https://www.acmicpc.net/problem/9095
20분
입력 받은 정수를 1, 2, 3의 합으로 나타낼 수 있는 경우의 수를 출력 한다.
1, 2, 3을 더한 상태를 다음 함수 f에 입력으로 주고 재귀호출한다.
이 때 다음 두가지 종료조건을 만족하면 값을 반환한다. 
- sum(지금 까지 더한 정수) > n (입력 받은 정수)
0을 반환한다. 
- sum(지금 까지 더한 정수) == n (입력 받은 정수)
1을 반환한다.
1, 2, 3에 대한 반환 받은 값을 모두 더하고 반환 한다.
재귀 함수는 현재 입력 받은 값을 계산하고 다음 함수를 재귀호출 한다. 
재귀 함수는 무한정 호출할 수 없기 때문에 종료조건이 있어야 한다.
각 함수호출 횟수와 한번 호출에 어떤 연산을 하는지를 곱하면 총 연산해야하는 수를 O표기법으로 알 수 있다.
=> [20231226] BAJ / 실버3 / 1, 2, 3 더하기 / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md
https://www.acmicpc.net/problem/13975
30 분
파일 목록들 중 두개를 골라 반복적으로 합쳐서 최종적으로 파일을 하나로 만들 때, 드는 비용의 최솟값을 구하기.
그리디하게 파일 합칠 때 비용이 적은것부터 골라서 합치면 된다.
단,최종 파일의 크기가 int max를 넘어가므로 주의.
=> [20231227] 골드4/파일합치기3/구범모

born-A/202312/22 PRG 여행경로.md, born-A/202312/26 PRG N으로 표현.md, born-A/202312/27 PRG 정수 삼각형.md
https://school.programmers.co.kr/learn/courses/30/lessons/43105?language=java
50분
삼각형의 꼭대기에서 바닥까지 이어지는 경로 중, 거쳐간 숫자의 합이 가장 큰 경우를 찾아야 한다. 
아래 칸으로 이동할 때는 대각선 방향으로 한 칸 오른쪽 또는 왼쪽으로만 이동 가능하다. 
삼각형의 정보가 담긴 배열 triangle이 매개변수로 주어질 때, 거쳐간 숫자의 최댓값을 return 한다.
대각선 방향으로 한 row씩 내려오며 숫자를 더하는걸 작은 문제로 나눠서 풀면 된다.
dp로 풀면 무난했던 문제였다.
=> [20231227] PRG / lv3 / 정수 삼각형 / 신예진

Yiseull/202312/27 PRG 사칙연산.md
https://school.programmers.co.kr/learn/courses/30/lessons/1843
80분
🚨 난이도 상상상. 너무 어려움...
=> [20231227] PRG / lv4 / 사칙연산 / 박이슬

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md
https://www.acmicpc.net/problem/1759
30분
정수 C개의 문자열이 주어질 때 정수 L개를 중복없이 오름차순으로 출력하는 문제
중복 되는 순열은 O(n!)에 풀지만
문제와 같이 중복 되지 않으면서 오름차순 정렬되는 순열은 O(2^n)에 풀 수 있다.
기본적으로 항목을 나여할 때 n! 개로 출력하게 되는데 이 부분을 최적화 하는 방법들을 알아가는 것 같다.
=> [20231227] BAJ / 골드5 / 암호 만들기 / 강병곤 

born-A/202312/22 PRG 여행경로.md, born-A/202312/26 PRG N으로 표현.md, born-A/202312/27 PRG 정수 삼각형.md, born-A/202312/28 PRG 등굣길.md
40분
격자의 크기 m, n과 물이 잠긴 지역의 좌표를 담은 2차원 배열 puddles이 매개변수로 주어질때,
오른쪽과 아래쪽으로만 움직여 집에서 학교까지 갈 수 있는 최단경로의 개수를 1,000,000,007로 나눈 나머지를 return하도록 작성한다.
최단경로 가짓수를 구하는 전형적인 방식을 이용하였다.
쉬운 dp문제였다.
=> [20231228] PRG / lv3 / 등굣길 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/92335
40분
입력으로 n, k가 주어진다.
n을 k진수로 만들었을 때 다음 규칙을 만족하는 소수 p의 개수를 구해야 한다.
- 0P0처럼 소수 양쪽에 0이 있는 경우
- P0처럼 소수 오른쪽에만 0이 있고 왼쪽에는 아무것도 없는 경우
- 0P처럼 소수 왼쪽에만 0이 있고 오른쪽에는 아무것도 없는 경우
- P처럼 소수 양쪽에 아무것도 없는 경우
String kNumber = Integer.toString(n, k);// toString을 이용하여 n을 k진수로 만든다.
String[] numbers = kNumber.split("0"); // 0으로 split하고 number원소를 검사한다. 
isPrime 함수를 만들고 Math.sqrt(num) 까지만 소수인지 검사한다. 
toString과 splilt을 이용하여 빨리 풀 수 있다.
시간 내에 어떻게 하면 빨리 풀지 고민해야 하는데 toString과 split은 좋은 방법인 것 같다.
=> [20231228] PRG / lv2 / k진수에서 소수 개수 구하기 / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md
https://www.acmicpc.net/problem/2342
120 분
게임에서 발을 움직일 때 마다 점수가 오르는데, 오르는 점수의 합을 최소로 만드는 문제.
이전의 발이 어딨었느냐에 따라 다음 점수의 값이 달라지고, 그리디하게는 못 푸므로 dp를 떠올렸다.
또한 바텀업보다는 최종값이 정해진 이후 이전값을 채우는 탑다운이 맞는 풀이지만, dp배열의 정의 자체 + dfs함수를 잘 못 짜서 시간이 오래 걸리고, 풀이를 참고하였다.
어려웠다.. 하지만 풀이를 어느정도 떠올린것은 뿌듯하다.
=> [20231228] BAJ/골드3/Dance Dance Revolution/구범모

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md
https://school.programmers.co.kr/learn/courses/30/lessons/17684
60분
다음과 같은 과정을 거쳐 LZW 압축을 한다. 
1. 길이가 1인 모든 단어를 포함하도록 사전을 초기화한다.
2. 사전에서 현재 입력과 일치하는 가장 긴 문자열 w를 찾는다.
3. w에 해당하는 사전의 색인 번호를 출력하고, 입력에서 w를 제거한다.
4. 입력에서 처리되지 않은 다음 글자가 남아있다면(c), w+c에 해당하는 단어를 사전에 등록한다.
5. 단계 2로 돌아간다.
먼저 A-Z를 해쉬 테이블에 저장한다.
입력받은 문자열 msg에서 1부터 N까지 검사한다.
- 만약 일치하는 문자열이 있으면 len = len + 1 하여 추가 탐색한다.
- 만약 일치하는 문자열이 없다면 해쉬 테이블에 저장한다. 
- 문자열이 끝날 때 예외처리를 많이 해야해서 코드가 복잡해졌다. 다음에는 문자열이 끝나는 경우를 고려해서 다른 방법으로 시도해야 겠다.
=> [20231229] PRG / lv2 / [3차] 압축 / 강병곤

born-A/202312/22 PRG 여행경로.md, born-A/202312/26 PRG N으로 표현.md, born-A/202312/27 PRG 정수 삼각형.md, born-A/202312/28 PRG 등굣길.md, born-A/202312/29 BAJ 1, 2, 3 더하기.md
https://www.acmicpc.net/problem/9095
40분
정수 n이 주어졌을 때, n을 1, 2, 3의 합으로 나타내는 방법의 수를 구하는 프로그램을 작성한다.
1, 2, 3, 4를 만들 수 있는 경우의 수를 생각해야하는데,
1 = 1
2 = 1+1 / 2
3 = 1+1+1 / 1+2 / 2+1 / 3  
4= 1+3 / 2+2 / 3+1이 된다. 
즉 1, 2, 3의 각 경우의 수에 +1, +2, +3을 해주기만 하면 4를 만들 수가 있다.  
점화식을 유추해보면 dp [n] = dp [n-1] + dp [n-2] + dp [n-3]이라는 식을 세울 수 있다.
dp 풀때마다 점화식을 구하는 데에 애를 많이 먹는거 같다.
문제를 더 많이 풀어야겠다.
=> [20231229] BAJ / 실버3 / 1,2,3 더하기 / 신예진

Yiseull/202312/29 PRG 기능개발.md
https://school.programmers.co.kr/learn/courses/30/lessons/42586#
1시간 이상
프로그래머스 팀에서는 기능 개선 작업을 수행 중입니다. 각 기능은 진도가 100%일 때 서비스에 반영할 수 있습니다.
또, 각 기능의 개발속도는 모두 다르기 때문에 뒤에 있는 기능이 앞에 있는 기능보다 먼저 개발될 수 있고, 이때 뒤에 있는 기능은 앞에 있는 기능이 배포될 때 함께 배포됩니다.
먼저 배포되어야 하는 순서대로 작업의 진도가 적힌 정수 배열 progresses와 각 작업의 개발 속도가 적힌 정수 배열 speeds가 주어질 때 각 배포마다 몇 개의 기능이 배포되는지를 return 하도록 solution 함수를 완성하세요.
=> [20231229] PRG / lv2 / 기능개발 / 박이슬

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md
https://www.acmicpc.net/problem/27210
40분
조각상들을 연속으로 칠하여, 종류가 다른 조각상들의 갯수 차이를 최대로 구하는 문제.
1번 조각상과 2번 조각상만을 갖는 스택을 생성한 이후, 서로 다른 종류의 조각상이 들어오면 st.pop, 같은 종류의 조각상이 들어오면 push한 이후, 매번 st.size로 답을 갱신한다.
=> [20240102] BAJ/골드5/신을 모시는 사당/구범모

born-A/202401/02 PRG 구명보트.md
https://school.programmers.co.kr/learn/courses/30/lessons/42885
30분
사람들의 몸무게를 담은 배열 people과 구명보트의 무게 제한 limit가 매개변수로 주어질 때, 
모든 사람을 구출하기 위해 필요한 구명보트 개수의 최솟값을 구한다.
정렬을 통해 가장 몸무게가 많이 나가는 사람과 가장 몸무게가 적게 나가는 사람들끼리 보트에 태워 보내면 된다.
=> [20240102] PRG / lv2 / 구명보트 / 신예진

Yiseull/202301/02 RPG 다리를 지나는 트럭.md
https://school.programmers.co.kr/learn/courses/30/lessons/42583
30분
=> [20240102] PRG / lv2 / 다리를 지나는 트럭 / 박이슬

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md
https://school.programmers.co.kr/learn/courses/30/lessons/12951
40분
입력으로 받은 문자열 s를 공백으로 단어를 분리하고 각 단어의 첫 글자만 대문자로 변경한 후 출력
모든 문자열을 소문자로 변경하고 처리한다.
굉장히 단순하지만 처음 접근을 잘 못하거나 자바 문자열 처리하는 방법을 모르면 한 없이 어려워지는 문제였다.
기본적인 문자열 정도는 암기하고 있자 라는 생각이 들었다.
=> [20240102] PRG / lv2 / JadenCase 문자열 만들기 / 강병곤

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md
https://school.programmers.co.kr/learn/courses/30/lessons/42883
50분
=> [20240103] PRG / lv2 / 조이스틱 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md
https://school.programmers.co.kr/learn/courses/30/lessons/12911
30분
주어진 숫자를 2진수로 변경하였을 때 1의 숫자가 같으면서도 큰 숫자 중에 가장 작은 수를 출력
1. toStirng을 정수를 2진수로 변환한다.
2. 1의 개수가 같으면서도 큰 수를 for문으로 탐색한다.
3. 찾으면 그 값을 반환한다.
toStirng을 사용하면 바로 풀 수 있는 문제였다.
Integer.toString을 잘 활용하도록 하자
=> [20240103] PRG / lv2 / 다음 큰 숫자 / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md
https://www.acmicpc.net/problem/3184
10 분
map안에 있는 양, 늑대가 싸운 이후 최종적으로 map안에 남아 있는 양, 늑대의 마리수를 구하는 문제.
단순히 방문하지 않은 정점을 bfs로 돌려서, 해당 구간안의 양/늑대 마리수를 구한다.
이후 문제 조건대로 양이 더 많으면 양 마리수만 답에 더해주고, 그렇지 않으면 늑대 마리수만 답에 더해주어 최종적으로 출력하면 된다.
=> [20240104] BAJ/실버1/양/구범모

Yiseull/202401/04 BAJ 프린터 큐.md
https://www.acmicpc.net/problem/1966
35분
=> [20240104] BAJ / 실버3 / 프린터 큐 / 박이슬

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md
https://school.programmers.co.kr/learn/courses/30/lessons/42883
20분
number에서 k 개의 수를 제거했을 때 만들 수 있는 수 중 가장 큰 숫자를 문자열 형태로 return 한다.
for문을 만들어야 할 문자의 길이만큼 반복한다.
그 이후에 가장 큰 수를 탐색하여 StringBuilder에 붙혀주고 return 한다.
=> [20240104] PRG / lv2 / 큰 수 만들기 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/12973
30분
연속으로 나오는 알파벳이 있으면 없을 때 까지 제거한다.
만약 모든 문자를 지우면 1을 반환하고 더 이상 없으면 0을 반환한다.
스택을 이용하여 제거한다.
처음에 문자열로만 생각해서 효율성 문제를 통과하지 못하였다.
정말 중요한 스택에 대해 개념적으로 배울 수 있어서 좋았다.
=> [20240104] PRG / lv2 / 짝지어 제거하기 / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md, BeommoKoo-dev/202401/05 BAJ 27212 미팅.md
https://www.acmicpc.net/problem/27212
60 분
문제에 조건에 따라 악수를 했을 때, 만족도의 최댓값을 구하는 문제.
단순히 brute force로 악수 짝을 지어주면 O(1000C500)이 나올 수 있기 때문에, 시간초과가 난다.
따라서 dp[i][j] = A대학 i번째 학생과 B대학 j번째 학생'까지' 악수했을 때 나올 수 있는 만족도의 최댓값으로 두고,
i와 j가 악수하는 경우 / 악수하지 않는 경우의 수를 각각 점화식으로 세워 푼다.
어떤식으로 최적화 할지 감이 오질 않았다. dp배열 선언하는것은 많이 풀어서 감을 잡아야 할 것 가탇.
=> [20240105] BAJ/골드3/미팅/구범모

Yiseull/202401/05 PRG 길 찾기 게임.md
https://school.programmers.co.kr/learn/courses/30/lessons/42892
120분
- [x 상상상상
=> [20240105] PRG / lv3 / 길 찾기 게임 / 박이슬

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md
https://school.programmers.co.kr/learn/courses/30/lessons/42884
40분
모든 차량이 한 번은 단속용 카메라를 만나도록 하려면 최소 몇 대의 카메라를 설치해야 하는지를 구함.
두번째 요소를 기준으로 정렬한후.
주어진 최소 진입지점 부터 카메라 설치 지점을 시작한다.
진입, 진출지점 사이에 카메라가 없으면 answer++ 한다.
정렬하는 부분에서 시간이 오래걸렸다. 해당 문법을 익혀둬야겠다.
=> [20240105] PRG / lv3 / 단속카메라 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md, Curry4182/202401/05 최댓값과 최솟값.md
https://school.programmers.co.kr/learn/courses/30/lessons/12939
20분
주어진 문자열에서 최솟값과 최댓값을 찾고 정해진 양식대로 반환한다.
주어진 문자열을 split으로 나누고 최대값과 최솟값을 찾아 반환한다.
Integer.parseInt() 정도는 항상 외우고 다니자
=> [20240105] PRG / lv2 / 최대값과 최솟값 / 강병곤

Yiseull/202401/08 PRG 이중우선순위큐.md
https://school.programmers.co.kr/learn/courses/30/lessons/42628
20분
명령어 | 수신 탑(높이)
-- | --
I 숫자 | 큐에 주어진 숫자를 삽입합니다.
D 1 | 큐에서 최댓값을 삭제합니다.
D -1 | 큐에서 최솟값을 삭제합니다.
이중 우선순위 큐가 할 연산 operations가 매개변수로 주어질 때, 모든 연산을 처리한 후 큐가 비어있으면 [0,0] 비어있지 않으면 [최댓값, 최솟값]을 return 하도록 solution 함수를 구해라.
우선순위 큐를 선언하고 문제에서 주어진 대로 명령어를 수행한다. 이때 명령어가 삽입인 경우와 최솟값 삭제인 경우에는 우선순위 큐에 삽입하고 pop 하면 된다. 살짝 복잡한 경우는 최댓값을 삭제하는 경우이다. 우선순위 큐는 오름차순이기 때문에 pop으로 처리할 수 없고 첫 번째 인덱스(가장 높은 우선순위 인덱스) 외에는 우선순위 큐 내에 순서를 보장하지 못한다. 
따라서 최댓값 삭제인 경우만 우선순위큐에서 가장 높은 값을 찾고 remove 메서드로 값을 삭제한다.
문제에서 주어진 대로 그대로 구현하면 돼서 크게 어렵지 않은 문제였다. 다만 최댓값을 삭제하는 부분에서 우선순위 큐를 두 개를 선언해서 사용해야 하나? 라는 생각이 처음에 들기도 했지만 max와 remove 함수를 통해 쉽게 해결할 수 있었다!👍
=> [20240108] PRG / lv3 / 이중우선순위큐 / 박이슬

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md, Curry4182/202401/05 최댓값과 최솟값.md, Curry4182/202401/06 이진 변환 반복하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/70129?language=java
40분
문자열이 1이 될때 까지 2진 변환 반복하기 
반복문을 활용하여 문자열 길이가 1이 될때까지 반복한다.
그 동안 사용했던 방법들을 응용해서 도움이 되는 문제였댜.
=> [20240108] PRG / lv2 / 이진 변환 반복하기 / 강병곤

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md, born-A/202401/08 PRG 피로도.md
https://school.programmers.co.kr/learn/courses/30/lessons/87946 
30분
유저의 현재 피로도 k와 각 던전별 "최소 필요 피로도", "소모 피로도"가 담긴 2차원 배열 dungeons 가 매개변수로 주어질 때, 
유저가 탐험할수 있는 최대 던전 수를 구한다.
dfs 끝단까지 탐색 후 이전노드로 돌아갈 때, 방문 여부와 방문 횟수를 이전 노드까지 탐색했을 때의 값으로 복구한다.
=> [20240108] PRG / lv2 / 피로도 / 신예진

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md, BeommoKoo-dev/202401/05 BAJ 27212 미팅.md, BeommoKoo-dev/202401/08 BAJ 1445 일요일 아침의 데이트.md
https://www.acmicpc.net/problem/1445
60 분
출발지 - 도착지 까지 갈때
1. 최소한으로 쓰레기를 가로질러 가고
2. 최소한으로 쓰레기 옆을 지나가게 하여 최종적으로 1,2값을 구하는 문제.
단순 bfs가 아닌, 가로질러간 쓰레기 갯수, 옆으로 지나간 쓰레기 갯수를 포함하여 pq에 넣어 도착지에 도착하게 코드를 작성한다.
진짜 .. ps는 해도해도 너무너무 어렵다ㅜㅜ
=> [20230108] BAJ/골드2/일요일 아침의 데이트/구범모

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md, BeommoKoo-dev/202401/05 BAJ 27212 미팅.md, BeommoKoo-dev/202401/08 BAJ 1445 일요일 아침의 데이트.md, BeommoKoo-dev/202401/09 BAJ 13301 타일 장식물.md
https://www.acmicpc.net/problem/13301
10 분
n개의 타일을 붙였을 때, 타일의 둘레 길이를 구하는 문제.
간단한 점화식을 이용하여 n번째 직사각형의 길이를 구하고, 이전 직사각형을 포함하여 둘레를 구해준다.
n = 1일때의 반례때문에 틀렸었다. 항상 최소/최댓값을 유의하여 문제 풀기.
=> [20230109] BAJ/실버5/타일 장식물/구범모

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md, born-A/202401/08 PRG 피로도.md, born-A/202401/09 BAJ DFS와 BFS.md
https://www.acmicpc.net/problem/1260
30분
dfs, bfs 알고리즘을 각각 구현한다.
기본적인 dfs, bfs 문제였다.
관련 자바 문법을 찾아보느라 시간이 소요되었다.
=> [20240109] BAJ / 실버2 / DFS와 BFS / 신예진

Yiseull/202401/08 PRG 이중우선순위큐.md, Yiseull/202401/09 PRG 디스크 컨트롤러.md
https://school.programmers.co.kr/learn/courses/30/lessons/42627#
120분🤮
하드디스크는 한 번에 하나의 작업만 수행할 수 있습니다. 각 작업에 대해 [작업이 요청되는 시점, 작업의 소요시간]을 담은 2차원 배열 jobs가 매개변수로 주어질 때, 작업의 요청부터 종료까지 걸린 시간의 평균을 가장 줄이는 방법으로 처리하면 평균이 얼마가 되는지 return 하도록 solution 함수를 작성해주세요. (단, 소수점 이하의 수는 버립니다)
되게 간단한 문제인줄 알았는데 생각보다 고려해야 할 조건들이 많아서 푸는데 애를 먹었다.
=> [20240109] PRG / lv3 / 디스크 컨트롤러 / 박이슬

Yiseull/202401/10 PRG 보석 쇼핑.md
https://school.programmers.co.kr/learn/courses/30/lessons/67258
85분
- [X] 중
=> [20240110] PRG / lv3 / 보석 쇼핑 / 박이슬

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md, born-A/202401/08 PRG 피로도.md, born-A/202401/09 BAJ DFS와 BFS.md, born-A/202401/10 PRG 괄호 회전하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/76502 
20분
괄호를 회전하고,  괄호 문자열이 올바른지 확인한다.
괄호를 회전하는데에는 Queue를 사용하고, 
괄호 문자열이 올바른지 확인하는 경우에는 반복문을 돌리면서 Stack을 사용한다. 
),},]의 3가지 경우에 해당하는 문자가 있는지 체크한다.
=> [20240110] PRG / lv2 / 괄호 회전하기 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md, Curry4182/202401/05 최댓값과 최솟값.md, Curry4182/202401/06 이진 변환 반복하기.md, Curry4182/202401/07 네트워크.md, Curry4182/202401/10 야근지수.md
https://school.programmers.co.kr/learn/courses/30/lessons/12927
60분
남은 일의 양 works를 배열로 받았을 때 n을 참가한다. 이 때 남은 works의 제곱의 합이 최소가 되는 값을 반환한다.
우선순위 큐에 모든 work를 넣고 n이 1이상 일 때 각 아이템 값을 1씩 낮춘다.
그 후 n이 1이 될 때 반복문을 중단하고 합을 반환한다.
우선순위 큐등을 활용하여 가장 빠르게 푸는 방법도 숙지해야겠다는 생각을 하였다.
=> [20240110] PRG / lv3/ 야근 지수 / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md, BeommoKoo-dev/202401/05 BAJ 27212 미팅.md, BeommoKoo-dev/202401/08 BAJ 1445 일요일 아침의 데이트.md, BeommoKoo-dev/202401/09 BAJ 13301 타일 장식물.md, BeommoKoo-dev/202401/10 BAJ 1507 궁금한 민호.md, BeommoKoo-dev/202401/11 BAJ 2836 수상택시.md
https://www.acmicpc.net/problem/2836
60 분
손님들을 출발지에서 목적지까지 태워줄 때 드는 최소 거리를 구하는 문제
스위핑 이후 겹치는 선분의 거리를 답에 더해준다.
스위핑의 개념을 몰랐지만 해당 부분을 떠올렸다. 하지만 답에 어떤식으로 더해줄지 몰라서 풀이를 참고하였다.
정 답을 어떤식으로 구할지 모른다면, 하나하나 손으로 써가며 수식으로 나타내는 것도 좋다고 생각이 된다.
=> [20240111] BAJ/골드3/수상택시/구범모

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md, born-A/202401/08 PRG 피로도.md, born-A/202401/09 BAJ DFS와 BFS.md, born-A/202401/10 PRG 괄호 회전하기.md, born-A/202401/11 PRG 이진 변환 반복하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/70129
30분
s가 "1"이 될 때까지 계속해서 s에 이진 변환을 가했을 때, 
이진 변환의 횟수와 변환 과정에서 제거된 모든 0의 개수를 각각 배열에 담아 return한다.
10진수를 2진수로 변경하는 Integer.toBinaryString() 메소드를 알고 있다면 쉽게 해결할 수 있는 문제
=> [20240111] PRG / lv2 / 이진 변환 반복하기 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md, Curry4182/202401/05 최댓값과 최솟값.md, Curry4182/202401/06 이진 변환 반복하기.md, Curry4182/202401/07 네트워크.md, Curry4182/202401/10 야근지수.md, Curry4182/202401/11 순위.md
https://school.programmers.co.kr/learn/courses/30/lessons/49191
30분
a와 b가 있을 때 a가 b를 이긴 결과 값을 입력으로 받는다.
이 때 각각의 a, b의 순위를 알 수 있는 경우가 몇개인지 반환한다.
이긴 경우를 1, 진 경우를 -1 로 하여 2차원 배열에 저장한다.
이후 플로이와샬 알고리즘을 이용하여 2차원 배열 arr를 업데이트 한다.
이 후 answer를 반환 하기 전에 전체 배열을 탐색한다. 
기본적인 알고리즘들을 적용해볼 수 있어서 도움이 되었다.
=> [20240111] PRG / lv3 / 순위 / 강병곤

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md, BeommoKoo-dev/202401/05 BAJ 27212 미팅.md, BeommoKoo-dev/202401/08 BAJ 1445 일요일 아침의 데이트.md, BeommoKoo-dev/202401/09 BAJ 13301 타일 장식물.md, BeommoKoo-dev/202401/10 BAJ 1507 궁금한 민호.md, BeommoKoo-dev/202401/11 BAJ 2836 수상택시.md, BeommoKoo-dev/202401/12 BAJ 10826 피보나치수4.md
https://www.acmicpc.net/problem/10826
5분
n번째 피보나치수를 출력하라.
n = 10000이므로 자바의 long형태로도 10000번째 피보나치수를 커버하지 못한다.
따라서 BigInteger로 덧셈연산을하여 풀었다.
=> [20240112] BAJ/실버5/피보나치수4/구범모

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md, Curry4182/202401/05 최댓값과 최솟값.md, Curry4182/202401/06 이진 변환 반복하기.md, Curry4182/202401/07 네트워크.md, Curry4182/202401/10 야근지수.md, Curry4182/202401/11 순위.md, Curry4182/202401/12 n진수 게임.md
https://school.programmers.co.kr/learn/courses/30/lessons/17687
30분
다음과 같은 규칙으로 원으로 둘러 게임을 진행한다.
1. 숫자를 0부터 시작해서 차례대로 말한다. 첫 번째 사람은 0, 두 번째 사람은 1, … 열 번째 사람은 9를 말한다.
2. 10 이상의 숫자부터는 한 자리씩 끊어서 말한다. 즉 열한 번째 사람은 10의 첫 자리인 1, 열두 번째 사람은 둘째 자리인 0을 말한다.
이 때 p 번째 순서의 답t개를 n진수로 반환한다. 
반복문을 사용하여 p번째 답을 n진수로 변환하여 저장하고 t개 값을 저장하여 반환한다.
Integer.toString()을 사용하지 않으면 시간이 오래 걸리는 문제이다.
Integer.toString()을 사용하지 않고 진수변환도 연습해봐야 겠다.
=> [20240112] PRG / lv3 / n진수 게임 / 강병곤 

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md, born-A/202401/08 PRG 피로도.md, born-A/202401/09 BAJ DFS와 BFS.md, born-A/202401/10 PRG 괄호 회전하기.md, born-A/202401/11 PRG 이진 변환 반복하기.md, born-A/202401/12 BAJ 1로 만들기.md
https://www.acmicpc.net/problem/1463
5분
1. X가 3으로 나누어 떨어지면, 3으로 나눈다.
2. X가 2로 나누어 떨어지면, 2로 나눈다.
3. 1을 뺀다.
정수 N이 주어졌을 때, 위와 같은 연산 세 개를 적절히 사용해서 1을 만들려고 할때, 연산을 사용하는 횟수의 최솟값을 구한다.
보텀업 방식으로 풀었다.
문제에서 제시한 세가지의 경우의 수로 부분 문제로 나누어 min 값을 구하여 갱신하면 된다.
dp 유형의 쉬운 문제를 많이 풀어서 기본적인 풀이에 익숙해지도록 노력하자.
=> [20240112] BAJ / 실버3 / 1로 만들기 / 신예진

Yiseull/202401/12 PRG 호텔 방 배정.md
https://school.programmers.co.kr/learn/courses/30/lessons/64063
120분 이상🫠
처음에는 모든 방이 비어 있으며 "스카피"는 다음과 같은 규칙에 따라 고객에게 방을 배정하려고 합니다.
1. 한 번에 한 명씩 신청한 순서대로 방을 배정합니다.
2. 고객은 투숙하기 원하는 방 번호를 제출합니다.
3. 고객이 원하는 방이 비어 있다면 즉시 배정합니다.
4. 고객이 원하는 방이 이미 배정되어 있으면 원하는 방보다 번호가 크면서 비어있는 방 중 가장 번호가 작은 방을 배정합니다.
전체 방 개수 k와 고객들이 원하는 방 번호가 순서대로 들어있는 배열 room_number가 매개변수로 주어질 때, 각 고객에게 배정되는 방 번호를 순서대로 배열에 담아 return 하도록 solution 함수를 완성해주세요.
=> [20240112] PRG / lv4 / 호텔 방 배정 / 박이슬

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md, BeommoKoo-dev/202401/05 BAJ 27212 미팅.md, BeommoKoo-dev/202401/08 BAJ 1445 일요일 아침의 데이트.md, BeommoKoo-dev/202401/09 BAJ 13301 타일 장식물.md, BeommoKoo-dev/202401/10 BAJ 1507 궁금한 민호.md, BeommoKoo-dev/202401/11 BAJ 2836 수상택시.md, BeommoKoo-dev/202401/12 BAJ 10826 피보나치수4.md, BeommoKoo-dev/202401/15 BAJ 19582 200년간 폐관수련했더니 PS 최강자가 된 건에 대하여.md
https://www.acmicpc.net/problem/19582
200 분
순서대로 열리는 대회에서, 상금의 상한을 넘지 않도록 모아서 각 대회를 참가했을 때, 최소 N-1개의 대회의 참가할수 있는지 유무를 조사하라.
각 대회에 참가하기 위해서는, 각 대회가 시작하기 전까지 모은 상금이 각 대회의 상금 상한보다 낮아야 한다.
따라서 누적합으로 지금까지의 상금을 구해주고, 어떤 대회의 상금의 상한을 넘었다면 이전에 받은 상금 중 가장 큰 상금을 누적합에서 최대 1번 제회시킨다. 이후에도 다시 상금의 상한을 넘어서면 N-1개의 대회에 참가할 수 없다.
처음에 완탐을 생각했고, 시간초과를 예상하여 dp로써 경우의 수를 제거하려 했으나 각 상태가 독립적이지 않았다. 무턱대고 완탐 -> dp순으로 풀이방향을 잡기보다, dp를 사용할 땐 항상 '중복되는 경우의 수가 있는지'부터 체크하기.
(ps. 나도 ps 최강자 되고 싶다)
=> [20240115] BAJ/골드3/200년간 폐관수련했더니 PS 최강자가 된 건에 대하여/구범모

born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md, born-A/202401/08 PRG 피로도.md, born-A/202401/09 BAJ DFS와 BFS.md, born-A/202401/10 PRG 괄호 회전하기.md, born-A/202401/11 PRG 이진 변환 반복하기.md, born-A/202401/12 BAJ 1로 만들기.md, born-A/202401/15 BAJ 가장 긴 감소하는 부분 수열.md
https://www.acmicpc.net/problem/11722
40분
수열 A가 주어졌을 때, 가장 긴 감소하는 부분 수열의 길이를 구한다.
현재 위치의 수보다 이전 위치의 수가 크다면 감소하는 부분 수열일 가능성이 생긴다.
이 경우에 이전 수들의 dp 메모 값과 현재 dp 메모 값 + 1 중에서 최댓값을 메모한다.
dp유형에선 규칙을 구하는데에서 항상 어려움을 겪는다..
=> [20240115] BAJ / 실버2 / 가장 긴 감소하는 부분 수열  / 신예진

Yiseull/202401/15 PRG 가사 검색.md
https://school.programmers.co.kr/learn/courses/30/lessons/60060
120분
=> [20240115] PRG / lv4 / 가사 검색 / 박이슬

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md, Curry4182/202401/05 최댓값과 최솟값.md, Curry4182/202401/06 이진 변환 반복하기.md, Curry4182/202401/07 네트워크.md, Curry4182/202401/10 야근지수.md, Curry4182/202401/11 순위.md, Curry4182/202401/12 n진수 게임.md, Curry4182/202401/15 베스트앨범.md
https://school.programmers.co.kr/learn/courses/30/lessons/42579
30분
다음의 기준으로 음악의 고유번호를 정렬한다.
1. 속한 노래가 많이 재생된 장르를 먼저 수록합니다.
2. 장르 내에서 많이 재생된 노래를 먼저 수록합니다.
3. 장르 내에서 재생 횟수가 같은 노래 중에서는 고유 번호가 낮은 노래를 먼저 수록합니다.
1. 장르마다 재생수를 저장하는 해시테이블과 장르마다 고유번호, 재생수를 저장하는 해시테이블 두개를 만든다.
2. 해시테이블을 value값이 max이고 방문하지 않는 장르에 대해 해시테이블을 이용하여 고유번호를 저장한다. 
처음 해시테이블을 value기준으로 정렬 하려고 했지만 장르의 길이가 최대 100이기 때문에 n^2 으로 정렬해도 되서 for문으로 만들었다. 이처럼 비효율적인 것 처럼 보이지만 빠르게 구현할 수 있으면 그렇게 하는게 좋은 것 같다.
=> [20240115] PRG / lv3 / 베스트앨범 / 강병곤

Yiseull/202401/16 PRG 스킬 트리.md
=> [20240116] PRG / lv2 / 스킬 트리 / 박이슬

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md, BeommoKoo-dev/202401/02 BAJ 27210 신을 모시는 사당.md, BeommoKoo-dev/202401/03 BAJ 27211 도넛 행성.md, BeommoKoo-dev/202401/04 BAJ 3184 양.md, BeommoKoo-dev/202401/05 BAJ 27212 미팅.md, BeommoKoo-dev/202401/08 BAJ 1445 일요일 아침의 데이트.md, BeommoKoo-dev/202401/09 BAJ 13301 타일 장식물.md, BeommoKoo-dev/202401/10 BAJ 1507 궁금한 민호.md, BeommoKoo-dev/202401/11 BAJ 2836 수상택시.md, BeommoKoo-dev/202401/12 BAJ 10826 피보나치수4.md, BeommoKoo-dev/202401/15 BAJ 19582 200년간 폐관수련했더니 PS 최강자가 된 건에 대하여.md, BeommoKoo-dev/202401/16 BAJ 1099 알 수 없는 문장.md
https://www.acmicpc.net/problem/1099
80분
주어진 단어들로, 단어 내의 문자 순서만 바꾸어 문장을 만들었을 때 드는 비용의 최솟값
dp[i] = 문장의 i번째 인덱스부터 시작했을 때 그 문장을 만드는 비용의 최솟값이라고 정의한다.
이후 각 단어들로 문장을 만들었을 때, 문장에서 그 단어의 길이를 제외한 만큼의 문장을 만드는 데 드는 비용을 구하는 부분문제를 구할 수 있다.
문제만 읽었을 때 어떤 알고리즘으로 풀어야 할지 몰라서 태그를 보았다. 천천히 완탐 풀이 생각 -> 부분문제 정의를 했으면 충분히 태그를 보지 않아도 되었을텐데 문제자체가 어렵다 생각되어 당황했던 점이 아쉽다.
=> [20240116] BAJ/골드3/알 수 없는 문장/구범모

born-A/16 BAJ 계단 오르기.md, born-A/202401/02 PRG 구명보트.md, born-A/202401/03 PRG 조이스틱.md, born-A/202401/04 PRG 큰 수 만들기.md, born-A/202401/05 PRG 단속카메라.md, born-A/202401/08 PRG 피로도.md, born-A/202401/09 BAJ DFS와 BFS.md, born-A/202401/10 PRG 괄호 회전하기.md, born-A/202401/11 PRG 이진 변환 반복하기.md, born-A/202401/12 BAJ 1로 만들기.md, born-A/202401/15 BAJ 가장 긴 감소하는 부분 수열.md
https://www.acmicpc.net/problem/2579
45분
첫 번째 계단을 밟고 이어 두 번째 계단이나, 세 번째 계단으로 오를 수 있다. 
하지만, 첫 번째 계단을 밟고 이어 네 번째 계단으로 올라가거나, 첫 번째, 두 번째, 세 번째 계단을 연속해서 모두 밟을 수는 없다.
각 계단에 쓰여 있는 점수가 주어질 때 이 게임에서 얻을 수 있는 총 점수의 최댓값을 구한다.
n-3을 밟고 n-1번 계단을 밟고 오는 경우와 n-2번을 밟고 오는 경우 2가지의 경우 중 최댓값을 구한다.
점화식을 구하기까지 문제를 분석하는데 시간이 오래걸렸다.
=> [20240116] BAJ / 실버3 / 계단 오르기 / 신예진

Curry4182/202312/20 PRG 수레 움직이기.md, Curry4182/202312/21 BAJ N과 M(6).md, Curry4182/202312/22 BAJ N과 M(5).md, Curry4182/202312/26 1, 2, 3 더하기.md, Curry4182/202312/27 암호 만들기.md, Curry4182/202312/28 k진수에서 소수 개수 구하기.md, Curry4182/202312/29 [3차] 압축.md, Curry4182/202401/02 JadenCase 문자열 만들기.md, Curry4182/202401/03 다음 큰 숫자.md, Curry4182/202401/04 짝지어 제거하기.md, Curry4182/202401/05 최댓값과 최솟값.md, Curry4182/202401/06 이진 변환 반복하기.md, Curry4182/202401/07 네트워크.md, Curry4182/202401/10 야근지수.md, Curry4182/202401/11 순위.md, Curry4182/202401/12 n진수 게임.md, Curry4182/202401/15 베스트앨범.md, Curry4182/202401/16 최고의 집합.md
https://school.programmers.co.kr/learn/courses/30/lessons/12938
40분
다음 조건을 만족하는 집합을 찾고 반환한다.
1. 각 원소의 합이 S가 되는 수의 집합
2. 위 조건을 만족하면서 각 원소의 곱 이 최대가 되는 집합
편차가 제일 작은 원소를 가지는 배열을 만들고 나머지 연산을 통해 배열의 합이 s가 되도락한다.
간단하지만 수학적 아이디어가 필요한 문제라서 조금 어려웠다.
=> [20240116] PRG /lv3 /최고의 집합 / 강병곤

Curry4182/202401/17 단어 변환.md
https://school.programmers.co.kr/learn/courses/30/lessons/43163
30분
begin으로 주어진 단어가 target으로 변환 될 때까지 몇개의 단계를 거쳐야하는지 반환 하는 문제이다.
이 때 변환 조건은 다음과 같다. 
1. 한 번에 한 개의 알파벳만 바꿀 수 있습니다.
2. words에 있는 단어로만 변환할 수 있습니다.
단어 길이가 1씩 차이나는 모든 단어를 que 넣고 bfs로 탐색한다.
bfs를 응용한 문제여서 연습에 도움이 되었다.
=> [20240117] PRG / lv3 / 단어 변환 / 강병곤

Yiseull/202401/17 BAJ 치즈.md
https://www.acmicpc.net/problem/2638
45분
N×M의 모눈종이 위에 아주 얇은 치즈가 있다. 이 치즈는 냉동 보관을 해야만 하는데 실내온도에 내어놓으면 공기와 접촉하여 천천히 녹는다. 그런데 이러한 모눈종이 모양의 치즈에서 각 치즈 격자(작은 정사각형 모양)의 4변 중에서 적어도 2변 이상이 실내온도의 공기와 접촉한 것은 정확히 한시간만에 녹아 없어져 버린다.
치즈 내부에 있는 공간은 치즈 외부 공기와 접촉하지 않는 것으로 가정하고, 이 공간에 접촉한 치즈 격자는 녹지 않는다. 그러나 한 시간 후, 이 공간으로 외부공기가 유입되면 치즈 격자들이 녹는다.
모눈종이의 맨 가장자리에는 치즈가 놓이지 않는 것으로 가정한다. 입력으로 주어진 치즈가 모두 녹아 없어지는데 걸리는 정확한 시간을 구하는 프로그램을 작성하시오.
1. 모눈종이 오른쪽 위부터 확인하면서 치즈가 있고, 치즈가 공기가 접촉하는 부분이 2면 이상이면 melting 배열에 인덱스를 저장한다.
2. 만약 melting 배열이 비어있다면, 치즈가 없는 것이기 때문에 반복문을 종료하고, 그렇지 않다면 melting 배열에 저장된 인덱스에 해당하는 모눈종이에 값을 0으로 바꿔준다. (치즈가 녹아서 없어졌으니 0으로 바꿔줌)
3. 1~2번을 반복할 때마다 시간을 1시간 추가한다. 
👉 이 풀이가 실패한 이유는 **'치즈 내부에 있는 공간은 치즈 외부 공기와 접촉하지 않는 것으로 가정'** 이라는 조건을 고려하지 않았기 때문이다.
**'치즈 내부에 있는 공간은 치즈 외부 공기와 접촉하지 않는 것으로 가정'** 조건에 대한 로직을 추가 …
=> [20240117] BAJ / 골드3 / 치즈 / 박이슬

Yiseull/202401/18 PRG 네트워크.md
https://school.programmers.co.kr/learn/courses/30/lessons/43162
15분
네트워크란 컴퓨터 상호 간에 정보를 교환할 수 있도록 연결된 형태를 의미합니다. 예를 들어, 컴퓨터 A와 컴퓨터 B가 직접적으로 연결되어있고, 컴퓨터 B와 컴퓨터 C가 직접적으로 연결되어 있을 때 컴퓨터 A와 컴퓨터 C도 간접적으로 연결되어 정보를 교환할 수 있습니다. 따라서 컴퓨터 A, B, C는 모두 같은 네트워크 상에 있다고 할 수 있습니다.
컴퓨터의 개수 n, 연결에 대한 정보가 담긴 2차원 배열 computers가 매개변수로 주어질 때, 네트워크의 개수를 return 하도록 solution 함수를 작성하시오.
네트워크는 방향이 없기 때문에 네트워크의 개수는 강연결성분의 개수와 똑같다. 즉, BFS를 몇 번 수행하는지로 바꿔서 정답을 구할 수 있다.
1. 맨 처음 컴퓨터에 대한 방문 배열을 선언한다.
2. 컴퓨터 0번부터 N-1번까지 돌면서 방문했는지 확인한다. 방문하지 않았으면 BFS를 실행한다.
3. BFS를 실행하면 시작 컴퓨터에서 연결되어 있는 모든 컴퓨터들이 방문된다.
이 문제는 전형적인 BFS/DFS 문제여서 비교적 간단하게 풀 수 있었당!
=> [20240118] PRG / lv3 / 네트워크 / 박이슬

born-A/202401/18 BAJ 미로 탐색.md
https://www.acmicpc.net/problem/2178 
40분
미로에서 1은 이동할 수 있는 칸을 나타내고, 0은 이동할 수 없는 칸을 나타낸다. 
이러한 미로가 주어졌을 때, (1, 1)에서 출발하여 (N, M)의 위치로 이동할 때 지나야 하는 최소의 칸 수를 구하는 프로그램을 작성한다.
최소의 칸 수 를 구하는 문제이므로 bfs 큐를 사용해서 푼다.
=> [20240118] BAJ / 실버1 / 미로 탐색 / 신예진

Curry4182/202401/18 등굣길.md
40분
1,1 에서 시작하여 주어진 웅덩이를 피하고 n,m에 도착하는 경우의 수를 반환한다.
n,m 크기의 배열을 만들고 물 웅덩이가 있는 곳을 -1로 표현하여 저장한다. 
n,m크기 만큼 반복하여 최종적으로 n,m 위치의 배열의 값을 반환한다.
평소에 동적 계획법을 사용하지 않아서 바로 생각나지 않아 어려웠다.
=> [20240118] PRG / lv3 / 등굣길 / 강병곤

Yiseull/202401/19 PRG 단어 변환.md
https://school.programmers.co.kr/learn/courses/30/lessons/43163
30분
두 개의 단어 begin, target과 단어의 집합 words가 매개변수로 주어질 때, 아래와 같은 규칙을 이용하여 최소 몇 단계의 과정을 거쳐 begin을 target으로 변환할 수 있는지 return 하도록 solution 함수를 작성해주세요.
```
1. 한 번에 한 개의 알파벳만 바꿀 수 있습니다.
2. words에 있는 단어로만 변환할 수 있습니다.
예를 들어 begin이 "hit", target가 "cog", words가 ["hot","dot","dog","lot","log","cog"]라면 "hit" -> "hot" -> "dot" -> "dog" -> "cog"와 같이 4단계를 거쳐 변환할 수 있습니다.
```
BFS로 최소 단계를 구한다. 이때 내가 생각하는 핵심은 방문 확인을 리스트가 아닌 딕셔너리로 하는 것이다.
BFS를 돌 때, words의 단어들을 매번 모두 순회하면서 현재 단어와 차이가 1 이하인지 확인해야 하는데 주어진 begin은 words 배열에 없기 때문에 visited를 배열로 선언할 경우에는 조금 복잡해진다.
그래서 방문 딕셔너리를 통해 key 값은 단어, value 값은 몇 번째 단계인지 저장을 하면 배열보다는 간단하게 풀 수 있다.
처음에는 check 메서드에서 for 문으로 단어의 길이만큼 돌면서 인덱스로 직접 단어를 비교해주었다. 하지만 zip이라는 좋은 함수가 있어서 그것으로 다시 풀이했다. zip과 같은 함수들을 알고는 있지만 실제로 그것을 …
=> [20240119] PRG / lv3 / 단어 변환 / 박이슬

HandamdeCloud/202401/19 PRG 단어 변환.md
https://school.programmers.co.kr/learn/courses/30/lessons/43163
20분
dfs를 활용한 문제 풀이
단어간의 차이를 비교하고 진행조건 종료조건을 만들어서 풀면 된다. + target에 없으면 애초에 0을. 출력한다.
풀이 계획, 전형적인 dfs풀이었다. dfs풀이에 익숙해지니 lv3문제였지만 수월하게 풀 수 있었다.
=> [20240119] PRG / lv3 / 단어 변환 / 조재현

BeommoKoo-dev/202401/19 BAJ 1493 박스 채우기.md
https://www.acmicpc.net/problem/1493
60분
세준이가 갖고 있는 큐브로 직육면체를 채웠을 때, 드는 큐브의 최소 개수
제일 큰 큐브부터 채워서 분할정복을 돌린다.
greedy하게 제일 큰 큐브부터 써도 되는것은 어느정도 생각을 했지만, 재귀를 어떤식으로 짜야할지 몰라서 풀이를 참고했다.
단순하게 하나의 큐브를 채우고 나머지의 공간을 재귀로 돌리면 된다.
=> [20240119] BAJ/골드2/박스 채우기/구범모

Curry4182/202401/19 단속 카메라.md
https://school.programmers.co.kr/learn/courses/30/lessons/42884?language=java
30분
특정 구간의 값이 2차원 배열로 들어온다. 이때 모든 구간을 만족하기 위한 최소 값이 몇개 필요한지 구하는 문제이다.
이차원 배열에 주어진 각 구간의 마지막 값을 기준으로 정렬한다.
정렬 된 값 기준으로 c를 만들고 c 를 초과한 값이 몇개인지 구하고 반환한다.
탐욕법은 각 단계마다 해를 업데이트 하는 문제인데 이번 문제를 통해 탐욕법에 대한 개념을 공부할 수 있었다.
=> [20240119] PRG / lv3 / 단속카메라  / 강병곤

Yiseull/202401/22 PRG 게임 맵 최단거리.md
https://school.programmers.co.kr/learn/courses/30/lessons/1844
15분
게임 맵의 상태 maps가 매개변수로 주어질 때, 캐릭터가 상대 팀 진영에 도착하기 위해서 지나가야 하는 칸의 개수의 최솟값을 return 하도록 solution 함수를 완성해주세요. 단, 상대 팀 진영에 도착할 수 없을 때는 -1을 return 해주세요.
- maps는 0과 1로만 이루어져 있으며, 0은 벽이 있는 자리, 1은 벽이 없는 자리를 나타냅니다.
- 처음에 캐릭터는 게임 맵의 좌측 상단인 (1, 1) 위치에 있으며, 상대방 진영은 게임 맵의 우측 하단인 (n, m) 위치에 있습니다.
일반적인 BFS로 풀면 된다. 이때 방문 배열을 bool 타입이 아닌 정수 타입으로 만들어서 몇 번째로 칸을 방문한 것인지 저장한다.
목적지를 만나면 목적지에 대한 방문 배열 값을 반환하고, BFS가 끝나면 목적지까지 가지 못한 것이기 때문에 -1을 반환한다.
전형적인 BFS 문제여서 푸는데 어렵지 않았다😊
=> [20240122] PRG / lv3 / 게임 맵 최단거리 / 박이슬

born-A/202401/22 BAJ 순열 사이클.md
https://www.acmicpc.net/problem/10451
25분
N개의 정수로 이루어진 순열이 주어졌을 때, 순열 사이클의 개수를 구하는 프로그램을 작성한다.
DFS로 풀었다. 인덱스 i와 arr[i] 값이 같으면 자기 자신만 잇는 그래프가 되므로 1을 리턴한다. 
방문한 곳을 들란 경우도 리턴 1을 해준다. 
그 리턴값들을 더하면 그래프의 개수가 된다.
=> [20240122] BAJ / 실버3 / 순열 사이클 / 신예진

Curry4182/202401/22 괄호 회전하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/76502
30분
괄호에 대해 열고 닫는 쌍이 올바르게 하기 위해 문자열을 몇번 이동해야 하는지 구하는 문제이다.
문자열을 이동한 후에 스택을 사용하여 열고 닫는 괄호의 순서 쌍이 옳바른지 확인한다.
처음 부터 스택을 고려 해서 빠르게 풀 수 있었다. 자료구조를 이용할 수 있는 문제는 최대한 활용하는 게 좋은것 같다.
=> [20240122] PRG / lv2 / 괄호 회전하기 / 강병곤

HandamdeCloud/202401/23 BOJ 22859 html 파싱.md
https://www.acmicpc.net/submit/22859
60 분
html의 태그를 모두 제거하고 조건에 맞도록 파싱 결과르르 만든다.
가능한 모든 경우의 수로 split, start with, flag방식을 활용해 생 구현을 했다. 2퍼센트에서 틀렸는데, 테스트케이스는 알 수가 없어 포기했다. 
재미없었다.. 정규표현식을 구하는 문제일줄은 몰랐는데, 굳이 이런 내용이 문제로 나올것 같지는 않다!
다만 >< 로 split하는 방법이 오랜만에 생각나서 반가웠고 잘 기억나지 않은 문법과 풀이 방법이 생각나서 좋았다.
=> [20240123] BOJ / 골드3 / html 파싱 / 조재현

BeommoKoo-dev/202401/23 BAJ 1943 동전 분배.md
https://www.acmicpc.net/problem/1943
50분
동전의 종류와 금액, 동전의 갯수까지 주어졌을 때, 총 금액의 절반만큼 나눌수 있는지 없는지를 구하는 문제.
냅색인데 물건이 하나가 아닌, 두개 이상일 때의 냅색이였다.
기존 냅색에서 count만큼 도는 for loop을 추가하여 풀이하면 되었다.
=> [20240123] BAJ/골드3/동전 분배/구범모

born-A/202401/23 BAJ 반복수열.md
https://www.acmicpc.net/problem/2331
45분
반복되는 부분을 제외했을 때, 수열에 남게 되는 수들의 개수를 구하는 프로그램을 작성한다.
HashSet에 숫자들을 넣고 중복 체크한다.
숫자들의 순서를 체크하기 위해 ArrayList를 이용한다.
중복 숫자가 나오면 list에서 해당 숫자 인덱스를 리턴한다.
=> [20240123] BAJ / 실버4 / 반복수열 / 신예진

Curry4182/202401/23 할인행사.md
https://school.programmers.co.kr/learn/courses/30/lessons/131127?language=java
40분
자신이 원하는 제품과 수량이 할인하는 날짜와 10일 연속으로 일치할 경우에 맞춰서 회원가입을 하려고 할 때 할인 받을 수 있는 회원등록 날짜의 총일수를 반환한다.
hash 자료구조를 사용하여 저장한 후 날짜에 맞춰 반환한다. 
hash 자료구조를 응용할 수 있어서 좋았다.
=> [20240123] PRG / lv2 / 할인행사  / 강병곤

Yiseull/202401/24 PRG 단속카메라
https://school.programmers.co.kr/learn/courses/30/lessons/42884#
60분
고속도로를 이동하는 모든 차량이 고속도로를 이용하면서 단속용 카메라를 한 번은 만나도록 카메라를 설치하려고 합니다.
고속도로를 이동하는 차량의 경로 routes가 매개변수로 주어질 때, 모든 차량이 한 번은 단속용 카메라를 만나도록 하려면 최소 몇 대의 카메라를 설치해야 하는지를 return 하도록 solution 함수를 완성하세요.
=> [20240124] PRG / lv3 / 단속카메라 / 박이슬

born-A/202401/24 BAJ 단지번호붙이기.md
https://www.acmicpc.net/problem/2667 
30분
1은 집이 있는 곳을, 0은 집이 없는 곳을 나타낸다. 
연결된 집의 모임인 단지를 정의하고, 단지에 번호를 붙이려 한다. 
지도를 입력하여 단지수를 출력하고, 각 단지에 속하는 집의 수를 오름차순으로 정렬하여 출력하는 프로그램을 작성한다.
시작 지점에서 상하좌우를 살펴본 뒤 인접한 지점 중 
해당 좌표가 범위를 벗어나지 않고, 1이 있다면  0으로 바꾸고 더이상 인접한 지점에 1이 없다면 단지수 +1 을 해준다.
기본적인 dfs 문제라 연습하기 좋았다.
=> [20240124] BAJ / 실버1 / 단지번호붙이기 / 신예진

Curry4182/202401/24 더 맵게.md
https://school.programmers.co.kr/learn/courses/30/lessons/42626
30분
입력 받은 배열에서 가장 낮은 두 값을 이용하여 새로운 값을 배열에 넣는다.
이 때 k 이상일 때 까지 이를 반복한다.
제일 낮은 값 두개를 가져오고 다시 넣는 작업을 반복해야 한다. 이 때 logN인 힙 자료구조를 이용하여 효율적으로 문제를 해결한다.
우선순위 큐를 활용하면 빠르게 문제를 풀 수 있지만 라이브러리 없이 구현하는 방법도 알 필요가 있을 것 같다.
=> [20240124] PRG / lv2 / 더 맵게 / 강병곤

HandamdeCloud/202401/25 PRG 기지국 설치.md, HandamdeCloud/202401/26 PRG 스티커모으기(2).md
https://school.programmers.co.kr/learn/courses/30/lessons/12979#
55 분
최고 기지국을 설치한다.
시간복잡도를 줄이기 위한 풀이가 중요하다. 0이 발생하는 구간, 1이 발생하는구간(기지국 설치되어있는)의 차이 길이를 파악해서
그 차이를 나눗셈과 몫을 가지고 몇개나 설치하는지가 중요하다. 즉, 어디에 설치하냐보다 몇개에 초점을 맞추면 풀이가 쉬워진다.
어제 고생했던 엣지케이스를 고려하기에 최적화된 문제였다.!!!
바로 연습했고 바로 적용할 수 있어서 너무 기쁘다. 몬제도 잘 읽었다. 어디에 설치하냐는 전혀 중요하지 않은걸 파악하고 범위가 닿지 않는 구간별로 풀이를 만들어 계산토록하니 풀이가 굉장히 쉬웠다. 추가로 범위를 폭넓게 생각한 연습이 이번 문제풀이에 큰 도움이 된 것같다.
=> [20240125] PRG / LV3 / 기지국 설치 / 조재현

born-A/202401/25 BAJ 연결 요소의 개수.md
https://www.acmicpc.net/problem/11724
15분
방향 없는 그래프가 주어졌을 때, 연결 요소의 개수를 구하는 프로그램을 작성한다. 
모든 노드들을 돌면서 방문하지 않은 노드를 dfs 동작을 하게 하고, answer을 1 증가시킨다.
=> [20240125] BAJ / 실버2 / 연결 요소의 개수 / 신예진

Yiseull/202401/25 BAJ 동물원.md
https://www.acmicpc.net/problem/1309
40분
어떤 동물원에 가로로 두칸 세로로 N칸인 아래와 같은 우리가 있다.
이 동물원에는 사자들이 살고 있는데 사자들을 우리에 가둘 때, 가로로도 세로로도 붙어 있게 배치할 수는 없다. 이 동물원 조련사는 사자들의 배치 문제 때문에 골머리를 앓고 있다.
동물원 조련사의 머리가 아프지 않도록 우리가 2*N 배열에 사자를 배치하는 경우의 수가 몇 가지인지를 알아내는 프로그램을 작성해 주도록 하자. 사자를 한 마리도 배치하지 않는 경우도 하나의 경우의 수로 친다고 가정한다.
- DP 배열을 생성해서 아래와 같이 로직을 구성했는데 메모리 초과가 떴다. n이 100,000이기 때문에 3차원 배열은 당연히 메모리 부족이 뜰 걸 생각 못했다 😅
```python
for i in range(2, n + 1):
dp[i][0] = dp[i - 1][0] + dp[i - 1][1] + dp[i - 1][2]
dp[i][1] = dp[i - 1][0] + dp[i - 1][2]
dp[i][2] = dp[i - 1][0] + dp[i - 1][2]
```
- DP 배열을 선언하지 않고 a, b 변수 두 개로 처리했다. 로직은 위의 DP와 같다.
```python
def solution(n: int) -> int:
a, b = 1, 1
for i in range(n - 1):
a, b = a + b + b, a + b
return (a + b + b) % 9901
```
처음에 보고 되게 간단하다 생각했는데, 생각보다 답이 잘 나오지 않아서 당황했다. 그리고 겨우 …
=> [20240125] BAJ / 실버1 / 동물원 / 박이슬

Curry4182/202401/25 1로 만들기.md
https://www.acmicpc.net/problem/1463
30분
다음 조건으로 1이 될 때 까지의 최소 연산을 구한다. 
X가 3으로 나누어 떨어지면, 3으로 나눈다.
X가 2로 나누어 떨어지면, 2로 나눈다.
1을 뺀다.
중간 연산을 저장하고 이미 구해져있다면 넘어가는 다이나믹 프로그래밍 방식으로 해결한다.
다이나믹 프로그래밍의 기본 개념을 정리할 수 있어서 좋았다.
=> [20240125] BAJ / silver3 / 1로 만들기 / 강병곤

born-A/202401/26 BAJ 바이러스.md
https://www.acmicpc.net/problem/2606
10분
1번 컴퓨터가 웜 바이러스에 걸리면 웜 바이러스는 2번과 5번 컴퓨터를 거쳐 3번과 6번 컴퓨터까지 전파되어
2, 3, 5, 6 네 대의 컴퓨터는 웜 바이러스에 걸리게 된다.
1번 컴퓨터를 통해 웜 바이러스에 걸리게 되는 컴퓨터의 수를 출력하는 프로그램을 작성한다.
전형적인 dfs 풀이 방식을 이용했다.
1번 컴퓨터를 통해 바이러스에 걸리게 되는 컴퓨터의 수를 구하는 것이기에 
dfs문 시작시에 1을 증가하는 것이 아니라 연결되어 있고, 방문하지 않은 컴퓨터라는 조건을 충족시에만
1을 증가시켜야 한다.
문제에서 요구하는 출력이 무엇인지 제대로 확인하고 풀 것 !
=> [20240126] BAJ / 실버3 / 바이러스 / 신예진

Yiseull/202401/26 PRG 주차 요금 계산.md
https://school.programmers.co.kr/learn/courses/30/lessons/92341
35분
- 어떤 차량이 입차된 후에 출차된 내역이 없다면, 23:59에 출차된 것으로 간주합니다.
- 00:00부터 23:59까지의 입/출차 내역을 바탕으로 차량별 누적 주차 시간을 계산하여 요금을 일괄로 정산합니다.
- 누적 주차 시간이 기본 시간이하라면, 기본 요금을 청구합니다.
- 누적 주차 시간이 기본 시간을 초과하면, 기본 요금에 더해서, 초과한 시간에 대해서 단위 시간 마다 단위 요금을 청구합니다.
- 초과한 시간이 단위 시간으로 나누어 떨어지지 않으면, 올림합니다.
주차 요금을 나타내는 정수 배열 fees, 자동차의 입/출차 내역을 나타내는 문자열 배열 records가 매개변수로 주어집니다. 차량 번호가 작은 자동차부터 청구할 주차 요금을 차례대로 정수 배열에 담아서 return 하도록 solution 함수를 완성해주세요.
1. 딕셔너리1에 차량의 입차 시간을 저장한다.
2. 출차인 경우에 딕셔너리2에 누적 주차 시간을 추가한다.
3. 딕셔너리1이 비어있지 않은 경우, 남은 차량에 대해 누적 주차 시간을 추가한다.
4. 모든 차량의 누적 주차 시간의 계산이 끝난 경우, 한 차랑씩 주차 요금을 계산한다.
5. 차량 번호가 작은 자동차부터 주차 요금을 정렬해 반환한다.
- 풀이는 어렵지 않았는데 마지막 정답을 반환할 때, 딕셔너리를 key 값으로 정렬해서 value값만 리스트로 반환하는 것에서 헤메었다. 그래도 금방 해결했다.
- 전에 풀었던 문제였는데 그때의 풀이와 지금의 풀이가 …
=> [20240126] PRG / lv2 / 주차 요금 계산 / 박이슬

Curry4182/202401/26 움직이는 미로 탈출.md
https://www.acmicpc.net/problem/16954
30 분
욱제는 학교 숙제로 크기가 8×8인 체스판에서 탈출하는 게임을 만들었다. 체스판의 모든 칸은 빈 칸 또는 벽 중 하나이다. 욱제의 캐릭터는 가장 왼쪽 아랫 칸에 있고, 이 캐릭터는 가장 오른쪽 윗 칸으로 이동해야 한다.
이 게임의 특징은 벽이 움직인다는 점이다. 1초마다 모든 벽이 아래에 있는 행으로 한 칸씩 내려가고, 가장 아래에 있어서 아래에 행이 없다면 벽이 사라지게 된다. 욱제의 캐릭터는 1초에 인접한 한 칸 또는 대각선 방향으로 인접한 한 칸으로 이동하거나, 현재 위치에 서 있을 수 있다. 이동할 때는 빈 칸으로만 이동할 수 있다.
1초 동안 욱제의 캐릭터가 먼저 이동하고, 그 다음 벽이 이동한다. 벽이 캐릭터가 있는 칸으로 이동하면 더 이상 캐릭터는 이동할 수 없다.
욱제의 캐릭터가 가장 오른쪽 윗 칸으로 이동할 수 있는지 없는지 구해야 한다.
너비 우선 탐색을 이용하여 가능한 경로를 탐색하고 최종 답을 구하였다.
BFS에 대해 연습할 수 있어서 좋았다.
=> [20240126] BAJ / gold3 / 움직이는 미로 탈출 / 강병곤

born-A/202401/29 BAJ 촌수계산.md
https://www.acmicpc.net/problem/2644
30분
여러 사람들에 대한 부모 자식들 간의 관계가 주어졌을 때, 주어진 두 사람의 촌수를 계산하는 프로그램을 작성한다.
일반적인 bfs 문제처럼 방문처리 배열을 만드는 것이 아닌, 촌수를 저장하는 배열로 만들어 0인 경우에만 방문하여 로직을 수행하게 한다.
=> [20240129] BAJ / 실버2 / 촌수계산 / 신예진

Curry4182/202401/29 어른 상어.md, Curry4182/202401/Untitled.html
https://www.acmicpc.net/problem/19237
60분
문제 조건에 맞도록 상어를 움직였을 때 몇초안에 1번 상어만 남는지 구하는 문제이다.
문제 조건을 각각 구현 한 후 1번 상어가 남을 때 까지 반복한다.
문제 조건 하나하나는 어렵지 않지만 이것을 동시에 에러 없이 구현하기가 쉽지 않다.
=> [20240129] BAJ / gold2 / 어른 상어 / 강병곤

Yiseull/202401/29 PRG 양궁대회.md
https://school.programmers.co.kr/learn/courses/30/lessons/92342
60분 이상
=> [20240129] PRG / lv2 /  양궁대회 / 박이슬

born-A/202401/30 BAJ 외판원 순회 2.md
https://www.acmicpc.net/problem/10971
45분
어느 한 도시에서 출발해 N개의 도시를 모두 거쳐 다시 원래의 도시로 돌아오는 순회 여행 경로를 계획하려고 한다. 
각 도시간에 이동하는데 드는 비용은 행렬 W[i][j]형태로 주어진다. W[i][j]는 도시 i에서 도시 j로 가기 위한 비용을 나타낸다. 
N과 비용 행렬이 주어졌을 때, 가장 적은 비용을 들이는 외판원의 순회 여행 경로를 구하는 프로그램을 작성한다.
모든 도시를 다 거쳐야 하기 떄문에 cnt 변수를 사용하여 확인한다.
최소 비용을 구해야하므로 모든 노드들을 시작점으로 하여 돌아야한다.
=> [20240130] BAJ / 실버2 / 외판원 순회 2 / 신예진

BeommoKoo-dev/202401/30 BAJ 16395 파스칼의 삼각형.md
https://www.acmicpc.net/problem/16395
10분
파스칼 삼각형의 n행 k열을 출력
bottom up dp
=> [20240130] BAJ/실버5/파스칼의 삼각형/구범모

Yiseull/202401/30 PRG 양과 늑대.md
https://school.programmers.co.kr/learn/courses/30/lessons/92343
60분
2진 트리 모양 초원의 각 노드에 늑대와 양이 한 마리씩 놓여 있습니다. 이 초원의 루트 노드에서 출발하여 각 노드를 돌아다니며 양을 모으려 합니다. 각 노드를 방문할 때 마다 해당 노드에 있던 양과 늑대가 당신을 따라오게 됩니다. 이때, 늑대는 양을 잡아먹을 기회를 노리고 있으며, 당신이 모은 양의 수보다 늑대의 수가 같거나 더 많아지면 바로 모든 양을 잡아먹어 버립니다. 당신은 중간에 양이 늑대에게 잡아먹히지 않도록 하면서 최대한 많은 수의 양을 모아서 다시 루트 노드로 돌아오려 합니다.
각 노드에 있는 양 또는 늑대에 대한 정보가 담긴 배열 info, 2진 트리의 각 노드들의 연결 관계를 담은 2차원 배열 edges가 매개변수로 주어질 때, 문제에 제시된 조건에 따라 각 노드를 방문하면서 모을 수 있는 양은 최대 몇 마리인지 return 하도록 solution 함수를 완성해주세요.
👉 이 풀이는 DFS로 풀 수 있습니다. 핵심은 노드에 방문하면 방문할 리스트에서 본인을 제거하고 자식 노드들 추가하는 것입니다.  이때 리스트를 새로 만들어야 합니다. 안그러면 하나의 리스트가 계속 업데이트 되어 제대로된 정답이 나오지 않습니다. 
예를 들어, 처음에는 0번 노드에서 시작하기 때문에 방문할 리스트는 [0]이고, 0번에 방문하면 방문할 리스트에서 0번 노드를 삭제하고 그 자식 노드인 1번, 2번 노드가 들어갑니다.
1. 노드를 방문하고 양과 늑대의 갯수를 업데이트 한다. 
2. 양의 수가 …
=> [20240130] PRG / lv3 / 양과 늑대 / 박이슬

Curry4182/202401/30 레벨 햄버거.md
https://www.acmicpc.net/problem/16974
40분
상근날드에서 오랜만에 새로운 햄버거를 출시했다. 바로 레벨-L 버거이다. 레벨-L 버거는 다음과 같이 만든다.
-레벨-0 버거는 패티만으로 이루어져 있다.
- 레벨-L 버거는 햄버거번, 레벨-(L-1) 버거, 패티, 레벨-(L-1)버거, 햄버거번으로 이루어져 있다. (L ≥ 1)
위와 같이 패티를 만들었을 때 먹은 패티가 몇 장일지 구한다.
버거와 패티를 배열에 저장하고 문제에 제시한 형식이 맞는지 확인하고 저장한다.
문제에 제시된 부분을 읽고 구현을 빨리 하는 부분에서 좀더 공부해야 할 거 같다.
=> [20240130] BAJ / gold5 / 레벨 햄버거 / 강병곤

BeommoKoo-dev/202401/31 BAJ 16988 Baaaaaaaaaduk2 (Easy).md, BeommoKoo-dev/202402/01 BAJ 2655 가장높은탑쌓기.md
https://www.acmicpc.net/problem/16988
120분
바둑판의 2곳을 골라 바둑돌을 두었을 때, 상대방의 돌을 잡을 수 있는 값 중 최댓값을 구하시오.
dfs를 이용해 바둑판의 두 곳을 조합으로 고른다.
이후 상대방의 바둑돌 기준으로 bfs를 돌려, 상대방의 바둑돌이 둘러쌓여졌는지를 판단한다.(빈칸이 없으면 둘러쌓여진 것이다.)
둘러쌓여졌다면 count에 더해준 뒤 ans와 비교하여 최댓값으로 갱신.
2차원 배열에서의 조합을 연습할 수 있었던 문제. 추천한다.
=> [20240131] BAJ/골드3/Baaaaaaaaaduk2 (Easy)/구범모

HandamdeCloud/202401/31 BOJ 무기공학.md
이전과 동일
40 분
부메랑을 만드는데 최대값을 만드는 경우
함수 : 방향별로 함수를만든다. (범위탐색, 방문처리)
진행조건 : 순차적, 백트래킹
탈출조건 : 더이상 탐색할 수 있는 행이 없을때
가장 어려웠던건 진행방향이었다. 부메랑을 만들고 난 후 어디로 이동해야할 지 몰라서 이부분만 답을 참고했다. 그랬더니 일반 bfs처럼 옆으로 순차 탐색을 할 수 있었다. 열 범위에 다다르면 다음 행으로 진행하는 방식으로 이동하며 문제를 해결할 수 있어 진행조건의 틀을 조금 깨야할 필요가 있겠다고 생각했다.
=> [20240131] BOJ / 골드4 / 무기공학 / 조재현

born-A/202401/31 BAJ 문서 검색.md
https://www.acmicpc.net/problem/1543
30분
문자열을 하나씩 비교해가면서 cnt를 증가시킨다.
이미 검색한 문자열을 또 검색하면 안되므로 인덱스를 pattern.length()-1 로 증가시켜 탐색한다.
그리디로 풀었는데 다른 사람의 풀이를 보니 더 빨리 풀 수 있는거 같다.
```java 
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
String S = br.readLine();
String S2 = br.readLine();
int size = S.length();
int size2 = S2.length();
S = S.replace(S2, "");
System.out.println((size - S.length()) / size2);
}
```
코드도 간결하고 그리디로 푼 방식보다 40ms 정도 더 빠르다.
=> [20240131] BAJ / 실버5 / 문서 검색 / 신예진

Yiseull/202402/01 PRG 사라지는 발판.md
https://school.programmers.co.kr/learn/courses/30/lessons/92345
120분 이상
=> [20240201] PRG / lv3 / 사라지는 발판 / 박이슬

HandamdeCloud/202402/01 BOJ 20056 마법사 상어와 파이어볼.md, HandamdeCloud/202402/02 BOJ 20056 마법사 상어와 파이어볼.md
동일
70 분 - 실패
기존과 같음
메소드를 일부러 나누어 생각
1. 이동
2. 판정(홀짝)
3. 중복검사
풀이는잘 나누고 테케 3개는 맞췄지만 네번째 테케가 통과하지 못하는데, 그 문제를 파악하기가 어려웠다.
보면 구현이고 문제를 잘 나누면 쉽게 해결할 수 있겠다 싶었는데 생각보다 난이도가 어려웠다.
디버깅을 하면서 문제를 해결해보고 싶었는데, 풀이가 길어지면서 머리가 그 내용들을 잘 따라가지 못하는 것 같다. 
게속해서 이런 문제들에 익숙해지면서 코드를 따라갈 줄 아는 연습이 필요해보인다.
=> [20240202] BOJ / 골드4 / 마법사 상어와 파이어볼 / 조재현

born-A/202402/02 BAJ 파티.md
https://www.acmicpc.net/problem/1238
60분 - 실패
되돌아가는 부분을 어떻게 작성해야할지 감이 안온다.
=> [20240202] BAJ / 골드3 / 파티 / 신예진

Yiseull/202402/02 PRG [PCCP 모의고사 1] 2번.mc
https://school.programmers.co.kr/learn/courses/15008/lessons/121684
60분 이상
=> [20240202] PRG / lv2 / [PCCP 모의고사 1] 2번 / 박이슬

HandamdeCloud/202402/05 BOJ 1325 효율적인 해킹.md
https://www.acmicpc.net/problem/1325
50 분 - 실패
최소 컴퓨터로 최대한 많은 해킹을 하는 방버 
dfs풀이. bfs로는 해결할 수 있을 것 같았지만, 일부러 dfs로 시도해보았다.
방문 할 수 있는 곳을 dfs로 이어들어가서 모두 탐색하고 나오는 과정으로 문제를 해결했다.
풀이는 적절하게 답을 내지만, 시간초과 이슈로 해결하지 못함
풀이에는 문제가 없었지만 시간초과 이슈에 대해서 계속 고민해볼 수 있었던 문제,
모든 문제가 dfs로 풀릴 수 잇는것은 아니었다. 항상 그 깊이가 어디까지 이어지는지 문제 조건을 보고 더 나은 풀이를 선택하자.
=> [20240205] BOJ / 실버1 / 효율적인 해킹 / 조재현

born-A/202402/05 BAJ 걷기.md
https://www.acmicpc.net/problem/1459
40분
걸을 수 있는 방법은 두가지 인데, 
하나는 도로를 따라서 가로나 세로로 한 블록 움직여서 이번 사거리에서 저 사거리로 움직이는 방법이고, 
블록을 대각선으로 가로지르는 방법이 있다.
집으로 가는데 걸리는 최소시간을 구하는 프로그램을 작성한다.
최소 시간이기 때문에 수평, 대각선 이동 시간을 따져 경우의 수를 나눈다.
1. 수평으로만 이동하는 경우
2. 대각선으로만 이동하는 경우
3. 대각선 + 수평을 이동하는 경우
=> [20240205] BAJ / 실버4 / 걷기 / 신예진

Yiseull/202402/05 PRG [PCCP 모의고사 1] 3번.md
https://school.programmers.co.kr/learn/courses/15008/lessons/121685
60분
=> [20240205] PRG / lv2 / [PCCP 모의고사 1] 3번 / 박이슬

born-A/202402/06 BAJ 파티.md
https://www.acmicpc.net/problem/1238
60분
N개의 숫자로 구분된 각각의 마을에 한 명의 학생이 살고 있다.
X번 마을에 모이기로 하였고,  총 M개의 단방향 도로들이 있고 i번째 길을 지나는데 Ti의 시간을 소비한다.
학생들은 X까지 걸어가서 다시 그들의 마을로 최단시간으로 돌아와야 한다. 
N명의 학생들 중 오고 가는데 가장 많은 시간을 소비하는 학생은 누구인지 구하는 문제.
모든 정점에 대해서 X까지의 거리만 알아내면 된다.
X를 시작점으로 잡고 다익스트라 알고리즘을 수행한 후, 
입력을 반대로 저장한 배열에서 X를 시작점으로 잡고 다익스트라 알고리즘을 수행하면 된다.
왕복하는데에 있어 감을 못잡았던 문제, 단순하게 입력을 반대로 저장한 배열을 만들면 일반 다익스트라 문제와 같았다.
=> [20240206] BAJ / 골드3 / 파티 / 신예진

Yiseull/202402/06 PRG [PCCP 모의고사 1] 4번.md
https://school.programmers.co.kr/learn/courses/15008/lessons/121686#
120분
=> [20240206] PRG / lv3 / [PCCP 모의고사 1] 4번 / 박이슬

Curry4182/202402/06 외판원 순회.md
https://www.acmicpc.net/problem/16991
60 분
=> [20240206] BAJ / Gold3 / 외판원 순회 3 / 강병곤

HandamdeCloud/202402/06 PRG 최고의 집합.md, HandamdeCloud/202402/07 PRG 문자열 압축.md
https://school.programmers.co.kr/learn/courses/30/lessons/12938?language=python3
20 분
합이 s와 같고 가장 큰 집합 배열을 출력한다.
쉽다. 종료조건은 자연수개수보다 s가 작으면 불가능
중앙값의 곱이 가장 크기 때문에 그에 따른 값만 일부 나머지만큼 조정해주면 된다.
쉬운 풀이었지만, 생각이 조금 깊었다. 내가 생각한게 맞는지 풀이를 적용하기 전 문제조건을 잘 확인하는정도만 신경쓰면 될 것 같다.
몫과 나머지에 많이 약했는데, 한번 연습하고 간 느낌
=> [20240206] PRG / Lv3 / 최고의 집합 / 조재현

born-A/202402/07 BAJ 영역 구하기.md
https://www.acmicpc.net/problem/2583
40분
M, N과 K 그리고 K개의 직사각형의 좌표가 주어질 때, 
K개의 직사각형 내부를 제외한 나머지 부분이 몇 개의 분리된 영역으로 나누어지는지, 
그리고 분리된 각 영역의 넓이가 얼마인지를 구하여 이를 출력한다.
직사각형의 영역들을 1로 채우고 0이 아닌 부분을 만나면 dfs를 수행하면 된다.
문제에서 주어진 x,y좌표가 반대라서 헤맸다.
처음부터 입력을 M,N으로 받고, x가 아닌 y 좌표를 기준으로 반복문을 수행하는게 헷갈리지 않았을거 같다.
=> [20240207] BAJ / 실버1 / 영역 구하기 / 신예진

BeommoKoo-dev/202402/07 BAJ 1577 도로의 개수.md
https://www.acmicpc.net/problem/1577
60분
공사중인 도로 사이는 건너지 못하고, map의 끝에 도달하는 방법의 수.
공사중인 도로는 별도의 배열에 저장한 이후, bottom up dp로 경우의 수를 쌓아가며 해당 도로가 공사중이면 경우의 수에 포함시키지 않았다.
맞왜틀 오지게 했다.
=> [20240207] BAJ/골드5/도로의 개수/구범모

Curry4182/202402/07 청소년 상어.md
https://www.acmicpc.net/problem/19236
60분
문제 조건과 방법에 따라 배열위의 상어를 움직이고 총 먹은 먹이의 합을 구하는 문제
문제에 제시된 방법대로 상어를 움직이고 합을 더한다.
구현 문제는 작은 문제들의 조합이라고 생각하고 각 단계마다 영향을 끼치지 않도록 설계하는게 중요한 것 같다.
=> [20240207] BAJ / Gold2 / 청소년 상어 / 강병곤

Yiseull/202402/07 PRG 신입사원 교육.md
https://school.programmers.co.kr/learn/courses/15009/lessons/121688
10분
모든 신입사원들의 능력치는 정수로 표현되어 있는데, 2명의 신입사원이 같이 공부하면 서로의 능력을 흡수하여 두 신입사원의 능력치는 공부 전 두 사람의 능력치의 합이 됩니다. 선발한 2인의 교육이 끝나면 민수는 다시 2인을 선발하여 교육을 진행할 수도 있습니다. 이때 한번 민수에게 선발된 사원이 다시 선발될 수도 있습니다. 민수가 교육한 신입사원들을 제외한 다른 신입사원들의 능력치는 변하지 않습니다. 민수는 산업스파이이기 때문에 교육 후 모든 신입사원들의 능력치의 합을 최소화하고 싶습니다.
신입사원들의 능력치를 나타내는 정수 배열 ability와 민수가 교육을 진행해야 하는 횟수를 나타내는 정수 number가 주어졌을 때, 교육 후 모든 신입사원들의 능력치의 합의 최솟값을 return 하는 solution 함수를 완성하세요.
✨ 핵심은 우선순위 큐를 이용하는 것! -> 최소 힙으로 구현
1. 주어진 능력들을 우선순위 큐로 만든다. (최소 힙)
2. 우선순위가 가장 높은 2개를 pop해서 더한 다음, 더한 값을 우선순위 큐에 2번 넣는다. (신입사원이 2명이기 때문에)
3. 주어진 number만큼 반복한다.
4. 우선순위 큐에 있는 원소들의 합이 교육 후 모든 신입사원들의 능력치의 합의 최솟값이다.
문제를 보자마자 우선순위 큐를 이용하는 문제구나 떠올려서 바로 풀었다! 그래서 그런가 레벨 2 같이 안느껴지고 레벨 1로 느껴질 정도로 되게 쉬운 문제였다. ㅎㅎ
=> [20240207] PRG / lv2 / 신입사원 교육 / 박이슬

HandamdeCloud/202402/08 BAJ 21278 호석이 두마리 치킨.md
https://www.acmicpc.net/problem/21278
70 분 - 실패
호석이 두마리 치킨의 적절한 위치와 최단거리 값을 구해야 한다.
치킨집 1, 2 가 위치할 수 있는 모든 경우의 수를 탐색한다. 그리고 그 가운데에서 최단거리를 구해야 한다.
최단거리를 구하도록 2차원 배열에 방문여부, count, 재귀식의 함수를 구현하려고 했지만, 원하는 결과를 얻을 수 없었다.
최단거리 라고 하면 떠올려야 하는 알고리즘이 있었지만 ,전혀 인지하지 못했다. 단순히 그래프 탐색으로만 해결하려고 하다보니 문제조건과 내용이 까다롭게 느껴졌다. 모든 최단거리 알고리즘을 다 시한번 정리하고 적용할 수 있도록 연관지어서 생각하는 연습을 꼭해야겠다.
=> [20240208] BAJ / 골드5 / 호석이두마리치킨 / 조재현

Yiseull/202402/08 PRG 카페 확장.md
https://school.programmers.co.kr/learn/courses/15009/lessons/121689
20분
주원이네 카페에는 영업을 시작하자마자 0초에 손님 한 명이 가게에 도착하고, 정확히 k초마다 새로운 손님 한 명이 카페에 와서 줄을 섭니다. 손님들은 키오스크를 통해 주문하고, 주원이는 주문받은 순서대로 음료를 만듭니다. 주원이는 음료를 한 번에 하나씩 만들며, 지금 만들고 있는 음료를 다 만들면 다음 음료를 만들기 시작합니다. 손님은 자신이 주문한 음료를 받자마자 카페를 나갑니다. 주원이네 카페에는 여러 종류의 음료를 판매하고 있는데 각 음료들은 0번부터 차례대로 번호가 지정되어 있습니다. 또한 주원이가 같은 종류의 음료를 만드는데 걸리는 시간은 항상 동일합니다.
주원이네 카페에서 판매하는 각 음료들의 제조 시간을 담은 정수 배열 menu와 오늘 손님들이 주문한 음료가 순서대로 적힌 배열 order, 새로운 한 명의 손님이 방문하는데 걸리는 시간인 k가 매개변수로 주어집니다. 오늘 카페에 동시에 존재한 손님 수의 최댓값을 return 하도록 solution 함수를 작성해주세요.
1.  처음에 손님이 음료 주문을 하면 음료가 완성되는 시각을 큐에 넣고, count(현재 존재하는 손님 수)를 +1 한다.
2. 다음 손님의 주문을 받기 전에 현재 시간과 비교해서 완성된 음료들은 다 큐에서 제거하고 count를 -1 한다.
위의 방법으로 풀어나가면 된다. 여기서 주의해야 할 점은 음료가 완성되는 시각이다.
(1) 큐에 음료가 담겨있는 경우에는 큐에 마지막 시각에 음료 제조 시간을 더해야 …
=> [20240208] PRG / lv3 / 카페 확장 / 박이슬

born-A/202402/08 BAJ 체인.md
https://www.acmicpc.net/problem/2785 
50분
가능한 한 적은 고리를 열고 닫아서, 모든 체인을 하나의 긴 체인으로 연결하려고 한다.
체인의 개수와 각각의 체인의 길이가 주어지면, 하나의 긴 체인으로 모든 체인을 묶기 위해 희원이가 열고 닫아야할 최소한의 고리 수를 구한다.
가장 짧은 체인으로 고리를 만들어 가장 긴 체인부터 연결하며 체인의 개수가 1이 될 때까지 반복한다.
예제 이해가 안돼서 시간이 오래 걸렸다.
=> [20240208] BAJ / 실버2 / 체인 / 신예진

Curry4182/202402/08 수 고르기.md
https://www.acmicpc.net/problem/2230
30분
차이가 M만큼 나는 수 중에서 최소인 값을 출력하는 문제
배열의 길이가 10^5 임으로 O(n^2)로 풀경우 시간 제한에서 걸린다.
따라서 초기 배열에 O(NlogN)으로 정렬 후 O(N) 투포인터 알고리즘으로 차이가 M나는 것 중 가장 작은 값을 찾아 출력하였다.
단순 투포인터 라도 응용하는 문제가 제출될 경우 투포인터인지 알기가 매우 어려운 것같다.
=> [20240208] BAJ / Gold5 / 수 고르기 / 강병곤

HandamdeCloud/202402/13 PRG 프랜즈4블록.md
https://school.programmers.co.kr/learn/courses/30/lessons/17679
60 분
2*2가 되면 사라지고 위에 값이 내려간다. 사라지는 블록 개수를 구하기
먼저 2*2가 되는 조건을 탐색하고 집합에 값을 넣었다.
그릐고. 값을 내려야하는데, 이 과정에서 값을 일일이 변환해주면서 처리했다.
후처리에서 고민이 많았는데, 이 값을 빈 리스트로 반환해 다음 과정에서 덜 헷갈리도록 설정했다.
그리고 이 과정은 반복되어야했는데, 한번이라도 빈 리스트가 검출되지 않으면 while문을 탈출하도록 했다. 
구현문제, 풀이계획대로 문제를 풀었다.
마지막에 검사하는 단계에서 뒷부분 답을 참고해서 조금 아쉬움이 있었다. while문 안에 while문을 넣는 처리는 항상 최후의 수단으로 생각하다보니 어려움을 겪었는데, 가능하다면. 적극적으로 사용하는게 좋아보인다.
=> [20240213] PRG / LV2 / 프렌즈4블록 / 조재현

Yiseull/202402/13 BAJ 회전 초밥.md
https://www.acmicpc.net/problem/2531
20분
새로 문을 연 회전 초밥 음식점이 불경기로 영업이 어려워서, 다음과 같이 두 가지 행사를 통해서 매상을 올리고자 한다.
1. 원래 회전 초밥은 손님이 마음대로 초밥을 고르고, 먹은 초밥만큼 식대를 계산하지만, 벨트의 임의의 한 위치부터 k개의 접시를 연속해서 먹을 경우 할인된 정액 가격으로 제공한다.
2. 각 고객에게 초밥의 종류 하나가 쓰인 쿠폰을 발행하고, 1번 행사에 참가할 경우 이 쿠폰에 적혀진 종류의 초밥 하나를 추가로 무료로 제공한다. 만약 이 번호에 적혀진 초밥이 현재 벨트 위에 없을 경우, 요리사가 새로 만들어 손님에게 제공한다.
위 할인 행사에 참여하여 가능한 한 다양한 종류의 초밥을 먹으려고 한다.
회전 초밥 음식점의 벨트 상태, 메뉴에 있는 초밥의 가짓수, 연속해서 먹는 접시의 개수, 쿠폰 번호가 주어졌을 때, 손님이 먹을 수 있는 초밥 가짓수의 최댓값을 구하는 프로그램을 작성하시오.
풀이의 핵심은 왼쪽에서 오른쪽으로 이동하면서 현재 고른 초밥을 계속해서 업데이트 하는 것이다. 살펴보는 구간은 문제에서 주어진 k개로 고정한다.
이때 현재 고른 초밥은 딕셔너리를 사용하여 저장한다. 딕셔너리를 사용하는 이유는 현재 어떠한 초밥의 종류가 포함되어 있는지를 O(1)로 확인할 수 있고, 딕셔너리의 길이를 통해 현재 포함된 초밥의 종류를 distinct하게 알 수 있기 때문이다.
1. 쿠폰으로 받은 초밥을 딕셔너리에 넣는다.
2. 초밥 배열에서 K개의 초밥을 확인하여 딕셔너리에 넣는다.
3. 한 칸씩 오른쪽으로 이동하면서 고른 …
=> [20240213] BAJ / 실버1 / 회전 초밥 / 박이슬

Curry4182/202402/13. 동전2.md
https://www.acmicpc.net/problem/2294
60분
=> [20240213] BAJ / Gold2 / 동전2 / 강병곤

HandamdeCloud/202402/14 PRG 방금그곡.md
35 분 - 실패
요구 조건에 맞게 구현하면 된다.
여러 조건들에 맞춰서 해결하는 키워드가 중요하다. 시분초 변환, 정렬 등 의 조건 처리가 중요
가장 중요했던건 문자열 처리 같다. 정렬과 무자열 활용은 기본이지만, 문자값을 대체하는 과정에서 많은 어려움읆 겪었고 결국 해결하지 못했다. 임의로 값을 변경해 인덱스 문제를 해결함에 있어 새로운 아이디어를 얻었다. 카캌오는 이런 유형의 풀이를 많이 낮은레벨에서 의도하는 것 같은데, 이를 잘 활용하는 연습이 필요해보인다.
=> [20240214] PRG / LV2 / 방금그곡 / 조재현

BeommoKoo-dev/202402/14 BAJ 14658 하늘에서 별똥별이 빗발친다.md
https://www.acmicpc.net/problem/14658
30분
격자에 떨어지는 별똥별을, l x l 칸의 방석으로 최대한 막을 때, 막지 못하는 별똥별의 수
n, m이 너무 커 격자 전체를 탐색하는 것은 비효율 적이다.
별똥별의 수가 현저히 작으므로, 별똥별을 기준으로 탐색하여 방석을 펼치는게 효율적이다.
서로 다른 별똥별을 선택하여 두 별똥별의 좌상단 교점을 기준으로 방석을 펼쳐 브루트 포스로 탐색 후,
막을 수 있는 별똥별을 최댓값으로 갱신하여 답을 구한다.
=> [20240214] BAJ/골드3/하늘에서 별똥별이 빗발친다/구범모

born-A/202402/14 BAJ 반복수열.md
반복수열의 규칙에 어긋나는 처음 수가 어디까지인지 찾으면 된다.
'어떤 수가 반복되지 않는가'가 아닌, 개수를 찾는 것이 목표이기 때문에 반복되는 구간이 시작되는 인덱스를 찾으면 그 전까지는 우리가 찾고자 하는 수이다.
25분
D[1] = A
D[n] = D[n-1]의 각 자리의 숫자를 P번 곱한 수들의 합
예를 들어 A=57, P=2일 때, 수열 D는 [57, 74(=52+72=25+49), 65, 61, 37, 58, 89, 145, 42, 20, 4, 16, 37, …]이 된다. 
그 뒤에는 앞서 나온 수들(57부터가 아니라 58부터)이 반복된다.
이와 같은 수열을 계속 구하다 보면 언젠가 이와 같은 반복수열이 된다. 이때, 반복되는 부분을 제외했을 때, 수열에 남게 되는 수들의 개수를 구하는 프로그램을 작성한다.
반복수열의 규칙에 어긋나는 처음 수가 어디까지인지 찾으면 된다.
반복되는 구간이 시작되는 인덱스를 찾으면 그 전까지는 찾고자 하는 수이다.
=> [20240214] BAJ / 실버4 / 반복수열 / 신예진

Curry4182/202402/14 쉬운 계단 수.md
https://www.acmicpc.net/problem/10844
30분
계단 수를 만족하는 수를 입력된 N 자리 만큼 몇개 만들 수 있는지 출력하는 문제
dp를 사용하여 이전 자리수를 저장하여 계산 한다.
다양한 방법으로 다이나믹 프로그래밍을 해야겠다고 생각이 든다.
=> [20240214] BAJ / 실버1 / 쉬운 계단 수 / 강병곤

HandamdeCloud/202402/15 PRG 양궁대회.md
60 분 - 실패
라이언이 이기되 여러 조건을 따져 최적의 결과를 찾아야 한다.
dfs 혹은 bfs식으로 모든 경우의 수를 확인해 탐색해야한다.
문제 이해부터 어려웠던 문제,
어떻게 문제를 접근해야할 지 알고리즘으로 접근하느 방법을 시도해보았어야 ㅎㅆ다. 노가다로 했을 때 dfs로 풀어볼 수 잇겠다는 각이 보였을텐데, 자꾸만 내용이 길어지다 보니 객체지햐엊ㄱ으로 구현을 어떻게 나눠야겠다는 생각에서 끝나 구현관점에서만 접근하려고 했던 것 같다.
dfs로 접근하는 경우에 알아두면 좋을점은 copy를 활용해 내가 탐색한 결과를 답에 복사시켜 넣는 방법이 좋겠다고 느껴진다. 
+ 이전 문제였지만 문자열은 .replace() 를 꼭 생각하기
=> [20240215] PRG / LV2 / 양궁대회 / 조재현

Yiseull/202402/15 PRG N개의 최소공배수.md
https://school.programmers.co.kr/learn/courses/30/lessons/12953
10분
두 수의 최소공배수(Least Common Multiple)란 입력된 두 수의 배수 중 공통이 되는 가장 작은 숫자를 의미합니다. 예를 들어 2와 7의 최소공배수는 14가 됩니다. 정의를 확장해서, n개의 수의 최소공배수는 n 개의 수들의 배수 중 공통이 되는 가장 작은 숫자가 됩니다. n개의 숫자를 담은 배열 arr이 입력되었을 때 이 수들의 최소공배수를 반환하는 함수, solution을 완성해 주세요.
=> [20240215] PRG / lv2 / N개의 최소공배수 / 박이슬

born-A/202402/15 BAJ 성곽.md
https://www.acmicpc.net/problem/2234
60분 - 실패
=> [20240215] BAJ / 골드3 / 성곽 / 신예진

Curry4182/202402/15 제곱수의 합.md
https://www.acmicpc.net/problem/1699
60 분
제곱 수의 합으로만 수를 표현할 때 입력받은 N에 대해서 제곱수의 합의 최소길이를 출력
i의 제곱수의 최소합의 최소 길이를 dp[i]로 정의하고 dp[i-j^2] + 1 에 대해서 가장 작은 수를 저장하고 dp[N]을 출력 
처음 수를 정의 할 때 똑바로 하는게 시간을 아끼는 지름길이라는 것을 다시 한번 더 되새김
=> [20240215] BAJ / 실버2 / 제곱 수의 합 / 강병곤

born-A/202402/16 BAJ 초콜릿 식사.md
https://www.acmicpc.net/problem/2885
30분
K개 정사각형을 만들기 위해서, 최소 몇 번 초콜릿을 쪼개야 하는지와 사야하는 가장 작은 초콜릿의 크기를 구하는 프로그램을 작성한다.
size가 k보다 작다면 계속 제곱을 시켜줘서 최소 초콜릿 크기를 구한다.
size가 k보다 더 크다면 size를 반으로 나눠주고 count를 증가시켜준다. 
그리고 size가 k보다 작거나 같다면 k-=size를 해줘서 구해야하는 초콜릿 크기를 줄여나간다.
=> [20240216] BAJ / 실버2 / 초콜릿 식사 / 신예진

Yiseull/202402/16 BAJ 사냥꾼.md
https://www.acmicpc.net/problem/8983
80분
KOI 사냥터에는 N 마리의 동물들이 각각 특정한 위치에 살고 있다. 사냥터에 온 사냥꾼은 일직선 상에 위치한 M 개의 사대(총을 쏘는 장소)에서만 사격이 가능하다. 편의상, 일직선을 x-축이라 가정하고, 사대의 위치 x1, x2, ..., xM은 x-좌표 값이라고 하자. 각 동물이 사는 위치는 (a1, b1), (a2, b2), ..., (aN, bN)과 같이 x,y-좌표 값으로 표시하자. 동물의 위치를 나타내는 모든 좌표 값은 양의 정수이다.
사냥꾼이 가지고 있는 총의 사정거리가 L이라고 하면, 사냥꾼은 한 사대에서 거리가 L 보다 작거나 같은 위치의 동물들을 잡을 수 있다고 한다. 단, 사대의 위치 xi와 동물의 위치 (aj, bj) 간의 거리는 |xi-aj| + bj로 계산한다.
사대의 위치와 동물들의 위치가 주어졌을 때, 잡을 수 있는 동물의 수를 출력하는 프로그램을 작성하시오.
=> [20240216] BAJ / 골드4 / 사냥꾼 / 박이슬

BeommoKoo-dev/202402/19 BAJ 17089 세 친구.md
https://www.acmicpc.net/problem/17089
10분
각각이 친구 관계인 세명을 골랐을 때, 친구의 합의 최솟값을 구하라.
처음에 브루트 포스를 떠올렸으나, O(N^3)이라 시간초과를 생각했다.
하지만 if문으로 친구관계인지를 검사하면 O(N^3)보다 훨 줄여서, 최대 O(MC2)정도만을 탐색하므로 시간초과를 피할 수 있다.
=> [20240219] BAJ/골드5/세 친구/구범모

HandamdeCloud/202402/19 PRG 괄호 변환.md
https://school.programmers.co.kr/learn/courses/30/lessons/60058
70 분 - 실패
올바른 배열을 만들어내기
올바른 배열인지확인, 분리, 재귀 방식으로 구현을 해내야 한다.
올바르지 않은 배열 결과는 안나오지는 않음
메소드 구분은 어렵지 않았다. 
각 함수를 만들때 너무 많은 경우의 수를 생각하고, 복잡하게 슬라이싱을 하다보니 정상적인 결과를 찾지 못했닫.
마지막으로 재귀를 활용하는 것과, while문 사용을 고민했었는데, 결과가 잘 나타나지 못했다.
인덱스 활용을 하는 방법을 조금이나마 더 배운것 같아 계속 기록하고 활용하는 방법밖에는 없겠다.
=> [20240219] PRG / LV2 / 괄호 변환 / 조재현

born-A/202402/19 BAJ 퍼즐.md
https://www.acmicpc.net/problem/1525
60분 - 실패
=> [20240219] BAJ / 골드2 / 퍼즐 / 신예진

Curry4182/202402/20 동물원.md
https://www.acmicpc.net/problem/1309
30분
N이 주어질 때 2*N 우리에 사자를 넣는 경우의 수를 구하여야 한다.
이 때 가로세로에 사자가 없어야 하고 사자의 수는 0부터 자유롭게 넣을 수 있다.
우리의 세로 길이 N일 때 가로의 넣는 경우의 수는 왼쪽, 오른쪽, 아예 안 넣는 경우의 수 세가지 이다.
이를 배열로 나타내면 배열의 크기는 dp[N][3] 과 같다.
이를 이용해 다이나믹 프로그래밍으로 문제를 해결하였다.
문제를 dp로 생각하는게 쉽지 않은것 같다. 좀더 연습이 필요하다.
=> [20240220] BAJ / 실버1 / 동물원 / 강병곤

Yiseull/202402/20 BAJ 숨바꼭질 3.md
https://www.acmicpc.net/problem/13549
45분
수빈이는 동생과 숨바꼭질을 하고 있다. 수빈이는 현재 점 N(0 ≤ N ≤ 100,000)에 있고, 동생은 점 K(0 ≤ K ≤ 100,000)에 있다. 수빈이는 걷거나 순간이동을 할 수 있다. 만약, 수빈이의 위치가 X일 때 걷는다면 1초 후에 X-1 또는 X+1로 이동하게 된다. 순간이동을 하는 경우에는 0초 후에 2*X의 위치로 이동하게 된다.
수빈이와 동생의 위치가 주어졌을 때, 수빈이가 동생을 찾을 수 있는 가장 빠른 시간이 몇 초 후인지 구하는 프로그램을 작성하시오.
=> [20240220] BAJ / 골드5 / 숨바꼭질 3 / 박이슬

HandamdeCloud/202402/20 PRG 호텔 대실.md, HandamdeCloud/202402/21 PRG 수식 최대화.md
https://school.programmers.co.kr/learn/courses/30/lessons/155651
30 분
조건에 맞는 최소 호탤 개수 구하기
정렬과 시간 변환을 잘 사용해서 문제를 해결하면 된다.
오랜만에 문제를 맞춰싿..
for-else문을 오랜만에 사용하고, 정렬조건과 시간복잡도를 모두 고려해서 풀 수 있어서 완벽하게 풀어낸 좋은 경험이었다.
=> [20240220] PRG / LV2 / 호텔 대실 / 조재현

born-A/202402/20 BAJ 퍼즐.md
https://www.acmicpc.net/problem/1525
40분
"123456789" 를 만드는 최소 이동 횟수를 구하는 프로그램을 작성
Map의 Key로 배열의 상태를 저장하면 된다. 
Value로는 move를 카운트해서 저장한다.
Map을 사용하면 쉽게 접근하여 해결할 수 있는 문제.
문제를 많이 풀어봐야겠다.
=> [20240220] BAJ / 골드2 / 퍼즐 / 신예진

BeommoKoo-dev/202402/20 BAJ 1508 레이스.md, BeommoKoo-dev/202402/21 BAJ 2073 수도배관공사.md, BeommoKoo-dev/202402/22 BAJ 1749 점수따먹기.md
https://www.acmicpc.net/problem/1508
40분
k개의 지점에 m명만큼의 심판을 배치했을 때, 가장 가까운 심판간의 거리를 최댓값으로 배치했을 때의 배치를 구하라.
최솟값을 최대로, 최댓값을 최소로 같은 문제는 매개변수 탐색의 전형적인 구문이다.
심판간의 거리를 매개변수로 잡아서 해당 거리보다 크게 차이나면 그 지점마다 심판을 배치하여 m명만큼을 만족하면 심판간의 거리를 늘려주고,
그렇지 않다면 심판간의 거리를 좁혀주었다.
=> [20240220] BAJ/골드2/레이스/구범모

born-A/202402/21 BAJ 지뢰찾기.md
https://www.acmicpc.net/problem/9082
40분
2×N 배열이 주어지면 주어진 배열에 있는 모든 지뢰의 개수(*까지 포함)를 찾는 프로그램을 작성한다.
각 테스트 케이스에 대해서 주어진 배열에 있는 모든 지뢰의 수를 한 줄에 하나씩 출력한다. 
지뢰의 수가 여럿이 될 수 있으면 가능한 지뢰의 수 중 최댓값을 출력한다.
주변 지뢰의 수를 다 더한 후 (total + 2) / 3 을 구하면 된다.
=> [20240221] BAJ / 골드4 / 지뢰찾기 / 신예진

Curry4182/202402/21 가장 긴 증가하는 부분수열 4.md
https://www.acmicpc.net/problem/14002
40분
길이가 증가하는 수열 중에 가장 긴 수열을 반환한다.
수열의 길이를 배열에 저장하고 다이나믹 프로그래밍 방식으로 해결한다.
계속해서 다이나믹 프로그래밍 문제를 풀고 있는데 쉽게 아이디어를 떠오르지 않고 매번 볼 때 마다 새롭다 😥
=> [20240221] BAJ / 골드4 / 가장 긴 증가하는 부분수열4 / 강병곤

Yiseull/202402/22 PRG 순위.md
https://school.programmers.co.kr/learn/courses/30/lessons/49191
90분
n명의 권투선수가 권투 대회에 참여했고 각각 1번부터 n번까지 번호를 받았습니다. 권투 경기는 1대1 방식으로 진행이 되고, 만약 A 선수가 B 선수보다 실력이 좋다면 A 선수는 B 선수를 항상 이깁니다. 심판은 주어진 경기 결과를 가지고 선수들의 순위를 매기려 합니다. 하지만 몇몇 경기 결과를 분실하여 정확하게 순위를 매길 수 없습니다.
선수의 수 n, 경기 결과를 담은 2차원 배열 results가 매개변수로 주어질 때 정확하게 순위를 매길 수 있는 선수의 수를 return 하도록 solution 함수를 작성해주세요.
=> [20240222] PRG / lv3 / 순위 / 박이슬

born-A/202402/22  BAJ 경로 찾기.md
https://www.acmicpc.net/problem/11403
15분
모든 정점 (i, j)에 대해서, i에서 j로 가는 길이가 양수인 경로가 있는지 없는지 구한다.
플로이드 워셜 알고리즘 사용하여 모든 노드 -> 모든 노드 비교하였다.
graph[i][j] = 1 인 경우는 경유 노드인 k를 거쳐가는 경우가 있을 때를 1로 설정하였다.
=> [20240222] BAJ / 실버1 / 경로 찾기 / 신예진

Curry4182/202402/23 1학년.md
https://www.acmicpc.net/problem/5557
30분
맨 마지막 수로 등호를 만들 때  만들 수 있는 올바른 등식의 개수를 출력한다. 
첫 자리 수 부터 연산하여 저장하고 주어진 N자리에 대하여 처리한다.
이제 자리수에 대한 dp에 대해 어느 정도 익숙해진거 같다.
=> [20240223] BAJ / 골드5 / 1 학년 / 강병곤

BeommoKoo-dev/202402/23 BAJ 1263 시간 관리.md
https://www.acmicpc.net/problem/1263
30분
해야 할 일을 마치는데 걸리는 시간과, 해당 일이 끝마쳐져야 하는 시간이 주어졌을 때
일을 처음으로 시작하는 시간의 최댓값(가장 늦은 시간)을 구하시오.
그리디한 접근법을 떠올렸다.
1. 일찍 끝나는 순으로 오름차순 정렬
2. 늦게 끝나는 순으로 내림차순 정렬
을 생각했고, 1번은 구해야 하는 답인 '처음으로 시작하는 시간'을 처음부터 정해야 하기 때문에
2번으로 선택했고, 일이 끝마쳐져야 하는 시간 - 걸리는 시간을 방문 처리하고 다음 순번으로 넘어가서
일이 끝마쳐져야 하는 시간이 방문처리 돼있으면 방문처리가 안돼있는 지점까지 옮겨주었다.
=> [20240223] BAJ/골드5/시간 관리/구범모

HandamdeCloud/202402/22 PRG 배달.md, HandamdeCloud/202402/23 PRG 전력망을 둘로 나누기.md
https://school.programmers.co.kr/learn/courses/30/lessons/12978
20 분
최소거리
플로이드 와샬
플로이드 와샬 풀이임을 알고나서는 문제 풀이가 굉장히 쉬웠다.
=> [20240223] PRG / LV2 / 전력망을 둘로 나누기 / 조재현

born-A/202402/23 BAJ A와 B.md
https://www.acmicpc.net/problem/12904
35분
두 문자열 S와 T가 주어졌을 때, S를 T로 바꾸는 게임이다. 
문자열을 바꿀 때는 다음과 같은 두 가지 연산만 가능하다.
- 문자열의 뒤에 A를 추가한다.
- 문자열을 뒤집고 뒤에 B를 추가한다.
주어진 조건을 이용해서 S를 T로 만들 수 있는지 없는지 알아내는 프로그램을 작성한다.
S의 길이보다 T의 길이가 클때 문자열의 마지막이 A 이면 A를 제거하고 B일때는 B를 제거 후 뒤집으면 된다.
StringBuilder를 활용하여 문자열을 조합하는 방법이 익숙하지 않아 생각보다 시간이 더 걸렸다.
=> [20240223] BAJ / 골드5 / A와 B / 신예진

Yiseull/202402/26 PRG 디스크 컨트롤러.md
https://school.programmers.co.kr/learn/courses/30/lessons/42627
20분
하드디스크는 한 번에 하나의 작업만 수행할 수 있습니다. 각 작업에 대해 [작업이 요청되는 시점, 작업의 소요시간]을 담은 2차원 배열 jobs가 매개변수로 주어질 때, 작업의 요청부터 종료까지 걸린 시간의 평균을 가장 줄이는 방법으로 처리하면 평균이 얼마가 되는지 return 하도록 solution 함수를 작성해주세요. (단, 소수점 이하의 수는 버립니다)
> 이 문제는 이전에 풀었던 문제이다. 풀이 방법은 같고 구현 방법이 조금 다르다.
1. 작업들을 요청되는 시점 순으로 정렬한다.
2. 작업이 현재 수횅할 수 있지만 현재 수행 중인 작업이 있는 경우에 우선순위 큐에 (작업의 소요시간, 작업이 요청되는 시점)으로 넣어논다. 3. 그러면 작업의 소요시간이 짧은 순이 가장 높은 우선순위가 된다.
4. 만약 현재 수행하고 있는 작업이 없다면 우선순위 큐에서 작업 소요시간이 가장 짧은 작업을 꺼내서 수행한다.
```
def solution(jobs: list) -> int:
jobs.sort(key=lambda x: (x[0], x[1]))
answer = jobs[0][1]
now = jobs[0][0] + jobs[0][1]
i = 1
heap = []
while i < len(jobs):
if jobs[i][0] <= now:
heappush(heap, (jobs[i][1], jobs[i][0]))
i += 1
continue
while heap and jobs[i][0] > now: …
```
=> [20240226] PRG / lv3 / 디스크 컨트롤러 / 박이슬

born-A/202402/26 BAJ 달팽이.md
https://www.acmicpc.net/problem/1913
40분
n이 주어졌을 때, 달팽이 모양으로 숫자가 배열되는 표를 작성한다.
방향이 총 3번 바뀌게 되고, 한 싸이클이 지날때마다 사각형의 크기가 n-2씩 줄어드는 것을 고려해서 푼다.
달팽이 문제는 처음 풀어봐서 처음 풀땐 감이 안잡혔다. 다른 문제도 풀어봐야겠다.
=> [20240226] BAJ / 실버3 / 달팽이 / 신예진

HandamdeCloud/202402/26 PRG 셔틀버스.md
70 분
무지가 탈 수 있는 가장 늦은 셔틀 찾기
조건을 고려해야 한다. 마지막 셔틀 시간, 그리고 인원수를 고려해 적절하게 탑승하는 테스트케이스를 먼저 이해하고 구현에 들어가야 한다.
문제 이해를 완벽히하고 구현에 들어가니 한결 풀이과정을 떠올리기 쉬웠다. 테스트케이스를 모두 통과했지만, 한번 문제를 겪기도 했다. 수도코드를 작성하는 과정에서 검증이 정상적으로 마무리되지. 않으면 억지로 끼워맞추려고 코드를 짜지만 않으면 괜찮을 것 같다.
=> [20240226] PRG / LV3 / 셔틀 버스 / 조재현

Curry4182/202402/27. 괄호 변환.md
https://school.programmers.co.kr/learn/courses/30/lessons/60058
30 분
-조건에 맞게 재귀적으로 괄호를 변환하는 문제 
- 주어진 조건을 맞춰 괄호를 변환한다.
- 문자열을 만드는 과정에서 StringBuilder를 사용하였다. 
- 괄호가 옳바른지 확인하기 위해 스택을 사용하여 확인함 
- StringBuilder에는 replace가 없다면 문자를 변경하기 위해서는 setCharAt(idx, char)를 사용하였다. 
- 문자열을 재귀적으로 변경하는데 어렵지는 않았다. 다만 스택과 StringBuilder를 사용하면서 바로 생각나지 않는 메서드들이 있었다.
=> [20240227] PRG / lv2 / 괄호 변환 / 강병곤

HandamdeCloud/202402/27 PRG 표 편집.md
130 분
for문, 인덱스, replace등으 ㅣ키워드로 가설을 세우고 풀었지만, 생각해 낸 반례에서 전혀 통과할 수 없었다.
계획을ㅇ 세우고 풀이한 부분은 좋았지만,, 로직이 복잡해진다면 객기부리지 말고 포기하자
=> [20240227] PRG / LV3 / 표 편집 / 조재현

BeommoKoo-dev/202402/27 BAJ 1245 농장 관리.md, BeommoKoo-dev/202402/28 1051 가장 큰 정사각형.md
https://www.acmicpc.net/problem/1245
60분
인접하고(x, y좌표 둘다 거리차이가 1 이하인), 높이가 같은 좌표의 집합을 산봉우리라 한다.
산봉우리와 인접한 다른 산들은 산봉우리보다 높다고 할 때, 산봉우리의 개수를 구하시오.
일단 인접하고, 높이가 같은 좌표의 집합인 산봉우리를 찾기 위해 bfs를 돌려준다.
이때, bfs내부에서 Queue에는 높이가 같은 좌표들만 집어넣어 주고, 방문처리를 한다. 또한 bfs탐색중 인접한 좌표중에서 자신의 높이보다 높은 산을 발견할 경우, flag를 false로 바꿔주고 해당 집합은 산봉우리가 아닌 것이다.
문제 자체의 독해를 완전히 잘못했었다. 코테에서 만났으면 맞왜틀하면서 많이 힘들었을 것 같다ㅠ
=> [20240227] BAJ/골드5/농장 관리/구범모

born-A/202402/27 BAJ 파일 정리.md
https://www.acmicpc.net/problem/20291
30분
파일을 확장자 별로 정리해서 몇 개씩 있는지 확장자들을 사전 순으로 정렬하는 문제.
문자열을 . 으로 구분하여 입력을 받아 HashMap에 저장한다.
확장자는 순서대로 출력해야 하므로 ArrayList에 저장한다.
=> [20240227] BAJ / 실버3 / 파일 정리 / 신예진

Yiseull/202402/27 PRG 호텔 방 배정.md
https://school.programmers.co.kr/learn/courses/30/lessons/64063
60분 이상
처음에는 모든 방이 비어 있으며 "스카피"는 다음과 같은 규칙에 따라 고객에게 방을 배정하려고 합니다.
- 한 번에 한 명씩 신청한 순서대로 방을 배정합니다.
- 고객은 투숙하기 원하는 방 번호를 제출합니다.
- 고객이 원하는 방이 비어 있다면 즉시 배정합니다.
- 고객이 원하는 방이 이미 배정되어 있으면 원하는 방보다 번호가 크면서 비어있는 방 중 가장 번호가 작은 방을 배정합니다.
전체 방 개수 k와 고객들이 원하는 방 번호가 순서대로 들어있는 배열 room_number가 매개변수로 주어질 때, 각 고객에게 배정되는 방 번호를 순서대로 배열에 담아 return 하도록 solution 함수를 완성해주세요.
=> [20240227] PRG / lv4 / 호텔 방 배정 / 박이슬

Curry4182/202402/28 나머지가 1이 되는 수 찾기.md
https://school.programmers.co.kr/learn/courses/30/lessons/87389
10분
n이 주어 졌을 때 n을 나눴을 때 1이되는 가장 작은 수 출력
반복문을 통해 1이 되는 가장 작은수를 1부터 탐색한다.
=> [20240228] PRG / lv1 / 나머지가 1이 되는 수 찾기 / 강병곤

HandamdeCloud/202402/28 PRG 다단계 칫솔 판매.md
80 분
관계 표현, 인덱싱, defaultdict로 요구사항을 파악해서 반영해야 한다.
특히 같은 사람에 대한 중복 수입이 발생할 수 있음을 유의해야 한다.
관계성을 파악함에 있어 공정관념으로 들어가면 안될 것 같다. 재귀로도 해결할 수 있고 리스트로도 해결할 수 있는데 풀이 계획 단계에서 많은것들을 계산을 하고 들어가야만 해결이 가능하다.
=> [20240228] PRG / LV3 / 다단계 칫솔 판매 / 조재현

BeommoKoo-dev/202402/28 1743 음식물 피하기.md
https://www.acmicpc.net/problem/1743
10분
맵에 떨어진 음식물 중 가장 크기가 큰 음식물의 크기를 구하시오. 이때, 음식물끼리 인접하면 하나의 음식물로 본다.
단순 bfs를 돌려서 가장 큰 음식물의 크기를 찾아준다.
어제 PR 안닫고 커밋을 해서, 그냥 한문제 더 풀어서 PR올렸다.
=> [20240228] BAJ/실버1/음식물 피하기/구범모

BeommoKoo-dev/202402/29 BAJ 1189 컴백홈.md
https://www.acmicpc.net/problem/1189
10분
R x C 맵에 못가는 부분이 주어지고 거리 K가 주어지면 한수가 집까지 도착하는 경우 중 거리가 K인 가짓수를 구하라.
dfs를 통하여 총 k번 이동했을 때 도착점에 도착하게 되면 답을 늘려주었다.
시작점 방문처리 안해서 한번 틀렸다. 잘하자..
=> [20240229] BAJ/실버1/컴백홈/구범모

BeommoKoo-dev/202403/01 BAJ 1181 단어 정렬.md
https://www.acmicpc.net/problem/1181
5분
알파벳 소문자로 이루어진 N개의 단어가 들어오면 아래와 같은 조건에 따라 정렬하는 프로그램을 작성하시오.
1. 길이가 짧은 것부터
2. 길이가 같으면 사전 순으로
단, 중복된 단어는 하나만 남기고 제거해야 한다.
set을 이용하여 입력받은 string을 중복제거한 이후, Comparator를 이용하여 문제에서 주어진 조건대로 정렬.
=> [20240301] BAJ/실버5/단어 정렬/구범모

HandamdeCloud/202402/29 PRG 다단계 칫솔 판매.md
30 분
이전 풀이와 동일
자바를 활용해서 풀었다. 자바를 활용하는 연습이 그동안 부족했어서 잊어버린 풀이 등을 복구하기 위해서 사용함
=> [20240229] PRG / LV3 / 다단계 칫솔 판매 / 조재현

Yiseull/202402/28 PRG 야근 지수.md
https://school.programmers.co.kr/learn/courses/30/lessons/12927
15분
회사원 Demi는 가끔은 야근을 하는데요, 야근을 하면 야근 피로도가 쌓입니다. 야근 피로도는 야근을 시작한 시점에서 남은 일의 작업량을 제곱하여 더한 값입니다. Demi는 N시간 동안 야근 피로도를 최소화하도록 일할 겁니다.Demi가 1시간 동안 작업량 1만큼을 처리할 수 있다고 할 때, 퇴근까지 남은 N 시간과 각 일에 대한 작업량 works에 대해 야근 피로도를 최소화한 값을 리턴하는 함수 solution을 완성해주세요.
👉 남아있는 작업 중에 가장 큰 작업들부터 해야지 야근 피로도가 최소가 된다.
1. works를 최대 힙으로 만든다.
2. 힙에서 가장 큰 값을 pop해서 -1한 후, 다시 넣기를 n번 반복한다. -> O(nlogn)
3. 남은 작업량을 제곱해서 더한다.
레벨3이지만 체감상 레벨2처럼 느껴졌다. 문제를 읽으면서 그리디하게 가장 큰 작업들부터 해야겠다는 생각을 했고, 그걸 어떻게 구현해야 생각했을 때 바로 최대 힙이 떠올랐다. 힙은 삽입, 삭제가 O(logn)이여서 시간초과가 안났지만 만약에 힙이 아닌 O(n)이 걸리는 다른 자료구조를 떠올렸다면 시간초과가 났을 것이다.
=> [20240228] PRG / lv3 / 야근 지수 / 박이슬

born-A/202402/29 BAJ 센서.md
https://www.acmicpc.net/problem/2212
45분
N개의 센서가 있고 K개의 집중국이 있는데, K개의 집중국을 이용하여 수신 가능 영역의 길이의 합을 구하는 문제.
N개의 센서와 K개의 집중국이 있으면 N-K개만큼의 간격을 포함한다.
=> [20240229] BAJ / 골드5 / 센서 / 신예진

Curry4182/202403/4 행렬 테두리 회전하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/77485
60분
주어진 쿼리에 해당하는 행렬에 시계 방향으로 옮기는 연산을 한다.
이 때 이동된 원소중 가장 작은 값의 원소를 반환한다.
원소를 큐에 저장하고 다음 칸에 저장한 순서대로 출력하여 시계방향으로 이동한다.
이 후 가장 작은 값을 반환하고 그 값을 저장하여 정답으로 answer로 반환한다.
2차원 자표에서 이동하고 교환하는 것 자체에 대한 연습이 필요한 것 같다.
=> [20240304] PRG / lv2 / 행렬 테두리 회전하기 / 강병곤

Yiseull/202403/04 PRG 최고의 집합.md, Yiseull/202403/05 PRG 숫자 게임.md
https://school.programmers.co.kr/learn/courses/30/lessons/12938
20분
자연수 n 개로 이루어진 중복 집합(multi set, 편의상 이후에는 "집합"으로 통칭) 중에 다음 두 조건을 만족하는 집합을 최고의 집합이라고 합니다.
1. 각 원소의 합이 S가 되는 수의 집합
2. 위 조건을 만족하면서 각 원소의 곱 이 최대가 되는 집합
집합의 원소의 개수 n과 모든 원소들의 합 s가 매개변수로 주어질 때, 최고의 집합을 return 하는 solution 함수를 완성해주세요.
- s가 n보다 작을 때는 조건을 무조건 만족할 수 없기 때문에 바로 [-1]를 반환한다.
- 1의 조건을 만족하면서 2번의 조건을 만족하려면 **원소가 최대한 골고루 분포**되어있어야 한다. 그럴려면 s에 대해서 n으로 나눠준 숫자들로 집합을 구성하면 된다. 하지만 홀수 같은 경우에는 딱 나누어 떨어지지 않는다. 이 문제를 해결하기 위해 s에서 n을 나눠준 후 나눈 값을 s에서 빼고 n은 -1을 하여 계속적으로 s와 n을 업데이트 해주며 집합을 구성하면 된다. 
- 예를 들어, n이 3이고 s가 10인 경우, 처음에는 3을 정답 배열에 추가하고 s=7, n=2 로 업데이트 한다. 그 후 똑같이 반복해주면 3을 정답 배열에 추가하고 s=4, n=1로 업데이트 한다. 마지막으로 4를 정답 배열에 추가해주면 우리가 원하는 정답이 나온다.
```python
def solution(n: int, s: int) -> list:
if s < n:
return [-1]
answer = [0] * n
for …
```
=> [20240304] PRG / lv3 / 최고의 집합 / 박이슬

born-A/202403/04 BAJ 셀프 넘버.md
https://www.acmicpc.net/problem/4673
25분
양의 정수 n에 대해서 d(n)을 n과 n의 각 자리수를 더하는 함수라고 정의하자. 예를 들어, d(75) = 75+7+5 = 87이다.
n을 d(n)의 생성자라고 한다. 
생성자가 없는 숫자를 셀프 넘버라고 한다
10000보다 작거나 같은 셀프 넘버를 한 줄에 하나씩 출력하는 프로그램을 작성한다.
d(n) 함수를 만들고, check[i] 가 false이면 d(i) 실행하고, check[i]가 false이면 출력한다.
=> [20240304] BAJ / 실버5 / 셀프 넘버 / 신예진

Curry4182/202403/5 수식 최대화.md
https://school.programmers.co.kr/learn/courses/30/lessons/67257
60분
사칙연산자의 우선순위를 변경했을 때 가장 높은 값을 출력
스택을 이용한 사칙 연산을 한다.
중위표기법에서 후위표기법으로 변경하는게 어려웠고 && 후위표기식을 연산 할 때 자주 하는 실수가 있는데 주의해야겠다는 생각을 함
=> [20240305] PRG / lv2 / 수식 최대화 / 강병곤

HandamdeCloud/202403/04 PRG 가장 먼 노드.md, HandamdeCloud/202403/04 PRG 두 큐 합 같게 만들기.md, HandamdeCloud/202403/04 PRG 양과 늑대.md, HandamdeCloud/202403/05 PRG 퍼즐 조각 채우기.md
https://school.programmers.co.kr/learn/courses/30/lessons/92343?language=python3
40, 20분, 30분
큐의 합 : 1. 시간복잡도 고려 풀이
양과 늑대 : 2. dfs
가장 먼 노드 : 3.  bfs
1. 시간 복잡도를 고려함에 있어 sum의 시간 복잡도도 고려해야 한다.
2. dfs의 동작 과정을 명확하게 이해하고 있다면, 풀이가 한층 쉬울 수 있다. 특정 구간에서만 동작이 반복하지 않고 전체의 순서를 고려해야한다는 점에서 수도코드나 시뮬레이션을 더 적절히 해줘야 한다는 생각이 들었다.
3. bfs로 최단거리를 구했다. 특정 지점에서 다음 지점간 거리를 구해야 하기 때문에 level을 올리는 과정에서 bfs, dfs중 bfs를 활용한 풀이가 좋겠다고 판단함
=> [20240305] PRG / LV3 / 두 큐 합 같게 만들기,양과 늑대, 가장 먼 노드, 퍼즐 조각 채우기 / 조재현

Curry4182/202403/06 섬 연결하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/42861
60분
최소 스패닝 트리를 구하는 문제
유니온 파인드와 크루스칼 알고리즘을 사용하여 최소 비용을 계산하였다.
크루스칼 알고리즘으로 문제를 푸는데 아직 익숙하지 않다. 많이 풀어서 연습해야 겠다.
=> [20240306] PRG / lv3 / 섬 연결하기 / 강병곤

HandamdeCloud/202403/06 PRG 거스름돈.md, HandamdeCloud/202403/06 PRG 입굼 심사.md
50, 30분
- [] 중
이분 탐색, dp
정해진 입국 심사대 리스트에 대해서만 이분 탐새 하는 것이 아니라, 시간 단위로 범위를 탐색할 수 도 있다. 최소 시간과 최대 시간을 정해 시간 단위로 이분 탐색을 진행해서 최적의 시간을 찾는 것인데, 처음 볼 때에는 이런 새각을 하기 굉장히 어려워 보이기 때문에, 미리 알고 들어가야할 것 같다.
전형적인 dp 풀이였다. 다만, dp[0]에 대한 처리 생각이 조금 부족했다. 하나의 코인으로 처리가 가능한 경우의 수였지만, 떠올리는데 시간이 오래 걸린듯 하다. 오랜만에풀었지만 바로 알고리즘을 떠올릴 수 있어서 다행이었다.
=> [20240306] PRG / LV3 / 입국 심사,거스름돈 / 조재현

HandamdeCloud/202403/07 PRG 가장 긴 펠린드롬.md, HandamdeCloud/202403/07 PRG 길 찾기 게임.md
https://school.programmers.co.kr/learn/courses/30/lessons/12904
1시간, 30분
- [] 중
1. 객체지향적인 풀이였다. 정렬 조건, 그리고 노드 객체를 구성해서 풀어야 하기 때문에 다소 어려웠다.
2. 슬라이싱 문제였다. 최대값 개선
1. 절대 풀 수 없는 수준이다 아직은. 조금 더 많이 보고 익히는 방법밖에는 없어보인다.
2. 슬라이싱 문제로 [::-1]과 같은 탐색 정렬에 익숙해져야 한다.
=> [20240307] PRG / LV3 / 길 찾기 게임, 가장 긴 펠린드롬 / 조재현

born-A/202403/07 BAJ 영역 구하기.md
https://www.acmicpc.net/problem/2583
25분
M, N과 K 그리고 K개의 직사각형의 좌표가 주어질 때, 
K개의 직사각형 내부를 제외한 나머지 부분이 몇 개의 분리된 영역으로 나누어지는지, 
그리고 분리된 각 영역의 넓이가 얼마인지를 구하여 이를 출력하는 프로그램을 작성한다.
좌표 내의 값을 1로 채우고, 0일때 dfs를 수행해서 영역의 넓이를 구한다.
=> [20240307] BAJ / 실버1 / 영역 구하기 / 신예진

Curry4182/202403/07 배달.md
https://school.programmers.co.kr/learn/courses/30/lessons/12978
60분
주어진 시작점에서 어떤 경로를 가기 위해 드는 최소 비용을 구하는 문제
다익스트라 알고리즘을 사용하여 문제를 해결하였다.
어떤 경로를 가기 위한 최소 비용 문제 인데 다익스트라를 왜 사용해야 하는지, 또 다른 알고리즘이 없는지 좀 더 공부해봐야 겠다.
=> [20240307] PRG / lv2 / 배달 / 강병곤

Yiseull/202403/08 PRG 징검다리 건너기.md
https://school.programmers.co.kr/learn/courses/30/lessons/64062
120분
카카오 초등학교의 "니니즈 친구들"이 "라이언" 선생님과 함께 가을 소풍을 가는 중에 징검다리가 있는 개울을 만나서 건너편으로 건너려고 합니다. "라이언" 선생님은 "니니즈 친구들"이 무사히 징검다리를 건널 수 있도록 다음과 같이 규칙을 만들었습니다.
1. 징검다리는 일렬로 놓여 있고 각 징검다리의 디딤돌에는 모두 숫자가 적혀 있으며 디딤돌의 숫자는 한 번 밟을 때마다 1씩 줄어듭니다.
2. 디딤돌의 숫자가 0이 되면 더 이상 밟을 수 없으며 이때는 그 다음 디딤돌로 한번에 여러 칸을 건너 뛸 수 있습니다.
3. 단, 다음으로 밟을 수 있는 디딤돌이 여러 개인 경우 무조건 가장 가까운 디딤돌로만 건너뛸 수 있습니다.
"니니즈 친구들"은 개울의 왼쪽에 있으며, 개울의 오른쪽 건너편에 도착해야 징검다리를 건넌 것으로 인정합니다.
"니니즈 친구들"은 한 번에 한 명씩 징검다리를 건너야 하며, 한 친구가 징검다리를 모두 건넌 후에 그 다음 친구가 건너기 시작합니다.
디딤돌에 적힌 숫자가 순서대로 담긴 배열 stones와 한 번에 건너뛸 수 있는 디딤돌의 최대 칸수 k가 매개변수로 주어질 때, 최대 몇 명까지 징검다리를 건널 수 있는지 return 하도록 solution 함수를 완성해주세요.
💡 이분탐색을 이용하면 O(nlogn)으로 문제를 풀 수 있다.
- left, right의 값은 디딤돌이 가질 수 있는 값의 최소, 최대 값이다.
- mid를 징검다리를 건너는 니니즈 친구들의 수라고 …
=> [20240308] PRG / lv3 / 징검다리 건너기 / 박이슬

BeommoKoo-dev/202403/08 1953 팀배분.md
https://www.acmicpc.net/problem/1953
20분
사람들이 각각 싫어하는 사람들의 정보가 주어져 있을 때, 그 사람들의 요구를 수용하여 서로 싫어하는 사람은 같은 팀에 넣지 않으려 한다. 이 조건을 만족하여 n명의 사람들 두 팀으로 나누는 프로그램을 작성하여라.
싫어하는 사람들끼리는 다른 팀이 되도록 이분 그래프를 만들어 준다.
다만 싫어하는 사람이 없는 경우에는 청팀에 넣어주었고, 한팀에 모든인원이 쏠렸을 때는 한명을 빼서 다른팀에 넣어주었다.
문제해석을 잘못해서 싫어하는 사람이 없는 경우를 고려하지 않았었다. 한국말 어렵다..
=> [20240308] BAJ/골드4/팀배분/구범모

born-A/202403/08 BAJ 단지번호붙이기.md
https://www.acmicpc.net/problem/2667
20분
지도를 입력하여 단지수를 출력하고, 각 단지에 속하는 집의 수를 오름차순으로 정렬하여 출력하는 프로그램을 작성한다.
1일때 dfs를 수행하고 count의 경우 ArrayList에 추가한 후 초기화한다.
=> [20240308] BAJ / 실버1 / 단지번호붙이기 / 신예진

HandamdeCloud/202403/08 PRG 경주로 건설.md
https://school.programmers.co.kr/learn/courses/30/lessons/67259
40 분
벽을 피하는 최소 거리
cost, direction을 활용해 풀이함, 풀이 계획중 cost를 떠올리기가 가장 어려웠음
연구소와 비슷한 문제라고 생각해서 애를 먹음. bfs이지만 경우의 수를 어떻게 떠올려 줘야할 지가 가장 어려웠다. 나머지 풀이 계획은 생각대로였음
해결 : cost의최소값을 갱신, 어떤 경우의수를 찾기보다 가장 최소값만 구하면 되는 문제다. 
과정보다 결과가 중요하다면 cost를 갱신해 나가면 앞에 고민을 해결할 수 있었다.
=> [20240308] PRG / LV3 / 경주로 건설 / 조재현

born-A/202403/11 PRG 네트워크.md, born-A/202403/11 PRG 타겟 넘버.md
https://school.programmers.co.kr/learn/courses/30/lessons/43165
https://school.programmers.co.kr/learn/courses/30/lessons/43162
45분
20분
타겟넘버 : 순서를 바꾸지 않고 적절히 더하거나 빼서 타겟 넘버를 만드는 횟수
네트워크 : 연결된 네트워크의 개수
타겟넘버 : dfs에 해당 배열과 idx, sum을 넣어서 target과 비교한다.
네트워크 : dfs에서 방문여부, 연결여부를 파악하여 재귀를 한다.
전형적인 풀이 코드 틀로만 풀려하니 오히려 시간이 오래걸렸다.
dfs -> 재귀 방식으로 풀이만 기억하자.
=> [20240311] PRG / lv2 / 타겟넘버 / 신예진

Curry4182/202403/09 가장 먼 노드.md
https://school.programmers.co.kr/learn/courses/30/lessons/49189
60분
주어진 문제에서 가장 먼 노드를 탐색하는 문제
인접 배열을 통해 가장 먼 노드를 탐색한다.
다양한 방식으로 탐색하는 방법을 익힐 수 있었다.
=> [20240311] PRG / lv3 / 가장 먼 노드 / 강병곤

HandamdeCloud/202403/11 PRG 호텔 방 배정.md, HandamdeCloud/202403/12 BAJ 21608 상어 초등학교.md
50 분
재귀
자바로 풀이하면서, 시간복잡도를 고려한 풀이를 많이 생각했다. hasmap을 기준으로 생각하게 되면서, 문제 해결이 한충 쉬웠음
=> [20240312] BAJ / 골드5 / 상어 초등학교 / 조재현

BeommoKoo-dev/202403/12 11562 백양로 브레이크.md
https://www.acmicpc.net/problem/11562
30분
서울 소재 Y모 대학교에서 대규모 공사를 진행하면서, 학교가 마치 미로처럼 변해버리고 말았다. 공사 이전까지는 어떤 건물에서 출발하더라도 다른 모든 건물로 갈 수 있는 길이 있었으나, 공사가 진행되면서 어떻게 한 건진 알 수 없지만 일방통행만 가능한 길이 많이 늘고 말았다.
남규는 전공을 살려 현재 일방통행인 길들 중 반드시 양방향으로 바꿔야만 하는 길이 몇 개인지 조사해 학교에 건의하기로 마음을 먹었다.
남규는 여러 건물들 사이를 직접 잇는 길들을 모두 조사했고, 그 중 어떤 길들이 일방통행인지, 또는 양방향 통행이 가능한지를 모두 체크했다.
남규의 프로그램은 간단하다. 출발지와 도착지를 입력하면 도착지까지 가기 위해 최소 몇 개의 길을 양방향으로 바꿔야만 하는지를 출력해준다.
n의 크기는 250으로 매우 작고, 몇 개의 길을 양방향으로 바꿔야 하는지를 거리로 생각해 보니 플로이드 워셜이 떠올랐다.
문제에서 양방향 간선이 주어지면 노드간의 거리를 0으로 하고, 단방향 간선이 주어지면 간선이 없는 부분의 거리를 1로 두었다.(여기에서 거리 = 양방향으로 바꿔야 하는 길의 갯수이므로.) 이후 플로이드 워셜을 돌리고 test case마다 답을 출력해준다.
몇개의 간선을 양방향으로 바꾸어야 하는지 = 거리를 떠올려야 풀 수있는 문제였다. 단순 거리를 구하는 플로이드 워셜보다 좋은 문제라고 생각한다.
=> [20240312] BAJ/골드3/백양로 브레이크/구범모

born-A/202403/12 PRG N으로 표현.md
https://school.programmers.co.kr/learn/courses/30/lessons/42895
60분
자 N과 number가 주어질 때, N과 사칙연산만 사용해서 표현 할 수 있는 방법 중 N 사용횟수의 최솟값을 return.
N을 사용하는 횟수에 초점을 맞춰 사용할 수 있는 횟수 8개의 박스를 만든다.
점화식은 dp[i] = dp[i-j] + dp[j] 이다.
앞뒤로 순서가 바뀔수도 있음을 유의해서 풀어야 한다.
dp 로 풀어야 하는것은 알았지만 로직이 떠오르지 않아 풀이를 참고했다.
한번 더 풀어봐야겠다.
=> [20240312] PRG / lv3 / N으로 표현 / 신예진

Yiseull/202403/12 PRG 거스름돈.md, Yiseull/202403/13 PRG 부대복귀.md
https://school.programmers.co.kr/learn/courses/30/lessons/12907
45분
거슬러 줘야 하는 금액 n과 Finn이 현재 보유하고 있는 돈의 종류 money가 매개변수로 주어질 때, Finn이 n 원을 거슬러 줄 방법의 수를 return 하도록 solution 함수를 완성해 주세요.
```python
def solution(n: int, money: list) -> int:
dp = [0] * (n + 1)
dp[0] = 1
for m in money:
for i in range(m, n + 1):
dp[i] += dp[i - m]
return dp[n] % 1000000007
```
- 보유하고 있는 돈마다 for문을 돌며 dp를 업데이트 해준다.
- dp[i] += dp[i - m]
- 이때 dp[0]은 1개의 돈으로 거슬러 줄 수 있는 경우를 위해 항상 1이다.
되게 쉬운 DP 문제라고 생각했으나 생각보다 되게 어려웠다. 처음에는 O(n)안에 해결하려고 했지만 중복 값을 제거하는 것이 어려웠고, 결국 해설을 보고 풀었다. 해설을 보고 O(nm) 안에 해결을 하였다.
평소에 가장 적은 개수의 돈을 가지고 거슬러주기 등과 같이 dp 값을 매번 전 값과 비교하여 푸는 유형의 문제들을 많이 봤었는데 이렇게 경우의 수를 구하는 문제는 오랜만에 본 것 같다. 덕분에 오랜만에 경험하면서 풀이를 다시 복기시켰다. 다음에 비슷한 유형을 만나면 금방 풀 수 있을 것 같다.
=> [20240312] PRG / lv3 / 거스름돈 / 박이슬

BeommoKoo-dev/202403/13 2751 수 정렬하기 2.md
https://www.acmicpc.net/problem/2751
5분
입력으로 주어지는 수를 정렬하여 출력
Arrays.sort를 이용하여 간단하게 정렬한다.
=> [20240313] BAJ/실버5/수 정렬하기 2/구범모

born-A/202403/13. PRG 정수 삼각형.md
https://school.programmers.co.kr/learn/courses/30/lessons/43105
45분
삼각형의 꼭대기에서 바닥까지 이어지는 경로 중, 거쳐간 숫자의 합이 가장 큰 경우를 찾아보려고 한다. 
아래 칸으로 이동할 때는 대각선 방향으로 한 칸 오른쪽 또는 왼쪽으로만 이동 가능하다.
처음과 끝의 경우는 이전 dp 값과 현재 값을 더하면 된다.
중간 값의 경우에 이전 dp 값들의 최대값과 현재 값을 더한다.
dp문제 임은 알았지만, 최대 합을 보장하나에 확신을 얻지 못해서 시간 소요를 많이 했다.
문제 분석을 제대로 해야겠다는 생각이 들었다..
=> [20240313] PRG / lv3 / 정수 삼각형 / 신예진

Curry4182/202403/13 여행경로.md
https://school.programmers.co.kr/learn/courses/30/lessons/43164
60분
ICN으로 시작해서 모든 공항을 도는 경로들 중 순서가 알파벳 순으로 가장 빠른 것을 출력하는 문제
DFS를 활용하여 경로가 변경될 때 마다 지난 경로를 업데이트 한다.
지난 경로 중간에 변경되어야 하는 경로가 있다면 재귀호출로 푸는게 구현 하기가 더 쉬워서 그렇게 하는게 바람직하다고 생각함
=> [20240313] PRG / lv3 / 여행경로 / 강병곤

Yiseull/202403/14 BAJ 특정한 최단 경로.md
https://www.acmicpc.net/problem/1504
60분
방향성이 없는 그래프가 주어진다. 세준이는 1번 정점에서 N번 정점으로 최단 거리로 이동하려고 한다. 또한 세준이는 두 가지 조건을 만족하면서 이동하는 특정한 최단 경로를 구하고 싶은데, 그것은 바로 임의로 주어진 두 정점은 반드시 통과해야 한다는 것이다.
세준이는 한번 이동했던 정점은 물론, 한번 이동했던 간선도 다시 이동할 수 있다. 하지만 반드시 최단 경로로 이동해야 한다는 사실에 주의하라. 1번 정점에서 N번 정점으로 이동할 때, 주어진 두 정점을 반드시 거치면서 최단 경로로 이동하는 프로그램을 작성하시오.
문제에서는 1번 정점에서 N번 정점까지의 최단 거리를 구할 때 반드시 주어진 정점을 통과해서 가야한다고 한다.
👉 이는 가능한 경로가 '1 -> v1 -> v2 -> n' 또는 '1 -> v2 -> v1 -> n' 2가지 중에 있다는 것을 의미한다.
👉 위의 두 가지 경로 중 값이 더 작은 것이 정답이다.
👉 `min(distance[v1] + distance2[v2] + distance3[v2], distance[v2] + distance2[v2] + distance3[v1])`
이때 v1 -> v2와 v2 -> v1는 같기 때문에 한 번만 구하면 된다.
지금까지 다익스트라 문제들은 진짜 기본적인 문제들, 다시 말해 알고리즘 그대로 푸는 문제들만 풀었다. 그래서 약간의 변형된 문제들만 봐도 살짝 어려움을 느끼는 것 같다. 이 문제도 처음에 봤을 때는 BFS 문제 아닌가 싶었다. 하지만 경로마다 가중치가 다른 것을 보아 …
=> [20240314] BAJ / lv3 /  특정한 최단 경로 / 박이슬

HandamdeCloud/202403/13 BAJ 17281 ⚾.md, HandamdeCloud/202403/17 166337 괄호 추가하기.md
https://www.acmicpc.net/problem/17281
70 분 실패
가장 높은 점수를 뽑는 타순
dfs 로 순열을 짜야겠다고는 생각했다.
타순을 짜는 방법이 어려웠다.
빈 리스트를 만들고, 그안에서 타순을 만들고 변경하는 작업, inning별로 달라지는 값을 어떻게 처리해야할 지 어려이 많았는데, 이번 기회엥 많은 dfs를 사용해서  어려운 문제를 해결하는 방법을 찾은 것 같아 많은 학습이 됨
=> [20240314] BAJ / 골드 3 / 괄호 추가하기 / 조재현

BeommoKoo-dev/202403/14 1326 폴짝폴짝.md
https://www.acmicpc.net/problem/1326
10분
개구리가 일렬로 놓여 있는 징검다리 사이를 폴짝폴짝 뛰어다니고 있다. 징검다리에는 숫자가 각각 쓰여 있는데, 이 개구리는 매우 특이한 개구리여서 어떤 징검다리에서 점프를 할 때는 그 징검다리에 쓰여 있는 수의 배수만큼 떨어져 있는 곳으로만 갈 수 있다.
이 개구리는 a번째 징검다리에서 b번째 징검다리까지 가려고 한다. 이 개구리가 a번째 징검다리에서 시작하여 최소 몇 번 점프를 하여 b번째 징검다리까지 갈 수 있는지를 알아보는 프로그램을 작성하시오.
bfs를 이용하여 노드마다 현재 idx, 지난 징검다리 수를 저장한다.
이후 b에 도달하는 노드에 한해서 정답을 최소화 시켜준다.
=> [20240314] BAJ/실버2/폴짝폴짝/구범모

Curry4182/202403/14 테이블 해시 함수.md
https://school.programmers.co.kr/learn/courses/30/lessons/147354?language=java
30분
입력받은 데이터를 활용하여 다음 조건에 만족하는 해쉬 값을 출력
1. 해시 함수는 col, row_begin, row_end을 입력으로 받습니다.
2. 테이블의 튜플을 col번째 컬럼의 값을 기준으로 오름차순 정렬을 하되, 만약 그 값이 동일하면 기본키인 첫 번째 컬럼의 값을 기준으로 내림차순 정렬합니다.
3.정렬된 데이터에서 S_i를 i 번째 행의 튜플에 대해 각 컬럼의 값을 i 로 나눈 나머지들의 합으로 정의합니다.
4. row_begin ≤ i ≤ row_end 인 모든 S_i를 누적하여 bitwise XOR 한 값을 해시 값으로서 반환합니다.
1. col번째 값이 동일한지에 따라 오름차순, 내림차순을 한다.
2. 나머지 연산은 %을 하고 XOR 연산은 ^을 활용해서 문제를 해결한다.
sort방법과 XOR연산자를 몰랐다면 풀 수 없는 문제 기본적인 연산자와 문법은 암기하자
=> [20240314] PRG / lv2 / 테이블 해시 함수 / 강병곤

BeommoKoo-dev/202403/15 1500 최대 곱.md
https://www.acmicpc.net/problem/1500
10분
세준이는 정수 S와 K가 주어졌을 때, 합이 S인 K개의 양의 정수를 찾으려고 한다. 만약 여러개일 경우 그 곱을 가능한 최대로 하려고 한다.
가능한 최대의 곱을 출력한다.
만약 S=10, K=3이면, 3,3,4는 곱이 36으로 최대이다.
(증명은 하지 못했지만) 직관적으로 생각했을 때 수를 고르게 분배해서 곱하는 것이 최대일 것이라고 생각하여,
(s / k + 1)를 s % k번, (s / k)를 k - s % k번 답에 곱해주었다.
=> [20240315] BAJ/실버2/최대 곱/구범모

HandamdeCloud/202403/18 17070 파이프 옮기기1.md
50 분
dp
dp일 수 있겠다는 예상, 그리고 수도코드의 대략적인 작성은 맞았지만, 3차원 리스트로 만들어서 이를 풀어낼 줄은 몰랐다. dp임을 알게되고 그나마 풀이 계획을 어느정도 유사하게 세운 점에서 유의미한 결과를 얻음
=> [20240315] BAJ / 골드 5 / 파이프 옮기기 1 / 조재현

born-A/202403/15 BAJ 토마토.md
https://www.acmicpc.net/problem/7576
40분
창고에 보관되는 토마토들 중에는 잘 익은 것도 있지만, 아직 익지 않은 토마토들도 있을 수 있다. 
보관 후 하루가 지나면, 익은 토마토들의 인접한 곳에 있는 익지 않은 토마토들은 익은 토마토의 영향을 받아 익게 된다. 
하나의 토마토의 인접한 곳은 왼쪽, 오른쪽, 앞, 뒤 네 방향에 있는 토마토를 의미한다. 대각선 방향에 있는 토마토들에게는 영향을 주지 못하며, 토마토가 혼자 저절로 익는 경우는 없다고 가정한다. 
철수는 창고에 보관된 토마토들이 며칠이 지나면 다 익게 되는지, 그 최소 일수를 알고 싶어 한다.
토마토를 창고에 보관하는 격자모양의 상자들의 크기와 익은 토마토들과 익지 않은 토마토들의 정보가 주어졌을 때, 며칠이 지나면 토마토들이 모두 익는지, 그 최소 일수를 구하는 프로그램을 작성한다.
x,y 좌표와 day 값을 가진 토마토 객체를 만들고 큐에 넣어 bfs를 통해 구한다.
토마토가 어떤 경우의수에 익을지 고민하여 코드를 짜보는게 재미있었다. :)
=> [20240315] BAJ / 골드5 / 토마토 / 신예진

Curry4182/202403/15 미로탈출.md
https://school.programmers.co.kr/learn/courses/30/lessons/159993
50분
주어진 조건에서 레버를 당기고 탈출하는 최소 거리를 출력한다.
시작지점에서 레버까지 BFS하고 레버에서 출구 까지 BFS를 한다.
이렇게 두번 BFS한 값을 출력한다.
BFS알고리즘으로 푸는데 좀더 익숙해져야겠다.
=> [20240315] PRG / lv2 / 미로탈출 / 강병곤

BeommoKoo-dev/202403/18 1431 시리얼 번호.md
https://www.acmicpc.net/problem/1431
10분
다솜이는 기타를 많이 가지고 있다. 그리고 각각의 기타는 모두 다른 시리얼 번호를 가지고 있다. 다솜이는 기타를 빨리 찾아서 빨리 사람들에게 연주해주기 위해서 기타를 시리얼 번호 순서대로 정렬하고자 한다.
모든 시리얼 번호는 알파벳 대문자 (A-Z)와 숫자 (0-9)로 이루어져 있다.
시리얼번호 A가 시리얼번호 B의 앞에 오는 경우는 다음과 같다.
A와 B의 길이가 다르면, 짧은 것이 먼저 온다.
만약 서로 길이가 같다면, A의 모든 자리수의 합과 B의 모든 자리수의 합을 비교해서 작은 합을 가지는 것이 먼저온다. (숫자인 것만 더한다)
만약 1,2번 둘 조건으로도 비교할 수 없으면, 사전순으로 비교한다. 숫자가 알파벳보다 사전순으로 작다.
시리얼이 주어졌을 때, 정렬해서 출력하는 프로그램을 작성하시오.
문제의 요구사항에 맞게 Comparable을 구현하는 Mystring을 구현하여 list에 넣고 sort하였다.
=> [20240318] BAJ/실버3/시리얼 번호/구범모

born-A/202403/18 BAJ 퇴사.md
https://www.acmicpc.net/problem/14501
25분
오늘부터 N+1일째 되는 날 퇴사를 하기 위해서, 남은 N일 동안 최대한 많은 상담을 하려고 한다.
상담을 적절히 했을 때, 백준이가 얻을 수 있는 최대 수익을 구하는 프로그램을 작성.
현재 날짜에서 상담 소요 날짜와 수익을 더해 dp에 저장한다.
이후, 중복될 때 최대값을 넣는다.
=> [20240318] BAJ / 실버3  / 퇴사 / 신예진

Yiseull/202403/18 PRG 양궁대회.md
https://school.programmers.co.kr/learn/courses/30/lessons/92342
60분
1. 어피치가 화살 n발을 다 쏜 후에 라이언이 화살 n발을 쏩니다.
2. 점수를 계산합니다.
1. 과녁판은 아래 사진처럼 생겼으며 가장 작은 원의 과녁 점수는 10점이고 가장 큰 원의 바깥쪽은 과녁 점수가 0점입니다.
2. 만약, k(k는 1~10사이의 자연수)점을 어피치가 a발을 맞혔고 라이언이 b발을 맞혔을 경우 더 많은 화살을 k점에 맞힌 선수가 k 점을 가져갑니다. 단, a = b일 경우는 어피치가 k점을 가져갑니다. k점을 여러 발 맞혀도 k점 보다 많은 점수를 가져가는 게 아니고 k점만 가져가는 것을 유의하세요. 또한 a = b = 0 인 경우, 즉, 라이언과 어피치 모두 k점에 단 하나의 화살도 맞히지 못한 경우는 어느 누구도 k점을 가져가지 않습니다.
- 예를 들어, 어피치가 10점을 2발 맞혔고 라이언도 10점을 2발 맞혔을 경우 어피치가 10점을 가져갑니다.
- 다른 예로, 어피치가 10점을 0발 맞혔고 라이언이 10점을 2발 맞혔을 경우 라이언이 10점을 가져갑니다.
3. 모든 과녁 점수에 대하여 각 선수의 최종 점수를 계산합니다.
3. 최종 점수가 더 높은 선수를 우승자로 결정합니다. 단, 최종 점수가 같을 경우 어피치를 우승자로 결정합니다.
현재 상황은 어피치가 화살 n발을 다 쏜 후이고 라이언이 화살을 쏠 차례입니다.
라이언은 어피치를 가장 큰 점수 차이로 이기기 위해서 n발의 화살을 어떤 과녁 점수에 맞혀야 하는지를 구하려고 합니다.
화살의 개수를 담은 자연수 …
=> [20240318] PRG / lv2 /  양궁대회 / 박이슬

Curry4182/202403/18 거리두기 확인하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/81302#fn1
40분
5x5 테이블에 규칙을 위반하는 원소가 있는지 확인하는 문제
bfs로 풀려고 했지만 맨핸튼 거리 2 안에 있는지 확인해야 하므로 bfs로 전체 P를 찾고 맨핸튼 거리에 있는지 확인하였다.
맨핸튼 거리라는 생소한 개념 때문에 bfs를 잘 못 선택하여 꼬였던거 같다. 다음에 문제를 풀기전에 한번 더 생각해보자
=> [20240318] PRG / lv2 / 거리두기 확인하기 / 강병곤

BeommoKoo-dev/202403/19 24445 알고리즘 수업-너비우선탐색2.md
https://www.acmicpc.net/problem/24445
10분
인접한 양방향 간선이 주어졌을 때, 시작정점부터 몇번째 방문되었는지 각 순서를 출력하시오.
bfs로 탐색하여 탐색순서를 저장하였다.
=> [20240319] BAJ/실버2/알고리즘 수업-너비우선탐색2/구범모

HandamdeCloud/202403/18 14890 경사로.md, HandamdeCloud/202403/19 PRG 등굣길.md
https://www.acmicpc.net/problem/14890
50 분
단순 구현
여러가지 조건을 세우고 그에 맞게 구현만 하면 된다.
=> [20240319] PRG / lv3 / 등굣길 / 조재현

born-A/202403/19 BAJ 빙고.md
https://www.acmicpc.net/problem/2578
60분
철수가 빙고판에 쓴 수들과 사회자가 부르는 수의 순서가 주어질 때, 
사회자가 몇 번째 수를 부른 후 철수가 "빙고"를 외치게 되는지를 출력하는 프로그램을 작성.
가로, 세로, 대각선 두방향에서 심판이 부른 숫자의 갯수가 5인지 확인한다.
무턱대고 dfs로 풀려고 풀었는데, 알고보니 단순 구현 문제였다...
특정 유형으로 접근하려 하기보다 문제를 어떻게 풀어야할지에 집중해야겠다.
=> [20240319] BAJ / 실버4 / 빙고 / 신예진

Yiseull/202403/19 PRG 양과 늑대.md
https://school.programmers.co.kr/learn/courses/30/lessons/92343
25분
2진 트리 모양 초원의 각 노드에 늑대와 양이 한 마리씩 놓여 있습니다. 이 초원의 루트 노드에서 출발하여 각 노드를 돌아다니며 양을 모으려 합니다. 각 노드를 방문할 때 마다 해당 노드에 있던 양과 늑대가 당신을 따라오게 됩니다. 이때, 늑대는 양을 잡아먹을 기회를 노리고 있으며, 당신이 모은 양의 수보다 늑대의 수가 같거나 더 많아지면 바로 모든 양을 잡아먹어 버립니다. 당신은 중간에 양이 늑대에게 잡아먹히지 않도록 하면서 최대한 많은 수의 양을 모아서 다시 루트 노드로 돌아오려 합니다.
각 노드에 있는 양 또는 늑대에 대한 정보가 담긴 배열 info, 2진 트리의 각 노드들의 연결 관계를 담은 2차원 배열 edges가 매개변수로 주어질 때, 문제에 제시된 조건에 따라 각 노드를 방문하면서 모을 수 있는 양은 최대 몇 마리인지 return 하도록 solution 함수를 완성해주세요.
1. 노드를 방문하고 노드의 동물을 확인해서 양과 늑대의 갯수를 업데이트 한다. 
2. 만약 늑대의 수가 더 높으면 return 한다.
3. 무조건 양의 수가 더 많은 경우이므로 정답값을 업데이트 한다.
4. 방문할 리스트를 새로운 리스트로 깊은 복사하고 새로운 리스트에 자식 노드를 담는다.
5. 복사한 리스트에 본인 노드를 삭제한다. 
7. 복사한 리스트의 원소들을 하나씩 방문한다.
이 문제는 전에 풀지 못해서 정답을 봤던 문제이다. 이번에 다시 풀 때 풀이가 기억나서 바로 풀 수 있었다. 답을 알고있는 …
=> [20240319] PRG / lv3 /  양과 늑대 / 박이슬

Curry4182/202403/19 가장 큰 정사각형 찾기.md
https://school.programmers.co.kr/learn/courses/30/lessons/12905
40분
가장 큰 정사각형의 길이를 찾는 문제.
i,j 기준으로 i-1, j || i, j-1 || i-1, j-1 을 검사한다.
이 때 0이 없다면 가장 작은 값에 1을 더하는 방식으로 dp로 문제를 푼다.
다이나믹 프로그래밍으로 풀어야 한다는 느낌은 왔지만 바로 풀지 못하고 한참고민 했었다. 
이런 류의 문제를 더 많이 풀어봐야 겠다.
=> [20240319] PRG / lv2 / 가장 큰 정사각형 찾기 / 강병곤

HandamdeCloud/202403/20 PRG 부대복귀.md
50 분
거리간 최단거리를 찾는 방법인데, 전체를 탐ㅁ색할 필요가 없어 다익스트라로 풀어보았다. 
java 연습중인데 기본기를 익히는 것 같아 재밌음
=> [20240320] PRG / lv3 / 부대복귀 / 조재현

born-A/202403/20 BAJ 기적의 매매법.md
https://www.acmicpc.net/problem/20546
50분
준현 - 가능한 주식을 전부 매수, 매도 x
성준 - 3일간 하락 주식 -> 전부 매수, 3일간 상승 주식 -> 전부 매도
14일때 이익률이 높은 사람 출력
성준 : 현재 주식 값에서 i-1, i-2, i-3의 연속된 값의 상승, 하락을 확인하여 매수 / 매도를 한다.
문제 해석을 잘못해서 한참 헤맸다. 구현 문제는 문제 해석부터 제대로 하고 시작해야겠다.
=> [20240320] BAJ / 실버5 / 기적의 매매법 / 신예진

Curry4182/202403/20 약수의 합.md
https://school.programmers.co.kr/learn/courses/30/lessons/12928
30 분
주어진 숫자 n에 대해 약수의 합을 출력하는 문제
for문으로 약수의 합을 더해 출력한다.
처음 조건을 잘 못 보고 10분동안 고민했는데 처음부터 조건을 잘 보는 연습이 필요한 것 같다.
=> [20240320] PRG / lv2 / 약수의 합 / 강병곤

HandamdeCloud/202403/21 BAJ 10988 팰린드롬인지 확인하기.md
5 분
좌우 탐색범위 일치여부 확인
자바 연습을 위한 코테문제풀이
=> [20240321] BAJ / 브론즈 3 / 팰린드롬인지 확인하기 / 조재현

born-A/202403/21 BAJ 별 찍기 - 19.md
https://www.acmicpc.net/problem/10994
30분
문제에 나온대로 별 찍기
4*I-1 이라는 규칙을 찾고 밖에서 부터 그려나가기.
맨윗줄 draw[idx고정][증가]
맨아랫줄 draw[n-idx-1고정][증가]
맨왼쪽 draw[증가][idx고정]
맨오른쪽 draw[증가][n-idx-1고정]
그린후 안쪽으로 한단계씩 들어갈때마다 idx+2 증가시킨다.
구현문제 많이 풀자 !
=> [20240321] BAJ / 실버4 / 별 찍기 - 19 / 신예진

BeommoKoo-dev/202403/21 6603 로또.md
https://www.acmicpc.net/problem/6603
10분
독일 로또는 {1, 2, ..., 49}에서 수 6개를 고른다.
로또 번호를 선택하는데 사용되는 가장 유명한 전략은 49가지 수 중 k(k>6)개의 수를 골라 집합 S를 만든 다음 그 수만 가지고 번호를 선택하는 것이다.
예를 들어, k=8, S={1,2,3,5,8,13,21,34}인 경우 이 집합 S에서 수를 고를 수 있는 경우의 수는 총 28가지이다. ([1,2,3,5,8,13], [1,2,3,5,8,21], [1,2,3,5,8,34], [1,2,3,5,13,21], ..., [3,5,8,13,21,34])
집합 S와 k가 주어졌을 때, 수를 고르는 모든 방법을 구하는 프로그램을 작성하시오.
dfs를 이용하여 kC6 조합을 구현하였다.
=> [20240321] BAJ/실버2/로또/구범모

Yiseull/202403/21 PRG 과제 진행하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/176962
60분
과제를 받은 루는 다음과 같은 순서대로 과제를 하려고 계획을 세웠습니다.
- 과제는 시작하기로 한 시각이 되면 시작합니다.
- 새로운 과제를 시작할 시각이 되었을 때, 기존에 진행 중이던 과제가 있다면 진행 중이던 과제를 멈추고 새로운 과제를 시작합니다.
- 진행중이던 과제를 끝냈을 때, 잠시 멈춘 과제가 있다면, 멈춰둔 과제를 이어서 진행합니다.
- 만약, 과제를 끝낸 시각에 새로 시작해야 되는 과제와 잠시 멈춰둔 과제가 모두 있다면, 새로 시작해야 하는 과제부터 진행합니다.
- 멈춰둔 과제가 여러 개일 경우, 가장 최근에 멈춘 과제부터 시작합니다.
과제 계획을 담은 이차원 문자열 배열 plans가 매개변수로 주어질 때, 과제를 끝낸 순서대로 이름을 배열에 담아 return 하는 solution 함수를 완성해주세요.
- 시작 시간 순으로 정렬한다.
- 시작 시간을 시와 분을 합쳐서 하나의 숫자로 만든다. 만약 이전에 남아있는 과제가 있다면 남은 과제 끝나는 시간과 새로운 과제 시작 시간을 비교해서 남아있는 과제가 더 늦게 끝날 때까지 남아있는 과제를 계속해서 끝낸다.
- 새로운 과제를 시작할 때 과제가 남아있으면 남은 시간을 계산해서 스택에 저장한다.
- 과제를 다 확인한 후 stack에 남아있는 과제들을 차례대로 수행한다.
레벨2인만큼 문제 그대로 구현하면 돼서 다른 구현 문제보단 크게 어렵지는 않았던 것 같다!
=> [20240321] PRG / lv2 /  과제 진행하기 / 박이슬

Curry4182/202403/21 카펫.md
https://school.programmers.co.kr/learn/courses/30/lessons/42842
30 분
주어진 y, b 값에 따라 크기를 각각 배열에 담는 문제 
구현 문제라 조건 대로 대입해서 풀면 됩니다.
주어진 조건을 더 빨리 보고 더 빨리 푸는 연습을 많이 해야겠다고 생각이드네요
=> [20240321] PRG / lv2 / 카펫 / 강병곤

HandamdeCloud/202403/22 PRG 무인도 여행.md
30 분
bfs
단순 bfs 문제이지만, 자바로 풀려니까 여러 문법들에 더 숙련되어야할 필요를 느꼈다. 유형별로 계속 풀어보면서 자바로 활요해서 푸는 방법에 더 익숙해져야할 것 같다.
=> [20240322] PRG / lv2 / 무인도 여행 / 조재현

Yiseull/202403/22 PRG 기둥과 보 설치.md
https://school.programmers.co.kr/learn/courses/30/lessons/60061
60분 이상
빙하가 깨지면서 스노우타운에 떠내려 온 "죠르디"는 인생 2막을 위해 주택 건축사업에 뛰어들기로 결심하였습니다. "죠르디"는 기둥과 보를 이용하여 벽면 구조물을 자동으로 세우는 로봇을 개발할 계획인데, 그에 앞서 로봇의 동작을 시뮬레이션 할 수 있는 프로그램을 만들고 있습니다.
프로그램은 2차원 가상 벽면에 기둥과 보를 이용한 구조물을 설치할 수 있는데, 기둥과 보는 길이가 1인 선분으로 표현되며 다음과 같은 규칙을 가지고 있습니다.
- 기둥은 바닥 위에 있거나 보의 한쪽 끝 부분 위에 있거나, 또는 다른 기둥 위에 있어야 합니다.
- 보는 한쪽 끝 부분이 기둥 위에 있거나, 또는 양쪽 끝 부분이 다른 보와 동시에 연결되어 있어야 합니다.
단, 바닥은 벽면의 맨 아래 지면을 말합니다.
2차원 벽면은 n x n 크기 정사각 격자 형태이며, 각 격자는 1 x 1 크기입니다. 맨 처음 벽면은 비어있는 상태입니다. 기둥과 보는 격자선의 교차점에 걸치지 않고, 격자 칸의 각 변에 정확히 일치하도록 설치할 수 있습니다.
벽면의 크기 n, 기둥과 보를 설치하거나 삭제하는 작업이 순서대로 담긴 2차원 배열 build_frame이 매개변수로 주어질 때, 모든 명령어를 수행한 후 구조물의 상태를 return 하도록 solution 함수를 완성해주세요.
> 지금까지 추가한 기둥과 보는 build_dict라는 딕셔너리에 저장한다.
- 기둥과 보를 추가할 수 있는 조건을 따로 함수 check()를 만들어서 …
=> [20240322] PRG / lv3 /  기둥과 보 설치 / 박이슬

Curry4182/202403/22 리코쳇 로봇.md
https://school.programmers.co.kr/learn/challenges?order=acceptance_desc&levels=2%2C3%2C4&languages=java&page=5
30분
R에서 로봇이 움직일 때 G까지 움직이는 최소거리를 반환 
BFS 방식으로 최소 값을 구한다.
BFS 방식에 대해 이제는 많이 연습한 것 같으니 다른 유형을 풀 필요가 있는 것 같다.
=> [20240322] PRG / lv2 / 리코쳇 로봇 / 강병곤

born-A/202403/22 BAJ 테트리스 게임.md
https://www.acmicpc.net/problem/4920
60분 - 실패
테트리스는 아래와 같은 5가지 조각으로 이루어져 있다.
정수로 이루어진 N×N 표가 주어진다. 테트리스 블록 중 하나를 표에 놓아 블록 아래에 있는 숫자의 합의 최댓값을 구하는 프로그램을 작성하시오.
1. block 배열에 테트리스 5가지 패턴을 저장한다. 
2. 블록 패턴을 시계 방향으로 90도 회전시킨다. 
3. 좌표 (y, x)와 블록 패턴을 사용하여 좌표 (y, x)에서 시작하는 블록 패턴에 포함된 값의 총합을 계산한다.
다른 분의 풀이를 참고해서 풀었다.
주말에 다시 풀어봐야겠다...
=> [20240322] BAJ / 골드4 / 테트리스 게임 / 신예진

born-A/202403/25 BAJ 설탕 배달.md
https://www.acmicpc.net/problem/2839
25분
봉지는 3킬로그램 봉지와 5킬로그램 봉지가 있다.
최대한 적은 봉지를 들고 가려고 한다. 
상근이가 설탕을 정확하게 N킬로그램 배달해야 할 때, 봉지 몇 개를 가져가면 되는지 그 수를 구하는 프로그램을 작성하시오.
n 이 4 또는 7 인 경우
n 이 5의 배수인경우 
n 이 5의 배수 + 1 또는 5의 배수 + 3 인 경우 
n 이 5의 배수 + 2 또는 5의 배수 + 4 인 경우
4가지로 나누어서 구한다.
=> [20240325] BAJ / 실버4 / 설탕 배달 / 신예진

BeommoKoo-dev/202403/25 17244 아맞다우산.md
https://www.acmicpc.net/problem/17244
30분
외출이 잦은 경재 씨는 반복되는 일을 근절하기 위해 꼭 챙겨야 할 물건들을 정리해보았다. 하지만 지갑, 스마트폰, 우산, 차 키, 이어폰, 시계, 보조 배터리 등 종류와 개수가 너무 많았다.
평소 불필요한 움직임을 아주 싫어하는 경재 씨는 이 물건들을 최대한 빠르게 챙겨서 외출하는 이동 경로를 알고 싶었다.
경재 씨는 한 걸음에 상하좌우에 인접한 칸으로만 움직일 수 있다.
경재 씨를 위해 집을 위에서 바라본 모습과 챙겨야 할 물건들의 위치들을 알고 있을 때, 물건을 모두 챙겨서 외출하기까지 최소 몇 걸음이 필요한지 구하는 프로그램을 작성하자.
기본적인 bfs탐색이지만, 각 물건을 챙겼을때의 상태가 중요하다. 
따라서 방문처리를 할 때 해당 좌표에 몇번물건을 챙겼는지 표시하기 위해서 비트마스킹을 이용하여, 해당 물건의 번호 -1만큼을 bit shift를 하여 방문유무를 체크한 이후 queue에 넣어주었고, 내가 지금 갖고있는 물건 상태로 이전에 방문한 적이 있다면 다음 정점을 방문하지 않고 continue처리를 하였다.
비트마스킹 연습을 위한 문제를 풀어보았다.
=> [20240325] BAJ/골드2/아맞다우산/구범모

HandamdeCloud/202403/25 PRG 시소 짝궁.md
https://school.programmers.co.kr/learn/courses/30/lessons/152996
30분
map의 count 방식을 활용함
map은 이렇게 보면 만능인 것 같기도 하다.. 파이썬으로는 복잡하게 풀었을텐데
=> [20240325] PRG / lv2 / 시소 짝궁 / 조재현

Yiseull/202403/25 PRG 더 맵게.md
https://school.programmers.co.kr/learn/courses/30/lessons/42626
10분
매운 것을 좋아하는 Leo는 모든 음식의 스코빌 지수를 K 이상으로 만들고 싶습니다. 모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 Leo는 스코빌 지수가 가장 낮은 두 개의 음식을 아래와 같이 특별한 방법으로 섞어 새로운 음식을 만듭니다.
> 섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)
Leo는 모든 음식의 스코빌 지수가 K 이상이 될 때까지 반복하여 섞습니다.
Leo가 가진 음식의 스코빌 지수를 담은 배열 scoville과 원하는 스코빌 지수 K가 주어질 때, 모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 섞어야 하는 최소 횟수를 return 하도록 solution 함수를 작성해주세요.
전형적인 우선순위 큐 문제이다. 모든 음식의 스코빌 지수가 k 이상이 되기 위해서 2가지 음식을 섞어서 스코빌 지수가 더 높은 음식을 만들 수 있는데 이때 스코빌 지수를 우선순위로 둔다.
- 우선순위가 높은 즉, 스코빌 지수가 낮은 음식 2개를 꺼내서 1개의 음식으로 만든 후 다시 큐에 넣는다.
- 이때 음식 2개를 큐에서 꺼내야 하기 때문에 큐의 길이가 2 이상일 때만 가능하다.
- 반복문을 모두 돌고 난 후, 큐의 가장 높은 우선순위 즉, 스코빌 지수가 가장 낮은 음식만 확인하여 전체 음식의 스코빌 지수가 K이상인지 확인할 수 있다.
```python
while scoville[0] < k and …
```
=> [20240325] PRG / lv2 /  더 맵게 / 박이슬

Yiseull/202403/26 PRG [3차] n진수 게임.md
https://school.programmers.co.kr/learn/courses/30/lessons/17687
35분
숫자를 0부터 시작해서 차례대로 말한다. 첫 번째 사람은 0, 두 번째 사람은 1, … 열 번째 사람은 9를 말한다.
10 이상의 숫자부터는 한 자리씩 끊어서 말한다. 즉 열한 번째 사람은 10의 첫 자리인 1, 열두 번째 사람은 둘째 자리인 0을 말한다.
이렇게 게임을 진행할 경우,
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, …
순으로 숫자를 말하면 된다.
게임에 익숙해져 질려가던 사람들은 좀 더 난이도를 높이기 위해 이진법에서 십육진법까지 모든 진법으로 게임을 진행해보기로 했다. 숫자 게임이 익숙하지 않은 튜브는 게임에 져서 벌칙을 받는 굴욕을 피하기 위해, 자신이 말해야 하는 숫자를 스마트폰에 미리 출력해주는 프로그램을 만들려고 한다. 튜브의 프로그램을 구현하라.
- 튜브의 순서가 p일 때, t번 말하려면 => 사람들의 수 m * (t - 1) + p 만큼의 길이만 필요하다.
- 따라서 while문을 돌면서 0부터 1씩 증가하며 필요한 길이만큼 n진수의 합쳐진 문자열을 구한다.
- 다 구한 후 정답 문자열을 리스트로 바꾼 후 answer[p - 1:m * (t - 1) + p:m]를 문자열로 다시 합치면 튜브가 말해야 하는 숫자들이 나온다.
간단한 문제이지만 정답 출력의 인덱스와 while문을 언제까지 돌건지 약간의 생각해야 하는 포인트가 있었다. 그래도 비교적 쉬운 문제여서 어려움 없이 풀 수 있었다!
=> [20240326] PRG / lv2 / [3차] n진수 게임 / 박이슬

HandamdeCloud/202403/26 PRG 최대값과 최소값.md
10 분
Stream풀이로 타입을 변환하고 활용하면 된다.
배열의 형변환 ,그리고 최대 최소값을 출력하기 위한 Stream활용을경험했다. python에 비해서 최대최소값 찾기가 쉬워보이는데 ,이런부분을 적극적으로 활용해야할 것 같다.
=> [20240326] PRG / lv2 / 최대값과 최소값 / 조재현

Curry4182/202403/26 프로세스.md
https://school.programmers.co.kr/learn/courses/30/lessons/42587
40분
문제에 제시된 형태로 우선순위를 계산해서 출력하시오
두개의 큐를 사용하여 조건에 맞기 출력하였습니다.
큐 관련 자료구조에 대해 복습
=> [20240326] PRG / lv2 / 프로세스 / 강병곤

born-A/202403/26 BAJ 할아버지는 유명해!.md
https://www.acmicpc.net/problem/5766
25분
매주 랭킹에 선수의 이름이 오를 때마다 선수의 포인트가 1포인트씩 오르는데,
매주마다의 랭킹 정보 리스트를 인풋으로 받아 2등 선수가 누구인지 알아내는 프로그램을 작성.
입력으로 들어오는 선수들의 번호를 인덱스로 하는 배열의 수를 +1증가시킨다. 
가장 점수가 높은 선수의 점수를 확인하고 그다음 두번째로 높은 선수의 점수를 확인해 저장해놓는다.
=> [20240326] BAJ / 실버4 / 할아버지는 유명해! / 신예진

BeommoKoo-dev/202403/27 1965 상자넣기.md
https://www.acmicpc.net/problem/1965
10분
정육면체 모양의 상자가 일렬로 늘어서 있다. 상자마다 크기가 주어져 있는데, 앞에 있는 상자의 크기가 뒤에 있는 상자의 크기보다 작으면, 앞에 있는 상자를 뒤에 있는 상자 안에 넣을 수가 있다. 예를 들어 앞에서부터 순서대로 크기가 (1, 5, 2, 3, 7)인 5개의 상자가 있다면, 크기 1인 상자를 크기 5인 상자에 넣고, 다시 이 상자를 크기 7인 상자 안에 넣을 수 있다. 하지만 이렇게 상자를 넣을 수 있는 방법은 여러 가지가 있을 수 있다. 앞의 예에서 차례대로 크기가 1, 2, 3, 7인 상자를 선택하면 총 4개의 상자가 한 개의 상자에 들어가게 된다.
상자의 크기가 주어질 때, 한 번에 넣을 수 있는 최대의 상자 개수를 출력하는 프로그램을 작성하시오.
결국 문제는 LIS를 요구하고 있다.
n이 1000으로 작으므로, O(N^2)로 LIS를 구하였다.
=> [20240327] BAJ/실버2/상자넣기/구범모

born-A/202403/27 BAJ 트리의 부모 찾기.md
https://www.acmicpc.net/problem/11725
40분
루트 없는 트리가 주어진다. 이때, 트리의 루트를 1이라고 정했을 때, 각 노드의 부모를 구하는 프로그램을 작성하시오.
dfs
=> [20240327] BAJ / 실버2 / 트리의 부모 찾기 / 신예진

Yiseull/202403/27 PRG 방문 길이.md
https://school.programmers.co.kr/learn/courses/30/lessons/49994
15분
게임 캐릭터를 4가지 명령어를 통해 움직이려 합니다. 명령어는 다음과 같습니다.
- U: 위쪽으로 한 칸 가기
- D: 아래쪽으로 한 칸 가기
- R: 오른쪽으로 한 칸 가기
- L: 왼쪽으로 한 칸 가기
캐릭터는 좌표평면의 (0, 0) 위치에서 시작합니다. 좌표평면의 경계는 왼쪽 위(-5, 5), 왼쪽 아래(-5, -5), 오른쪽 위(5, 5), 오른쪽 아래(5, -5)로 이루어져 있습니다.
명령어가 매개변수 dirs로 주어질 때, 게임 캐릭터가 처음 걸어본 길의 길이를 구하여 return 하는 solution 함수를 완성해 주세요.
구현 문제로, 문제에 주어진 조건들에 맞춰 구현만 하면 된다😊
- 캐릭터의 이전 위치를 저장한 후, 명령어에 따라 이동을 한다.
- 이동한 위치가 좌표평면 안에 있는지 확인한다.
- 좌표평면 안에 있다면, (현재 위치, 이동한 위치)를 set에 넣는다. 이때 (이동한 위치, 현재 위치)가 이미 set에 존재할 수도 있기 때문에 존재 여부를 확인한 후에 넣어준다.
- 이동한 위치를 현재 위치로 업데이트 한다.
이 문제는 되게 쉬운 문제였다. 약간 헤맸던 것은 이미 가본 길을 셀 때 방향은 고려하면 안된다는 것이다. 나는 처음에 (현재 위치, 이동한 위치)만 고려하고 set에 넣었었는데 그 반대로도 이미 건너갔을 수도 있다는 것을 간과했었다. 그래도 빨리 빠뜨린 조건을 알아채서 금방 풀 수 있었다!
=> [20240327] PRG / lv2 / 방문 길이 / 박이슬

Yiseull/202403/28 PRG 2개 이하로 다른 비트.md
https://school.programmers.co.kr/learn/courses/30/lessons/77885#
15분
양의 정수 x에 대한 함수 f(x)를 다음과 같이 정의합니다.
- x보다 크고 x와 비트가 1~2개 다른 수들 중에서 제일 작은 수
정수들이 담긴 배열 numbers가 매개변수로 주어집니다. numbers의 모든 수들에 대하여 각 수의 f 값을 배열에 차례대로 담아 return 하도록 solution 함수를 완성해주세요.
👉 짝수와 홀수의 계산 방법이 다르다. 짝수는 무조건 이진수의 마지막 숫자가 0이기 때문에 마지막 숫자만 1로 바꿔주면 돼서 기존의 숫자에 +1만 해주면 된다. 문제는 홀수이다.
👉 홀수에서 'x보다 크고 x와 비트가 1~2개 다른 수들 중에서 제일 작은 수'를 구하려면 일단 홀수의 이진수를 살펴봐야 한다. 만약 '1001'라는 홀수가 있을 때 정답은 '1010'이다. 즉 맨 마지막 0이 나오는 인덱스는 1로 바꾸고 그 다음 인덱스는 0으로 바꾸는 것이다. '01' -> '10'으로, '111'같은 숫자들은 앞에 0이 있다고 생각하고 즉, '0111'이라고 생각하고 풀면 된다.
- 홀수인 경우 이진수를 구한다.
- 구한 이진수에서 맨 뒤 쪽에서부터 0이 나오는 인덱스를 찾는다.
- 만약 0인 인덱스가 있다면 해당 인덱스의 숫자를 1로 바꿔주고 그 다음 숫자를 0으로 바꿔준다.
- 0인 인덱스가 없다면 맨 앞의 숫자를 0으로 바꿔주고 맨 앞에 1 숫자를 추가한다.
오늘부터 자바 코테를 준비하기로 해서, 파이썬과 자바로 두 번 문제를 풀었다. 먼저 파이썬으로 푼 다음 그 …
=> [20240328] PRG / lv2 / 2개 이하로 다른 비트 / 박이슬

BeommoKoo-dev/202403/28 3020 개똥벌레.md
https://www.acmicpc.net/problem/3020
50분
개똥벌레 한 마리가 장애물(석순과 종유석)로 가득찬 동굴에 들어갔다. 동굴의 길이는 N미터이고, 높이는 H미터이다. (N은 짝수) 첫 번째 장애물은 항상 석순이고, 그 다음에는 종유석과 석순이 번갈아가면서 등장한다.
이 개똥벌레는 장애물을 피하지 않는다. 자신이 지나갈 구간을 정한 다음 일직선으로 지나가면서 만나는 모든 장애물을 파괴한다.
동굴의 크기와 높이, 모든 장애물의 크기가 주어진다. 이때, 개똥벌레가 파괴해야하는 장애물의 최솟값과 그러한 구간이 총 몇 개 있는지 구하는 프로그램을 작성하시오.
석순, 종유석의 누적합을 구하여, 높이별로 몇개의 장애물이 있는지 count를 구하여 답을 구한다.
=> [20240328] BAJ/골드5/개똥벌레/구범모

born-A/202403/28 BAJ ZOAC 3.md
https://www.acmicpc.net/problem/20436
35분
성우는 한글 자음 쪽 자판은 왼손 검지손가락으로 입력하고, 한글 모음 쪽 자판은 오른손 검지손가락으로 입력한다.
a의 좌표가 (x1, y1)이고, b의 좌표가 (x2, y2)일 때, a에 위치한 성우의 손가락이 b로 이동하는 데에는 a와 b의 택시 거리 |x1-x2|+|y1-y2| 만큼의 시간이 걸린다.
각 키를 누르는 데에는 1의 시간이 걸린다.
성우는 두 손을 동시에 움직일 수 없다.
성우가 사용하는 키보드는 쿼티식 키보드이며, 아래 그림처럼 생겼다.
바쁜 성우를 위하여 해당 문자열을 출력하는 데 걸리는 시간의 최솟값을 구해보자.
map 키값으로 문자가 들어가고 value로는 해당 문자의 위치가 들어간다. 
L과 R이라는 변수를 만들어서 지금 왼손과 오른손의 위치가 어디에 존재하는지 저장해둔다. 
누르는 시간 계산은 입력값으로 들어오는 문자가 왼손인지 오른손인지 파악하고 
위치를 계산하고 해당 키를 입력하는 시간인 +1을 해준다.
=> [20240328] BAJ / 실버4 / ZOAC 3 / 신예진

Curry4182/202403/27 광물캐기.md, Curry4182/202403/28 최고의 집합.md
https://school.programmers.co.kr/learn/courses/30/lessons/12938
50분
다음 조건을 만족하는 집합을 찾는 문제
- 각 원소의 합이 S가 되는 수의 집합
- 위 조건을 만족하면서 각 원소의 곱 이 최대가 되는 집합
문제의 조건대로 나머지 연산 후 nlogn연산으로 정렬한다.
확실히 수학이 들어간 문제에 대해서는 좀 더 공부할 필요가 있는거 같다.
=> [20240328] PRG / lv3 / 최고의 집합 / 강병곤

Yiseull/202403/29 PRG 마법의 엘리베이터.md
https://school.programmers.co.kr/learn/courses/30/lessons/148653?language=python3#
30분
마법의 세계에 사는 민수는 아주 높은 탑에 살고 있습니다. 탑이 너무 높아서 걸어 다니기 힘든 민수는 마법의 엘리베이터를 만들었습니다. 마법의 엘리베이터의 버튼은 특별합니다. 마법의 엘리베이터에는 -1, +1, -10, +10, -100, +100 등과 같이 절댓값이 10c (c ≥ 0 인 정수) 형태인 정수들이 적힌 버튼이 있습니다. 마법의 엘리베이터의 버튼을 누르면 현재 층 수에 버튼에 적혀 있는 값을 더한 층으로 이동하게 됩니다. 단, 엘리베이터가 위치해 있는 층과 버튼의 값을 더한 결과가 0보다 작으면 엘리베이터는 움직이지 않습니다. 민수의 세계에서는 0층이 가장 아래층이며 엘리베이터는 현재 민수가 있는 층에 있습니다.
마법의 엘리베이터를 움직이기 위해서 버튼 한 번당 마법의 돌 한 개를 사용하게 됩니다.예를 들어, 16층에 있는 민수가 0층으로 가려면 -1이 적힌 버튼을 6번, -10이 적힌 버튼을 1번 눌러 마법의 돌 7개를 소모하여 0층으로 갈 수 있습니다. 하지만, +1이 적힌 버튼을 4번, -10이 적힌 버튼 2번을 누르면 마법의 돌 6개를 소모하여 0층으로 갈 수 있습니다.
마법의 돌을 아끼기 위해 민수는 항상 최소한의 버튼을 눌러서 이동하려고 합니다. 민수가 어떤 층에서 엘리베이터를 타고 0층으로 내려가는데 필요한 마법의 돌의 최소 개수를 알고 싶습니다. 민수와 마법의 엘리베이터가 있는 층을 나타내는 정수 storey 가 주어졌을 때, …
=> [20240329] PRG / lv2 / 마법의 엘리베이터 / 박이슬

BeommoKoo-dev/202403/29 1535 안녕.md
https://www.acmicpc.net/problem/1535
10분
세준이는 성형수술을 한 후에 병원에 너무 오래 입원해 있었다. 이제 세준이가 병원에 입원한 동안 자기를 생각해준 사람들에게 감사하다고 말할 차례이다.
세준이를 생각해준 사람은 총 N명이 있다. 사람의 번호는 1번부터 N번까지 있다. 세준이가 i번 사람에게 인사를 하면 L[i]만큼의 체력을 잃고, J[i]만큼의 기쁨을 얻는다. 세준이는 각각의 사람에게 최대 1번만 말할 수 있다.
세준이의 목표는 주어진 체력내에서 최대한의 기쁨을 느끼는 것이다. 세준이의 체력은 100이고, 기쁨은 0이다. 만약 세준이의 체력이 0이나 음수가 되면, 죽어서 아무런 기쁨을 못 느낀 것이 된다. 세준이가 얻을 수 있는 최대 기쁨을 출력하는 프로그램을 작성하시오.
dp[100] = 0으로 기저조건을 설정한 이후, 입력받은 것들을 for문으로 돌면서 해당 체력을 썼을 때 남은 체력이 1 이상이면 최댓값을 갱신하는 식으로 dp를 이용하여 풀이했다.
=> [20240329] BAJ/실버2/안녕/구범모

Curry4182/202403/29 사이클 게임.md
https://www.acmicpc.net/problem/20040
40 분
사이클이 도는 그래프가 있는지 판단하는 문제
유니온 파인드 알고리즘 사용하여 해결
유니온 파인드 정도는 외우고 있어야 겠다고 생각함
=> [20240329] PRG / 실버4 / 사이클 게임 / 강병곤

born-A/202404/01 BAJ 로봇 청소기.md
https://www.acmicpc.net/problem/14503
45분
로봇 청소기가 작동을 시작한 후 작동을 멈출 때까지 청소하는 칸의 개수를 출력한다.
arr [x][y]==0 이면 카운트를 증가시키고 arr [x][y]=-1 해준다. 
새롭게 이동한 위치가 범위 내에 있는지 확인하고 arr [x][y]==0이라면 dfs 재귀함수를 탄다.
=> [20240401] BAJ / 골드5 / 로봇 청소기 / 신예진

Curry4182/202404/01 등굣길.md
90분
집의 좌표와 학교 좌표가 주어졌을 때 물웅덩이를 피해서 갈 수 있는 경로의 수를 1,000,000,007로 나눈 나머지를 반환 하는 문제
dp 알고리즘을 사용하여 경우의 수를 저장하여 풀이한다.
dp 알고리즘은 조금만 변형해도 헷갈리기 때문에 더 많은 연습이 필요한 것 같다.
=> [20240401] PRG / lv3 / 등굣길 / 강병곤

BeommoKoo-dev/202404/01 1949 우수 마을.md
https://www.acmicpc.net/problem/1949
45분
N개의 마을로 이루어진 나라가 있다. 편의상 마을에는 1부터 N까지 번호가 붙어 있다고 하자. 이 나라는 트리(Tree) 구조로 이루어져 있다. 즉 마을과 마을 사이를 직접 잇는 N-1개의 길이 있으며, 각 길은 방향성이 없어서 A번 마을에서 B번 마을로 갈 수 있다면 B번 마을에서 A번 마을로 갈 수 있다. 또, 모든 마을은 연결되어 있다. 두 마을 사이에 직접 잇는 길이 있을 때, 두 마을이 인접해 있다고 한다.
이 나라의 주민들에게 성취감을 높여 주기 위해, 다음 세 가지 조건을 만족하면서 N개의 마을 중 몇 개의 마을을 '우수 마을'로 선정하려고 한다.
'우수 마을'로 선정된 마을 주민 수의 총 합을 최대로 해야 한다.
마을 사이의 충돌을 방지하기 위해서, 만일 두 마을이 인접해 있으면 두 마을을 모두 '우수 마을'로 선정할 수는 없다. 즉 '우수 마을'끼리는 서로 인접해 있을 수 없다.
선정되지 못한 마을에 경각심을 불러일으키기 위해서, '우수 마을'로 선정되지 못한 마을은 적어도 하나의 '우수 마을'과는 인접해 있어야 한다.
각 마을 주민 수와 마을 사이의 길에 대한 정보가 주어졌을 때, 주어진 조건을 만족하도록 '우수 마을'을 선정하는 프로그램을 작성하시오.
dp[cur][flag] : flag = 1일때, cur 노드를 우수마을로 선정했을 때/flag = 0일때, cur노드를 우수마을로 선정하지 않았을 때 최댓값으로 정의한 이후 dfs를 이용하여 flag = 1일때는 인접노드의 flag를 0으로 두고 재귀호출을 한다. …
=> [20240401] BAJ/골드2/우수 마을/구범모

born-A/202404/02 BAJ 분수찾기.md
https://www.acmicpc.net/problem/1193
40분
분수들을 1/1 → 1/2 → 2/1 → 3/1 → 2/2 → … 과 같은 지그재그 순서로 차례대로 1번, 2번, 3번, 4번, 5번, … 분수라고 하자.
X가 주어졌을 때, X번째 분수를 구하는 프로그램을 작성하시오.
T가 홀수일때,분자가 증가하고, 분모가 감소한다.
짝수일때는 이와 반대로 식을 구하면 된다.
=> [20240402] BAJ / 실버5 / 분수찾기 / 신예진

Curry4182/202404/02 N으로 표현.md
https://school.programmers.co.kr/learn/courses/30/lessons/42895
40 분
N, number가 주어졌을 때 N으로 number를 만들 수 있는 경우의 수 출력 
다이나믹 프로그래밍을 이용하여 중간 연산 값을 메모리에 저장
다이나믹 프로그래밍을 좀 더 학습해야할 필요를 느낌
=> [20240402] PRG / lv3 / N으로 표현 / 강병곤

born-A/202404/03 BAJ 단어 맞추기.md
https://www.acmicpc.net/problem/9081
35분
단어를 주면 그 단어를 이루는 알파벳들로 만들 수 있는 단어들을 사전 순으로 정렬할 때에 주어진 단어 다음에 나오는 단어를 찾는 프로그램을 작성한다.
단어 맨뒤 글자에서 부터 봤을 때 오름차순으로 올라가다가 꺾이는 지점의 전 값과 그 이후의 숫자 중 다음 큰 값과 swap. 
그 후, top 이후의 숫자들 모두 오름차순 정렬을 하면 된다.
=> [20240403] BAJ / 실버1 / 단어 맞추기 / 신예진

born-A/202404/04 BAJ 숨바꼭질.md
https://www.acmicpc.net/problem/1697
30분
수빈이는 동생과 숨바꼭질을 하고 있다. 수빈이는 현재 점 N(0 ≤ N ≤ 100,000)에 있고, 동생은 점 K(0 ≤ K ≤ 100,000)에 있다. 
수빈이는 걷거나 순간이동을 할 수 있다. 만약, 수빈이의 위치가 X일 때 걷는다면 1초 후에 X-1 또는 X+1로 이동하게 된다. 순간이동을 하는 경우에는 1초 후에 2*X의 위치로 이동하게 된다.
수빈이와 동생의 위치가 주어졌을 때, 수빈이가 동생을 찾을 수 있는 가장 빠른 시간이 몇 초 후인지 구하는 프로그램을 작성하시오.
bfs 큐를 이용해서 count를 구하면 된다.
=> [20240404] BAJ / 실버1 / 숨바꼭질 / 신예진

Curry4182/202404/04 짝수와 홀수.md
https://school.programmers.co.kr/learn/courses/30/lessons/12937
5분
짝수와 홀 수를 구별하여 출력하는 문제
나머지 연산자를 사용하여 풀이 
오늘은 컨디션이 좋지 않아 간단한 문제를 풀었습니다.
=> [20240404] PRG / lv1 / 짝수와 홀수 / 강병곤

born-A/202404/05 BAJ 파일 합치기.md
https://www.acmicpc.net/problem/11066
45분
소설가인 김대전은 소설을 여러 장(chapter)으로 나누어 쓰는데, 각 장은 각각 다른 파일에 저장하곤 한다. 
소설의 모든 장을 쓰고 나서는 각 장이 쓰여진 파일을 합쳐서 최종적으로 소설의 완성본이 들어있는 한 개의 파일을 만든다. 이 과정에서 두 개의 파일을 합쳐서 하나의 임시파일을 만들고, 이 임시파일이나 원래의 파일을 계속 두 개씩 합쳐서 소설의 여러 장들이 연속이 되도록 파일을 합쳐나가고, 최종적으로는 하나의 파일로 합친다. 
두 개의 파일을 합칠 때 필요한 비용(시간 등)이 두 파일 크기의 합이라고 가정할 때, 최종적인 한 개의 파일을 완성하는데 필요한 비용의 총 합을 계산하시오.
DP[j][i] = Math.min(DP[j][i], DP[j][s] + DP[s+1][i])
DP[j][i] += sum[i] - sum[j-1]
3중 for문을 돌려 위의 dp 공식에 적용하면 된다.
=> [20240405] BAJ / 골드3 / 파일 합치기 / 신예진

born-A/202404/06 BAJ 직사각형 네개의 합집합의 면적 구하기.md
https://www.acmicpc.net/problem/2669
15분
직사각형들이 차지하는 면적을 구하는 프로그램을 작성하시오.
각 칸에 직사각형이 있으면 1을 넣는 식으로 기록한다.
=> [20240408] BAJ / 실버5 / 직사각형 네개의 합집합의 면적 구하기 / 신예진

Curry4182/202404/08 프렌즈 블록.md
https://school.programmers.co.kr/learn/courses/30/lessons/17679
60분
떨어지는 블록을 조건에 맞게 연산하고 그 결과를 반환하는 문제 
구현 문제라서 조건에 따라 그대로 구현합니다.
구현 문제는 조건을 잘 보고 정신 차리고 풀어야 겠다고 다시 생각함
=> [20240408] PRG / lv2 / 프렌즈 블록 / 강병곤

Curry4182/202404/11 자릿수 더하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/12931?language=java
10분
자연수 N이 주어지면, N의 각 자릿수의 합을 구해서 return 하도록 함
while 문을 이용하여 풀이
간단한 문제라 빨리 풀 수 있었습니다.
=> [20240411] PRG / lv 1 / 자릿수 더하기 / 강병곤

born-A/202404/12 BAJ 분수찾기.md
https://www.acmicpc.net/problem/1193
25분
나열된 분수들을 1/1 → 1/2 → 2/1 → 3/1 → 2/2 → … 과 같은 지그재그 순서로 차례대로 1번, 2번, 3번, 4번, 5번, … 분수라고 하자.
X가 주어졌을 때, X번째 분수를 구하는 프로그램을 작성하시오.
=> [20240412] BAJ / 실버5 / 분수찾기 / 신예진

Curry4182/202404/12 줄기세포배양.md
https://swexpertacademy.com/main/code/problem/problemSubmitDetail.do
180 분
문제에서 주어진 조건에 따라 세포를 배야할 때 총 활성화 되어 있는 세포의 수 출력
주어진 조건을 하나도 빠짐없이 생각하며 코드를 작성한다.
조건 하나하나는 어렵지 않지만 모든 조건을 만족하게 만드는게 쉽지 않았다.
=> [20240412] SW Expert Academy / 줄기세포 배양/ 강병곤

Curry4182/202404/13 자연수 뒤집어 배열로 만들기.md
https://school.programmers.co.kr/learn/courses/30/lessons/12932
10분
자연수를 뒤집어 배열로 출력하는 문제 입니다.
자연수 자리수를 구하여 배열의 수를 구한 후 차례 대로 배열에 넣습니다.
이런 문제는 실수 하지 않고 빠르게 풀어야 하는 문제 중 하나라고 생각합니다.
=> [20240413] PRG / lv1 / 자연수 뒤집어 배열로 만들기  / 강병곤

born-A/202404/15 BAJ 설탕 배달.md
https://www.acmicpc.net/problem/2839
15분
상근이는 지금 사탕가게에 설탕을 정확하게 N킬로그램을 배달해야 한다. 
봉지는 3킬로그램 봉지와 5킬로그램 봉지가 있다.
상근이는 최대한 적은 봉지를 들고 가려고 한다.
상근이가 설탕을 정확하게 N킬로그램 배달해야 할 때, 봉지 몇 개를 가져가면 되는지 그 수를 구하는 프로그램을 작성하시오.
5로 나눠서 0인지 확인하고,
5kg로 나눌 수 없다면 3kg을 빼서 남은 무게로 5로 나눌 수 있는지 확인한다.
=> [20240415] BAJ / 실버4 /설탕 배달 / 신예진
