hi-min-study/daliy-algorithm-study

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md
https://www.acmicpc.net/problem/2482
60분
n개의 색 중 k개를 칠하는 방법의 수 찾기.
점화식을 세워 풀 수 있다.
dp[n][k]를 n개의 칸 중 k개의 인접하지 않은 칸을 선택하여 색칠하는 경우의 수라고 하자.
dp[n][1]은 항상 n임이 보장된다.
이후 n개의 칸 중 k개의 인접하지 않은 칸을 선택하여 색칠하는 경우의 수는,
1 : n번째 칸을 색칠하는 경우 : n-1번째, 1번째 칸 둘다 색칠하지 못하므로, n-2개의 칸 중 k-1개의 칸을 색칠하는 경우의 수 : dp[n-2][k-1]
2 : n번째 칸을 색칠하지 않는 경우 : 1~n-1번째 칸을 k개 색칠하는 경우의 수 : dp[n-1][k]
1 + 2의 경우의 수를 더해주면 된다.
점화식 어려워요ㅠ
=> [20231219] BAJ/골드3/색상환/구범모

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md
링크 : https://www.acmicpc.net/problem/7579
50분
필요한 용량(M)을 채우는 데 필요한 최소 비용(C)를 구하는 문제.
처음엔 그리디하게 접근하려 했지만, 문제분류를 확인했는데 냅색 알고리즘이였다.
알고리즘을 확인한 이후에 그리디의 반례를 찾아서, 냅색으로 접근하려 했으나
기존의 냅색 알고리즘으로 접근하려면 용량의 최댓값을 dp배열의 크기로 선언해야 한다.
하지만 이것은 메모리 초과가 날것이므로, 비용을 dp배열의 크기로 선언하여 dp배열에 들어가는 값을
용량으로 잡아주어서 해결하였다.
최적화에서 한번 더 최적화가 일어난 느낌이라, 많이 배워갔던 문제.
=> [20231226] BAJ/골드3/앱/구범모

BeommoKoo-dev/202312/18 BAJ 1987 알파벳.md, BeommoKoo-dev/202312/19 BAJ 2482 색상환.md, BeommoKoo-dev/202312/20 BAJ 1332 풀자.md, BeommoKoo-dev/202312/21 BAJ 2234 성곽.md, BeommoKoo-dev/202312/22 BAJ 21736 헌내기는 친구가 필요해.md, BeommoKoo-dev/202312/23 BAJ 7579 앱.md, BeommoKoo-dev/202312/24 BAJ 13975 파일합치기3.md, BeommoKoo-dev/202312/25 BAJ 2342 Dance Dance Revolution.md, BeommoKoo-dev/202312/26 BAJ 1495 기타리스트.md
https://www.acmicpc.net/problem/1495
20 분
i번째 공연마다 볼륨을 줄이고, 늘리면서 마지막 공연까지 갔을 때에, 최대 볼륨을 구하는 문제.
단순히 각 공연마다 볼륨을 줄이고, 늘리는 것을 bfs로 푼다면, O(2^n)의 시간복잡도가 나오게 된다.
따라서 다른 방법을 생각해 보았고, 이전 공연에서 사용된 볼륨에서 현재 공연의 볼륨을 +,- 해주면 되므로 바텀업 dp를 사용하여
실행시간을 최적화 시켰다.
dp는 더 많이 풀어서 점화식을 어렵지 않게 세울수 있도록 해보아야겠다.
=> [20231229] BAJ/실버1/기타리스트/구범모

Yiseull/202401/11 PRG 섬 연결하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/42861
70분
n개의 섬 사이에 다리를 건설하는 비용(costs)이 주어질 때, 최소의 비용으로 모든 섬이 서로 통행 가능하도록 만들 때 필요한 최소 비용을 return 하도록 solution을 완성하세요.
다리를 여러 번 건너더라도, 도달할 수만 있으면 통행 가능하다고 봅니다. 예를 들어 A 섬과 B 섬 사이에 다리가 있고, B 섬과 C 섬 사이에 다리가 있으면 A 섬과 C 섬은 서로 통행 가능합니다.
전체 건설 비용이 최소가 되도록 하려면 건설 비용이 작은 것부터 건설을 하면 된다. 이때 가장 중요한 것은 ✨사이클✨이 생기지 않도록 하는 것이다.
사이클은 BFS를 통해 확인한다. 
1. visited 배열에 자신의 이전 방문 섬을 넣는다. `visited[v] = w` 는 v가 w에서 넘어와서 방문한 것을 뜻한다.
2. BFS를 돌면서 이미 방문한 적 있는 섬을 만났을 때, 그 섬이 자신의 이전 방문 섬이 아니라면(=서로 연결되어 있는 섬이 아니라면) 사이클이 생긴 것으로 간주한다.
문제를 읽어 나가는 도중에 어떻게 풀어야할지 떠올라서 풀이를 생각해내는 것은 어렵지 않았다.
그런데도 풀이 시간이 오래 걸린 것은 사이클을 확인하는 로직이 자꾸 틀렸기 때문이다.  머릿 속에서는 '이렇게 접근하면 되겠다!' 생각은 했지만 그걸 코드로 풀어내는 과정에서 생각 그대로 잘 풀어내지 못했다.
항상 느끼는 거지만 나는 알고리즘 문제를 푸는데 꼼꼼함이 부족한 것 같다. 한 번에 통과하는 경우가 드물고 항상 제출하고 …
=> [20240111] PRG / lv3 / 섬 연결하기 / 박이슬

BeommoKoo-dev/202401/17 BAJ 16197 두 동전.md
https://www.acmicpc.net/problem/16197
20 분
두 동전을 동시에 이동시켜서, 보드 밖으로 하나의 동전만 떨어뜨릴 때 드는 최소 이동 횟수
두 동전을 하나의 노드로 생각해서 bfs를 돌린다. 따라서 visited배열도 두 동전의 x,y좌표를 각각 담은 4차원 배열로 선언하였다.
count >= 10인경우 -1을 리턴해야 하는 점을 깜빡해서 한번 틀렸다. 문제 조건 잘 보자.
=> [20240117] BAJ/골드4/두 동전/구범모

BeommoKoo-dev/202401/18 BAJ 1101 카드 정리1.md
https://www.acmicpc.net/problem/1101
50 분
문제 조건에 맞도록 카드를 이동시킬 때, 최소 이동 횟수를 구하는 문제.
상자의 갯수(N)이 작으므로, 모든 상자를 한번씩 조커 상자로 만들어 본 이후, 나머지 상자에서 
1. 카드가 아예 없는 경우 : continue
2. 카드가 1종류 있는 경우
2-1. 이전에 해당 색상이 나온 경우에는 이동횟수++
2-2. 이전에 해당 색상이 나오지 않은 경우에는 visited배열을 true로만 바꿔주기
3. 카드가 2종류 이상 있는 경우 : 이동횟수++
를 세서 답을 최소로 갱신한다.
처음에는 무조건 카드의 종류가 많은 상자를 조커 상자로 지정해두면 된다는 생각을 했는데, 맞왜틀 하다가 풀이를 찾아보니 꼭 그런것만은 아니였다. 반례는 아직 찾지 못했지만, 앞으로 n이 작은 경우에는 이번 기회를 떠올려서 완탐으로 모든 경우를 체크하는 것이 더 좋을것 같다는 생각이 든다.
=> [20240118] BAJ/골드4/카드 정리1/구범모

HandamdeCloud/202401/22 BOJ 22850 폴더 정리.md
https://www.acmicpc.net/problem/22860
50 분
내가 원하는 폴더 내의 파일종류와 파일 개수를 출력한다.
저장하는 비용과 탐색하는 과정의 소모비용으 생각하는데 고민이 있었다. 그렇지만 결론은 쉽게 나왔고 depth를 1인 dictionary를 두고 탐색을 계속해서 해나가는 과정을 생각했다. 그 dictionary의 값을 중심으로 계속 dfs탐색을 해나가면 결과는 구하기 쉬웠을 것이다. 
졸린 탓인지 dictionary에 선언을 하고 값을 채워넣는 기본 설정에서 어려움을 겪었다. 그부분만 해결되었으면 dfs과정은 전혀 어려운 과정은 아니었을 것 같다. 풀이 계획은 계획대로 잘 세워진 풀이가 되었다는 점에 대해 만족한다.. 집중력 부재가 뼈아프다.
=> [20240122] BOJ / 골드3 / 폴더 정리 / 조재현

BeommoKoo-dev/202401/22 BAJ 1781 컵라면.md
https://www.acmicpc.net/problem/1781
60분
각 문제마다 데드라인이 존재하고, 그 문제에 대한 보상이 있을 때 보상을 최대화 하는 문제
데드라인 오름차순 정렬 이후, 현재 날짜에 풀 수 있는 문제면 보상 오름차순으로 정렬된 우선순위큐에 add한다.
현재 날짜에 풀 수 없는 문제이면, 해당 보상을 우선순위 큐에 넣고, 가장 보상이 낮은 우선순위큐의 top을 pop해준다.
모든 문제를 푼 이후에는 우선순위큐를 비워내며 답에 더해준다.
=> [20240122] BAJ/골드2/컵라면/구범모

BeommoKoo-dev/202401/24 BAJ 9576 책 나눠주기.md
https://www.acmicpc.net/problem/9576
20분
학부생 m명에게 1~n범위 내에 있는 책을 최대한으로 나눠줄 수 있는 경우의 수
a이상 b이하의 책들을 그리디하게 b 오름차순으로 정렬하여, 범위내의 가장 작은 번호의 책부터 나눠준다.
처음 풀 땐 b오름차순이 아닌 a오름차순으로 풀었으나 반례가 있었다. 풀면서도 정렬의 기준이 3개 있다고 생각했는데, 무엇이 최적인지 모르겠어서 반례를 조금 생각해보다 a오름차순으로 제출했었다. 명확히 정렬의 기준이 여러개 보이는 것들은 직접 손으로 test case를 적어보자.
(최적의 답이 되는 정당성을 보장하는 법은 찾아봐도 잘 모르겠다 ㅜㅜ)
=> [20240124] BAJ/골드2/책 나눠주기/구범모

HandamdeCloud/202401/24 BOJ 16987 계란으로 계란치기.md
https://www.acmicpc.net/problem/16987
60 분 - 실패
계란으로 계란을 쳐서 깨진 계란을 count한다.
1. 파괴 복구 과정이 들어있다. 내구도를 임의의 변수로 주고 처리하려고 해서 기존 값이 제대로 복구되지 못하는 문제가 있었음
2. 진행 과정중 엣지케이스를 고려하는 과정에서 상당한 시간을 소모했지만, 그 값을 처리해주는 방법을 떠올리지 못해 실패함
디버깅 과정이 굉장히 인상적이었다. 풀이에서 잘못된점을 찾고 그걸 고쳐나가는 과정이 도움이 많이 된 듯하다.
다만, 엣지케이스를 고려하는 프로그래밍은 아직 부족한 듯 하다. 그 경우의수를 직접 노가다이더라도 해보는 연습이 필요하다. 
그리고 dfs풀이가 고착화되면서 문제를 푸는 형ㅇ식에서 습관적인 모습도 나온 것 같다. 다시 문제를 읽고 내가 생각한 풀이인지 생각할 필요가 있다.
=> [20240124] BOJ / 골드5 / 계란으로 계란치기 / 조재현

BeommoKoo-dev/202401/25 BAJ 6087 레이저 통신.md, BeommoKoo-dev/202401/26 BAJ 17136 색종이 붙이기.md
https://www.acmicpc.net/problem/6087
50분
C로 표시되어 있는 두 칸을 잇기 위해 설치해야 하는 거울의 갯수
하나의 C에서 시작하여 bfs를 돌린다. 이때, 방향을 틀어야 하는 경우의 수 = 거울의 수기 때문에, 이전에 사용했던 방향과 이전에 사용했던 거울을 상태로써 저장하기 위해 Node에 저장하였다. visited배열은 방문 x좌표/방문 y좌표/방향 까지 하여 3차원 int 배열로 선언했고, 저장하는 것은 거울의 갯수이다.
visited배열 설정을 잘못 해서 시간이 좀 더 걸렸다. 이런 유형을 연습할 수 있어서 좋았다.
=> [20240125] BAJ/골드3/레이저 통신/구범모

HandamdeCloud/202401/29 PRG 입국 심사.md
50 분 -> 실패
입국심사를 최소시간으로 할 수 있는 방법을 찾아라!
완전히 수학으로 풀었음
시간을 정방향 역방향으로 정렬하고 분수 비율로 따져서 효율적으로 탐색할 수 있는 시간을 만듦
그리고 계산과정에서 버림된 친구들을 모으면 정수가 됨 => 정수값들을 바탕을로 다시 시간이 가장 덜 소요되는 친구들에게 배분함
어찌보면 풀이가 완전히 방향성을 빗나간건 맞는 것 같다. 버림된 수를 가지고 다시 재분배하는 과정에서 어떤 입국 담당자가 효율적인지 의사 결정을 쉽게 해낼 수는 없었다. 과정에 확신이 없다보ㄴ 올바른 결과를 찾지 못했는데, 풀이를 보면서 이분탐색에 대해 공부를 많이 하게 되었다.
어떤 상황에 이분탐색 적용이 좋은건지 풀이와 문제를 대입해보면서 생각해봐야할듯 하다.
=> [20240129] PRG / LV3 / 입국 심사 / 조재현

Yiseull/202401/31 PRG 파괴되지 않은 건물.md
https://school.programmers.co.kr/learn/courses/30/lessons/92344
60분 이상
O(k + n * m), k는 skill의 길이
N x M 크기의 행렬 모양의 게임 맵이 있습니다. 이 맵에는 내구도를 가진 건물이 각 칸마다 하나씩 있습니다. 적은 이 건물들을 공격하여 파괴하려고 합니다. 건물은 적의 공격을 받으면 내구도가 감소하고 내구도가 0이하가 되면 파괴됩니다. 반대로, 아군은 회복 스킬을 사용하여 건물들의 내구도를 높이려고 합니다.
건물의 내구도를 나타내는 2차원 정수 배열 board와 적의 공격 혹은 아군의 회복 스킬을 나타내는 2차원 정수 배열 skill이 매개변수로 주어집니다. 적의 공격 혹은 아군의 회복 스킬이 모두 끝난 뒤 파괴되지 않은 건물의 개수를 return하는 solution함수를 완성해 주세요.
이 문제는 누적합 말고 다른 풀이로 시도한다면 시간초과가 나는 것 같습니다. 그리고 2차원 배열이기 때문에 누적합도 2차원으로 풀어야 합니다.
예를 들어, [1, 1, 1]에 대해서 0부터 1까지 2만큼의 내구도를 낮추려고 한다면, 최종 결과는 [-1, -1, 1]이 됩니다. 이때 누적합을 사용한다면 [0, 0, 0] 배열에 시작 인덱스에 +내구도, 마지막 인덱스 + 1 에 -내구도를 더하면, [-2, 0, 2]가 되고 시작 인덱스부터 누적합을 하면 [-2, -2, 0]이 됩니다. 그리고 원래의 배열과 합치면 [-1, -1, 0]이 되면서 원하는 결과를 얻을 수 있습니다.
이 방식을 2차원으로 확장하여, skill에 대하여 위와 같이 인덱스에 …
=> [20240131] PRG / lv3 / 파괴되지 않은 건물 / 박이슬

HandamdeCloud/202402/01 BOJ 20056 마법사 상어와 파이어볼.md
https://www.acmicpc.net/problem/20056
70 분 - 실패
- [] 상
구현 조건대로 파이어볼의 중량의 합을 구하기
절차적으로 필요한 내요을 구현하면 된다. 
너무 재밌었고 너무 아쉬운 문제.
객체지향적으로 메소드를 잘 나누고 정보를 전달했으면 쉽게 구현해냈을것 같은데, 의외로 생각지도 못한 곳에서 어려움을 겪어서 문제를 해결하지 못했다. 
fire_field = [[[0, 0]] * n for _ in range(n)]
fire_field = [[[0, 0] for _ in range(n)] for _ in range(n)]
3차원 배열을 구현하는 과정에서 그동안 2차원 배열을 곱하듯 게산을 하면서 참조값이 복사되는 문제를 인지하지 못했다. 
이렇게 되면 특정 위치 값에 사칙연산을 해도 전체에 영향을 받게 된다. 
그렇기 때문에 문제를 해결하기 위해선 선언을 적절히 신경써줘야만 한다.
=> [20240201] BOJ / 골드4 / 마법사 상어와 파이어볼 / 조재현

born-A/202402/01 BAJ 녹색 옷 입은 애가 젤다지? .md
https://www.acmicpc.net/problem/4485
70분
링크는 이 동굴의 반대편 출구, 제일 오른쪽 아래 칸인 [N-1][N-1]까지 이동해야 한다. 
동굴의 각 칸마다 도둑루피가 있는데, 이 칸을 지나면 해당 도둑루피의 크기만큼 소지금을 잃게 된다. 
링크는 잃는 금액을 최소로 하여 동굴 건너편까지 이동해야 하며, 한 번에 상하좌우 인접한 곳으로 1칸씩 이동할 수 있다.
링크가 잃을 수밖에 없는 최소 금액을 구한다.
한 지점에서 어느 한 지점까지의 최단경로를 구하는 문제이므로 다익스트라 + bfs 사용한다.
우선순위 큐를 사용하여 시간복잡도를 줄인다.
확실히 골드는 실버랑 난이도가 다른거 같다.
두가지 알고리즘을 섞어서 푸는 문제였어서 시간이 오래 소요되었다.
+ 변수명 떄문에 컴파일 에러가 계속 나서 시간을 엄청 소요했다. 변수명 인지를 제대로 하고 문제를 풀어야겠다.
=> [20240201] BAJ / 골드4 / 녹색 옷 입은 애가 젤다지?  / 신예진

BeommoKoo-dev/202402/02 BAJ 4811 알약.md
https://www.acmicpc.net/problem/4811
20분
알약을 꺼내 하나 전체를 먹는 경우와 반개를 먹는 경우를 문자열로 적었을 때, 나올 수 있는 경우의 수
N = 1, 2, 3까지 적어보니 부분문제가 보였고, dp[w][h] : 알약 1개짜리 w개와 반개짜리 h개가 남았을 때의 경우의 수로 정의한 이후 점화식을 세워보니
dp[w][h] = dp[w - 1][h + 1] +dp[w][h - 1]가 나왔다.
dp[n][0]이 내가 구해야 할 것이므로 매 테스트 케이스마다 출력.
=> [20240202] BAJ/골드5/알약/구범모

Curry4182/202402/02 외판원 순회.md
https://www.acmicpc.net/problem/2098
60분
어떤 도시a 에서 어떤 도시b 로 가는 모든 비용이 주어졌을 때 모든 도시를 방문하는 최소 비용을 출력하는 문제  
어떤 도시 a에서 어떤 도시 b로 가는 방법은 n 이고 이후 방법은 n-1이다. 이를 합치면 n! 인데 여기서 다이나믹 프로그래밍과 비트마스킹을 사용하여 O(2^n *n^2) 시간복잡도와 O(2^n * n) 공간 복잡도로 줄일 수 있었다.
처음 다이나믹 프로그래밍으로 풀려고 했지만 무엇을 어떻게 저장할지 고민을 많이 했다.
=> [20240202] BAJ / Gold1 / 외판원 순회 / 강병곤

BeommoKoo-dev/202402/06 BAJ 14943 벼룩시장.md
https://www.acmicpc.net/problem/14943
60분
벼룩을 사는 사람과 파는 사람이 있을 때, 배달의 최소비용
사는사람(음수의 가격)과 파는 사람(양수의 가격)을 입력받는 순서대로 각각 다른 큐에 집어넣고,
큐의 front끼리 비교하는 식으로, 최대한 거리가 가까운 사람끼리 거래를 하도록 그리디하게 접근한다.
정당성 증명은 다음과 같다.
만약 -1 1 2 -3 1 이 있다고 해보자. 그리디하게 접근한다면 (-1, 1), (2, -3), (1, -3)이 거래하게 된다. 따라서 답은 1 + 2 + 1 = 4가 된다. (모두 거리가 1)
만약 거리가 가까운 순으로 거래하지 않고 (-1, 2), (1, -3), (2, -3) (1, -3)이 거래한다고 해보자. 그렇다면 1(가격) * 2(거리) + 1 * 2 + 2 * 1 + 1 * 1 = 6이 돼버린다.
=> [20240206] BAJ/골드3/벼룩시장/구범모

BeommoKoo-dev/202402/08 BAJ 1525 퍼즐.md
https://www.acmicpc.net/problem/1525
50분
임의로 배정된 퍼즐을 잘 옮겨서 문제에서 주어진 모양대로 만들 때, 최소 이동횟수
최소 이동횟수를 구해야 하므로 bfs를 채택. 각 퍼즐의 상태를 어떻게 나타낼까 하다가 하나의 노드를 2차원 int배열로 선정하려 했었다.
하지만 문제의 메모리 제한은 32MB라, 계산해보니 최악의 경우 메모리 제한을 살짝 넘기는 정도라, 하나의 노드의 36바이트가 드는 2차원 int배열이(3x3배열이므로) 아닌, String으로 하나의 노드를 표현했다.(9바이트)
이후 String에서 0을 찾아 0의 주위와 바꾸어 보고, 해당 String이 만들어진 적 없으면 set에 해당 string을 넣어서 방문표시를 해주었다.
색다른 bfs라 좋았다.
=> [20240208] BAJ/골드2/퍼즐/구범모

BeommoKoo-dev/202402/13 BAJ 10653 마라톤2.md
https://www.acmicpc.net/problem/10653
60분
1번부터 n번 체크포인트까지 최대 k개를 스킵하여 도달할 때, 드는 최소 거리
처음에는 그리디 접근방식으로 각 체크포인트간에 거리가 먼 것들을 제외했으나, 그렇게 되면 제외한 점 앞뒤로 다시 연결시켜 주어야 하기에 복잡해진다. 알고리즘 태그를 보니 dp여서 다시 생각해 보니 상태 정의 해야할 것들이 크게 현재 인덱스, 몇개 체크포인트를 건너뛰었는지를 저장하여 bottom up으로 쌓아나갔다.
문제를 풀 때 알고리즘의 정당성을 어느정도 증명해보고 풀이를 하는 습관을 가지자.
=> [20240213] BAJ/골드3/마라톤2/구범모

born-A/202402/13 BAJ Projec Teams.md
https://www.acmicpc.net/problem/20044 
40분
2n명의 학생숫가 주어지고, n개의 팀의 점수의 합을 만든다.
팀의 점수의 합이 되는 수를 구한다.
정렬한 후, 차이를 최소화 하기 위해 (1,n), (2,n-1), (3,n-2) 식으로 쌍을 만든다.
쌍의 점수의 합이 최소가 되는 값을 구한다.
=> [20240213] BAJ / 실버4 / Project Teams / 신예진

BeommoKoo-dev/202402/15 BAJ 1374 강의실.md
https://www.acmicpc.net/problem/1374
10분
강의 시작시간과 종료시간이 주어질 때, 최소로 강의실을 이용할 때의 강의실 갯수
시작시간이 빠른 순서대로 정렬한 이후, 종료시간이 빠른 순서대로 정렬된 pq의 top과 비교하여, 시작시간이 이전에 들어가 있던 pq의 top보다 늦다면, 같은 강의실을 사용해도 되는 것이고 시작시간이 종료시간보다 빠르다면 새로운 강의실을 이용해야 한다.
비슷한 문제(https://www.acmicpc.net/problem/12764)를 풀어봤어서 풀이과정을 떠올리는 것이 수월했다. 역시 많이 풀어보는게 좋다.
=> [20240215] BAJ/골드5/강의실/구범모

BeommoKoo-dev/202402/16 BAJ 13302 리조트.md
https://www.acmicpc.net/problem/13302
60분
n일 중 m일을 쉬고, 리조트의 하루/3일/5일 이용권의 금액과 각 이용권을 구매했을 때의 지급되는 쿠폰이 있을 때,
m일을 제외한 모든 날을 리조트를 대여했을 때의 최소 금액을 구해라.
brute force는 O(3^100)이 나오므로, dp로 연산을 줄였다.
저장돼야 하는 상태는
1. 날짜, 2. 쿠폰의 갯수이므로,
dp[i][j] : i일에 리조트를 대여한 상태이고, 쿠폰이 j개 남아 있을 때 예약금의 (누적)최솟값으로 정의하고 점화식을 도출하였다.
=> [20240216] BAJ/골드4/리조트/구범모

Yiseull/202402/19 BAJ 게으른 백곰.md
https://www.acmicpc.net/problem/10025
45분
앨버트가 가장 적은 거리만 움직이고도 최대한 많은 얼음으로 더위를 식힐 수 있도록 도와주자. 우리 안은 1차원 배열로 생각하며, 총 N(1 ≤ N ≤ 100000)개의 얼음 양동이들이 xi(0 ≤ xi ≤ 1,000,000)좌표마다 놓여 있고 각 양동이 안에는 gi(1 ≤ gi ≤ 10,000)씩의 얼음이 들어 있다. 일단 앨버트가 자리를 잡으면 그로부터 좌우로 K(1 ≤ K ≤ 2,000,000) 만큼 떨어진 양동이까지 닿을 수 있다. 앨버트는 양동이가 놓여 있는 자리에도 자리잡을 수 있다. 모든 얼음 양동이의 위치는 다르다.
앨버트가 최적의 자리를 골랐을 때 얼음의 합을 구하시오. 즉, 얼음들의 합의 최댓값을 구해야 한다.
풀이는 슬라이딩 윈도우와 누적합을 사용하는 것이다. 먼저 풀이는 다음과 같이 간단하다.
1. 얼음이 들어있는 최소 인덱스부터 최대 인덱스까지 k*2 길이의 얼음들의 양을 업데이트 하는데, 
2. 한 칸씩 이동하면서 누적합에 i번째 얼음은 추가하고, i - (k*2) - 1번째 얼음은 제거한다.
이때 주의해야할 점은, (최소 인덱스 + K*2)가  1,000,000를 넘는지 확인해줘야 한다. 만약 넘는다면 배열의 최대 인덱스는 1,000,000여서 인덱스 에러가 발생한다. 따라서  1,000,000을 넘는 경우에는 최소 인덱스부터 마지막 인덱스까지의 길이가 k*2 미만이라는 것을 의미함으로 입력받은 전체 얼음의 양을 모두 합해서 반환하면 된다.
풀이는 이렇게 간단하지만 푸는 데 오래 걸렸다. 그 이유는 인덱스의 …
=> [20240219] BAJ / 실버3 / 개으른 백곰 / 박이슬

Yiseull/202402/21 PRG 순위 검색.md
https://school.programmers.co.kr/learn/courses/30/lessons/72412
75분
- 코딩테스트 참여 개발언어 항목에 cpp, java, python 중 하나를 선택해야 합니다.
- 지원 직군 항목에 backend와 frontend 중 하나를 선택해야 합니다.
- 지원 경력구분 항목에 junior와 senior 중 하나를 선택해야 합니다.
- 선호하는 소울푸드로 chicken과 pizza 중 하나를 선택해야 합니다.
지원자가 지원서에 입력한 4가지의 정보와 획득한 코딩테스트 점수를 하나의 문자열로 구성한 값의 배열 info, 개발팀이 궁금해하는 문의조건이 문자열 형태로 담긴 배열 query가 매개변수로 주어질 때,
각 문의조건에 해당하는 사람들의 숫자를 순서대로 배열에 담아 return 하도록 solution 함수를 완성해 주세요.
query의 각 문자열은 "[조건] X" 형식입니다. 예를 들면, "cpp and - and senior and pizza 500"은 "cpp로 코딩테스트를 봤으며, 경력은 senior 이면서 소울푸드로 pizza를 선택한 지원자 중 코딩테스트 점수를 500점 이상 받은 사람은 모두 몇 명인가?"를 의미합니다.
1️⃣ 첫 번째 풀이 - 실패
- 개발언어, 직군, 경력구분, 소울푸드는 dict에 [선택 항목: {지원자 index}] 형태로 저장한다. 코딩테스트 점수는 [지원자 index: 점수] 형태로 저장한다.
- query에 대해서 개발언어, 직군, 경력구분, 소울푸드를 & 연산하여 교집합을 구해주고, 구한 지원자 index에 대해서 한 …
=> [20240221] PRG / lv2 / 순위 검색 / 박이슬

Yiseull/202402/23 PRG 길 찾기 게임.md
https://school.programmers.co.kr/learn/courses/30/lessons/42892
50분
곤경에 빠진 카카오 프렌즈를 위해 이진트리를 구성하는 노드들의 좌표가 담긴 배열 nodeinfo가 매개변수로 주어질 때,
노드들로 구성된 이진트리를 전위 순회, 후위 순회한 결과를 2차원 배열에 순서대로 담아 return 하도록 solution 함수를 완성하자.
- nodeinfo는 이진트리를 구성하는 각 노드의 좌표가 1번 노드부터 순서대로 들어있는 2차원 배열이다.
- nodeinfo의 길이는 1 이상 10,000 이하이다.
- nodeinfo[i] 는 i + 1번 노드의 좌표이며, [x축 좌표, y축 좌표] 순으로 들어있다.
- 모든 노드의 좌표 값은 0 이상 100,000 이하인 정수이다.
- 트리의 깊이가 1,000 이하인 경우만 입력으로 주어진다.
- 모든 노드의 좌표는 문제에 주어진 규칙을 따르며, 잘못된 노드 위치가 주어지는 경우는 없다.
1. 노드가 입력된 순으로 번호를 갖기 때문에 노드 정보 맨 마지막에 노드 번호까지 추가해서 새롭게 배열을 만들고, x좌표 순으로 정렬한다.
2. y좌표가 가장 큰 노드가 루트 노드이기 때문에, 루트 노드를 찾고 루트 노드를 기준으로 왼쪽 이진트리와 오른쪽 이진트리로 나눈다.
3. 왼쪽 이진트리와 오른쪽 이진트리에 대해서도 2번을 실행한다. (재귀)
4. 문제에서 전위 순회와 후위 순회에 대해서 구하는 것이므로, 전위순회는 3번 전에 정답에 현재 루트를 추가하고, 후위순회는 3번이 다 끝난 후 추가한다.
이 문제는 전에 풀었던 문제이다. …
=> [20240223] PRG / lv3 / 길 찾기 게임 / 박이슬

BeommoKoo-dev/202402/26 BAJ 1240 노드 사이의 거리.md
https://www.acmicpc.net/problem/1240
10분
N개의 노드로 이루어진 트리가 주어지고 M개의 두 노드 쌍을 입력받을 때 두 노드 사이의 거리를 출력하라.
두 노드쌍을 입력받을 때 마다 bfs를 돌려서 노드 사이 거리를 구해주었다.
=> [20240226] BAJ/골드5/노드사이의 거리/구범모

born-A/202402/28 BAJ 케빈 베이컨의 6단계 법칙.md
https://www.acmicpc.net/problem/1389
35분
케빈 베이컨은 미국 헐리우드 영화배우들 끼리 케빈 베이컨 게임을 했을때 나오는 단계의 총 합이 가장 적은 사람을 구하는 문제.
1 3
1 4
4 5
4 3
3 2
가 주어졌을 때,
1은 2까지 3을 통해 2단계 만에, 3까지 1단계, 4까지 1단계, 5까지 4를 통해서 2단계 만에 알 수 있다. 따라서, 케빈 베이컨의 수는 2+1+1+2 = 6이다.
2는 1까지 3을 통해서 2단계 만에, 3까지 1단계 만에, 4까지 3을 통해서 2단계 만에, 5까지 3과 4를 통해서 3단계 만에 알 수 있다. 따라서, 케빈 베이컨의 수는 2+1+2+3 = 8이다.
3은 1까지 1단계, 2까지 1단계, 4까지 1단계, 5까지 4를 통해 2단계 만에 알 수 있다. 따라서, 케빈 베이컨의 수는 1+1+1+2 = 5이다.
4는 1까지 1단계, 2까지 3을 통해 2단계, 3까지 1단계, 5까지 1단계 만에 알 수 있다. 4의 케빈 베이컨의 수는 1+2+1+1 = 5가 된다.
플로이드 워셜
=> [20240228] BAJ / 실버1 / 케빈 베이컨의 6단계 법칙 / 신예진

BeommoKoo-dev/202403/04 1756 피자 굽기.md
https://www.acmicpc.net/problem/1756
40분
틀의 지름에 맞추어 피자반죽을 넣을 때, 가장 마지막에 들어가는 피자반죽의 위치를 구하시오.
완전탐색으로 돌리면 O(ND)가 나와 시간초과가 뜬다.
어떤 위치에 피자를 넣으면 그것보다 더 깊은곳에는 못 넣기 때문에, 하나의 포인터를 두어 최대 D만큼만 움직이게 하여 시간복잡도를 O(N+D)로 개선할 수 있다. 이때 주의해야 할 점은, 틀의 지름이 5 4 6 2 3 이런식으로 되면, 현재 틀의 지름을 이전의 틀의 지름 중 최솟값으로 만드는 작업이 필요하므로, 5 4 4 2 2로 틀의 지름을 바꾼 이후에 틀의 맨 끝에서부터 피자반죽을 넣어본다.
시간복잡도 개선하는 면에서 하나 배워가면 좋을 것 같다.
=> [20240304] BAJ/골드5/피자 굽기/구범모

Yiseull/202403/05 PRG 기지국 설치.md
https://school.programmers.co.kr/learn/courses/30/lessons/12979#
30분
전파의 도달 거리가 W일 땐, 기지국이 설치된 아파트를 기준으로 전파를 양쪽으로 W만큼 전달할 수 있습니다.
아파트의 개수 N, 현재 기지국이 설치된 아파트의 번호가 담긴 1차원 배열 stations, 전파의 도달 거리 W가 매개변수로 주어질 때, 모든 아파트에 전파를 전달하기 위해 증설해야 할 기지국 개수의 최솟값을 리턴하는 solution 함수를 완성해주세요
- 전파의 도달 거리가 w라고 하면, 하나의 기지국에서 총 w*2+1 만큼의 전파를 전달할 수 있다.
- 기지국의 전파를 받지 않는 곳의 연속된 길이가 d라고 한다면, 설치해야하는 최소 기지국의 개수는 d / (w*2+1)의 올림값이 될 것이다. 예를 들면, d가 5이고, w가 1이라고 한다면, w*2+1는 3이므로 최소 2개의 기지국을 설치해야 모든 곳에 전파를 전달할 수 있다.
```python
def solution(n: int, stations: list, w: int) -> int:
ww = w * 2 + 1
answer = 0
current = 1
for station in stations:
if current < station - w:
answer += ceil((station - w - current) / ww)
current = station + w + 1
answer += ceil((n - current + 1) / ww)
return answer
```
전파가 터지지 않는 곳의 길이를 구하기 위해 기지국 …
=> [20240305] PRG / lv3 / 기지국 설치 / 박이슬

born-A/202403/05 BAJ 직사각형 네개의 합집합의 면적 구하기.md
https://www.acmicpc.net/submit/2669
20분
네 개의 직사각형이 놓여 있는데 하나가 다른 하나를 포함할 수도 있으며, 변이나 꼭짓점이 겹칠 수도 있다.
이 직사각형들이 차지하는 면적을 구한다.
좌표 내에 들어있는 부분을 1로 채워서 더한다.
=> [20240305] BAJ / 실버5 / 직사각형 네개의 합집합의 면적 구하기 / 신예진

BeommoKoo-dev/202403/06 2042 구간 합 구하기.md
https://www.acmicpc.net/problem/2042
30분
첫째 줄에 수의 개수 N(1 ≤ N ≤ 1,000,000)과 M(1 ≤ M ≤ 10,000), K(1 ≤ K ≤ 10,000) 가 주어진다. M은 수의 변경이 일어나는 횟수이고, K는 구간의 합을 구하는 횟수이다. 그리고 둘째 줄부터 N+1번째 줄까지 N개의 수가 주어진다. 그리고 N+2번째 줄부터 N+M+K+1번째 줄까지 세 개의 정수 a, b, c가 주어지는데, a가 1인 경우 b(1 ≤ b ≤ N)번째 수를 c로 바꾸고 a가 2인 경우에는 b(1 ≤ b ≤ N)번째 수부터 c(b ≤ c ≤ N)번째 수까지의 합을 구하여 출력하면 된다.
입력으로 주어지는 모든 수는 -2^63보다 크거나 같고, 2^63-1보다 작거나 같은 정수이다.
기존의 dp를 이용한 구간합을 사용하면, 수를 변경하는데 O(M)이 걸리고 구간 합을 갱신하는데 O(N)이 걸리기 때문에, 전체 시간복잡도는 O(N*M)이 걸리게 되어 시간초과가 난다.
따라서 세그먼트 트리를 구현하여 구간합의 갱신을 O(logN)으로 최적화 하였다.
세그먼트 트리 학습용으로 문제를 풀어보았다.
=> [20240306] BAJ/골드1/구간 합 구하기/구범모

Yiseull/202403/06 PRG 베스트앨범.md
https://school.programmers.co.kr/learn/courses/30/lessons/42579#
45분
스트리밍 사이트에서 장르 별로 가장 많이 재생된 노래를 두 개씩 모아 베스트 앨범을 출시하려 합니다. 노래는 고유 번호로 구분하며, 노래를 수록하는 기준은 다음과 같습니다.
- 속한 노래가 많이 재생된 장르를 먼저 수록합니다.
- 장르 내에서 많이 재생된 노래를 먼저 수록합니다.
- 장르 내에서 재생 횟수가 같은 노래 중에서는 고유 번호가 낮은 노래를 먼저 수록합니다.
노래의 장르를 나타내는 문자열 배열 genres와 노래별 재생 횟수를 나타내는 정수 배열 plays가 주어질 때, 베스트 앨범에 들어갈 노래의 고유 번호를 순서대로 return 하도록 solution 함수를 완성하세요.
1. 먼저 2개의 dict를 선언한다. 하나는 장르별 총 재생 수를 저장하는 딕셔너리 `genre_total_plays`고, 다른 하나는 장르별 노래와 재생 수를 저장하는 딕셔너리 `genre_plays`다.
2. 주어진 `genres`와 `plays`의 길이만큼 반복하면서 `genre_total_plays`에는 키를 장르로 하여 계속해서 재생 수를 더해주고, `genre_plays`는 키를 장르로 하여 (재생 수, 노래 고유 번호) 튜플로 저장한다.
3. `genre_total_plays`의 items에 대하여 values에 대해, 즉 총 노래 재생 수로 내림차순 정렬을 한 후 반복문을 돌린다. 속한 노래가 많이 재생된 장르부터 확인하며, 그 장르의 genre_plays를 노래 재생 수를 기준으로 …
=> [20240306] PRG / lv3 / 베스트앨범 / 박이슬

born-A/202403/06 BAJ 막대기.md
https://www.acmicpc.net/problem/1094
45분
처음에는 64cm 막대 하나만 가지고 있다. 이때, 합이 X보다 크다면, 아래와 같은 과정을 반복한다.
1. 가지고 있는 막대 중 길이가 가장 짧은 것을 절반으로 자른다.
만약, 위에서 자른 막대의 절반 중 하나를 버리고 남아있는 막대의 길이의 합이 X보다 크거나 같다면, 위에서 자른 막대의 절반 중 하나를 버린다.
2. 이제, 남아있는 모든 막대를 풀로 붙여서 Xcm를 만든다.
몇개의 막대를 붙여서 원하는 길이의 막대를 만들 수 있는지 구한다.
64길이의 막대기로 만들수 있는 막대들은 {64, 32, 16, 8, 4, 2, 1}이다.
원하는 막대기 길이가 될때까지 더하고 빼준다.
문제 해석을 잘못해서 시간초과가 났다. 
어떻게 하면 답을 도출할지에 더 초점을 맞춰서 문제를 해석해야겠다.
=> [20240306] BAJ / 실버5 / 막대기 / 신예진

Yiseull/202403/07 PRG 불량 사용자.md
https://school.programmers.co.kr/learn/courses/30/lessons/64064
45분
개발팀 내에서 이벤트 개발을 담당하고 있는 "무지"는 최근 진행된 카카오이모티콘 이벤트에 비정상적인 방법으로 당첨을 시도한 응모자들을 발견하였습니다. 이런 응모자들을 따로 모아 불량 사용자라는 이름으로 목록을 만들어서 당첨 처리 시 제외하도록 이벤트 당첨자 담당자인 "프로도" 에게 전달하려고 합니다. 이 때 개인정보 보호을 위해 사용자 아이디 중 일부 문자를 '*' 문자로 가려서 전달했습니다. 
이벤트 응모자 아이디 목록이 담긴 배열 user_id와 불량 사용자 아이디 목록이 담긴 배열 banned_id가 매개변수로 주어질 때, 당첨에서 제외되어야 할 제재 아이디 목록은 몇가지 경우의 수가 가능한 지 return 하도록 solution 함수를 완성해주세요.
👉 이 문제의 입력값들의 크기는 매우 작다. 따라서 브루트포스 알고리즘을 사용하여 전체 경우의 수를 세어준다. 이때 중복된 경우를 위해 정답 배열을 set으로 선언한다.
이 문제는 중복 경우의 수를 처리하는 게 가장 어려웠다. 나는 중복을 처리하기 위해 answer 배열을 set으로 선언하고, 응모자 아이디에 대한 visited 배열을 하나의 string값으로 변경하여 answer에 추가했다. 이렇게 되면 중복값은 set 특성에 의해 1번만 저장될 것이고, answer의 길이는 제재 아이디 목록의 경우의 수가 될 것이다.
=> [20240307] PRG / lv3 / 불량 사용자 / 박이슬

Curry4182/202403/08 징검다리.md
https://school.programmers.co.kr/learn/courses/30/lessons/64062
60분
한 번 돌을 건널 때 마다 배열의 모든 값이 1씩 떨어진다.
그리고 원소의 값이 0일 때 그 원소는 건널 수 없다.
최대 k까지 건너뛸 수 있을 때 최대 몇번 건너뛸 수 있는지 출력한다.
이분탐색
이 방법은 자바도 가능하다.
문제에서 요구하는 값을 x 라고 하자
x를 만족하는지 확인하는데 배열의 길이 n 만큼 시간복잡도가 든다.
x가 통과되면 늘리고 통과되지 않으면 좀 더 줄이는 방식으로 구할 때 이분탐색으로 한다면 log n의 시간 복잡도가 든다.
그러면 전체 n log n으로 통과된다.
이분탐색이 되는 이유는 java는 idx 와 value를 저장하기 위해 long으로 변경하는데 이때 발생하는 오버헤드 때문에 안되는것으로 보인다.
=> [20240308] PRG / lv3 / [복습]징검다리 / 강병곤

Yiseull/202403/11 PRG 여행경로.md
https://school.programmers.co.kr/learn/courses/30/lessons/43164#
30분
주어진 항공권을 모두 이용하여 여행경로를 짜려고 합니다. 항상 "ICN" 공항에서 출발합니다.
항공권 정보가 담긴 2차원 배열 tickets가 매개변수로 주어질 때, 방문하는 공항 경로를 배열에 담아 return 하도록 solution 함수를 작성해주세요.
- 모든 공항은 알파벳 대문자 3글자로 이루어집니다.
- 주어진 공항 수는 3개 이상 10,000개 이하입니다.
- tickets의 각 행 [a, b]는 a 공항에서 b 공항으로 가는 항공권이 있다는 의미입니다.
- 주어진 항공권은 모두 사용해야 합니다.
- 만일 가능한 경로가 2개 이상일 경우 알파벳 순서가 앞서는 경로를 return 합니다.
- 모든 도시를 방문할 수 없는 경우는 주어지지 않습니다.
1. 출발 공항에 대해서 도착 공항들을 리스트로 가지고 있는 딕셔너리를 만든다. 이때 출발 공항 여부를 체크하지 않기 위해 defaultdict를 사용한다.
2. 출발 공항에 대한 도착 공항들을 정렬한다. (기본은 오름차순 정렬이다)
3. 'ICN'부터 출발하여 정렬된 순서대로 공항들을 방문한다. 만약 모든 도시를 방문했다면 각 방문 도시들을 담아 리스트로 반환하고, 모든 도시를 방문하지 않았다면 되돌아가서 다음 순서의 공항을 방문한다.
처음에 제출했을 때 틀렸다. 알고보니 주어진 항공권을 모두 사용해야 한다는 조건을 고려하지 않은 것이다. 처음에 구현할 때는 무조건 정렬된 순서로 방문하고 끝내도록 했는데 이런 경우 모든 도시를 …
=> [20240311] PRG / lv3 / 여행경로 / 박이슬

Curry4182/202403/12 [3차] 방금그곡.md
https://school.programmers.co.kr/learn/courses/30/lessons/17683
50분
입력으로 네오가 기억한 멜로디를 담은 문자열 m과 방송된 곡의 정보를 담고 있는 배열 musicinfos가 주어진다.
조건에 맞는 음악 제목을 출
#(샵)기호가 붙은 단어를 먼저 치환한후 split하여 문자를 저장한다.
단순히 split하기 전에 전처리 과정을 사용하면 훨씬 편하다는것을 알게되었다.
=> [20240312] PRG / lv2 / [3차] 방금그곡 / 강병곤

born-A/202403/14 BAJ 등굣길.md
25분
m x n 사이즈의 map에서 웅덩이를 피해
오른쪽과 아래쪽으로만 움직여 집에서 학교까지 갈 수 있는 최단경로의 개수를 1,000,000,007로 나눈 나머지를 return 한다.
왼쪽에서 오는 경우 수 + 위쪽에서 오는 경우 수를 더한 값을 구한다.
테스트케이스는 통과하였으나 효율성 테스트에서 실패하여 처음에 틀렸다.
1,000,000,007를 mod로 선언하여 할당하고 dp 테이블에 그 값을 넣어주어야 통과한다.
효율성 측면에서 유의해야겠다.
=> [20240314] PRG / lv3 / 등굣길 / 신예진

Yiseull/202403/15 BAJ 백도어.md
https://www.acmicpc.net/problem/17396
60분
최대한 빨리 게임을 끝내고 문제를 출제해야 하기 때문에 유섭이는 최대한 빨리 넥서스가 있는 곳으로 달려가려고 한다. 유섭이의 챔피언은 총 N개의 분기점에 위치할 수 있다. 0번째 분기점은 현재 유섭이의 챔피언이 있는 곳을, N-1 번째 분기점은 상대편 넥서스를 의미하며 나머지 1, 2, ..., N-2번째 분기점은 중간 거점들이다. 그러나 유섭이의 챔피언이 모든 분기점을 지나칠 수 있는 것은 아니다. 백도어의 핵심은 안 들키고 살금살금 가는 것이기 때문에 적 챔피언 혹은 적 와드(시야를 밝혀주는 토템), 미니언, 포탑 등 상대의 시야에 걸리는 곳은 지나칠 수 없다. N-1번째 분기점은 상대 넥서스이기 때문에 어쩔 수 없이 상대의 시야에 보이게 되며, 또 유일하게 상대 시야에 보이면서 갈 수 있는 곳이다.
입력으로 각 분기점을 지나칠 수 있는지에 대한 여부와 각 분기점에서 다른 분기점으로 가는데 걸리는 시간이 주어졌을 때, 유섭이가 현재 위치에서 넥서스까지 갈 수 있는 최소 시간을 구하여라.
👉 기본적인 다익스트라 + 약간의 입력값 변형
이 문제는 입력값만 약간 수정하면 기본적인 다익스트라 알고리즘 그대로 풀 수 있는 문제다. 수정해야 하는 입력값은 각 분기점이 상대 시야에 보이는지를 알려주는 배열과 분기점 사이의 거리를 나타내는 값이다.
각 분기점이 상대 시야에 보이는지 알려주는 배열에서 1인 값은 갈 수 없는 분기점이기 때문에 1인 값에 대해서는 그래프에 경로를 추가하지 않는다. 이때 주의해야할 점은 마지막 분기점이다. 마지막 …
=> [20240315] BAJ / 골드5 /  백도어 / 박이슬

BeommoKoo-dev/202403/20 2346 풍선 터뜨리기.md
https://www.acmicpc.net/problem/2346
10분
1번부터 N번까지 N개의 풍선이 원형으로 놓여 있고. i번 풍선의 오른쪽에는 i+1번 풍선이 있고, 왼쪽에는 i-1번 풍선이 있다. 단, 1번 풍선의 왼쪽에 N번 풍선이 있고, N번 풍선의 오른쪽에 1번 풍선이 있다. 각 풍선 안에는 종이가 하나 들어있고, 종이에는 -N보다 크거나 같고, N보다 작거나 같은 정수가 하나 적혀있다. 이 풍선들을 다음과 같은 규칙으로 터뜨린다.
우선, 제일 처음에는 1번 풍선을 터뜨린다. 다음에는 풍선 안에 있는 종이를 꺼내어 그 종이에 적혀있는 값만큼 이동하여 다음 풍선을 터뜨린다. 양수가 적혀 있을 경우에는 오른쪽으로, 음수가 적혀 있을 때는 왼쪽으로 이동한다. 이동할 때에는 이미 터진 풍선은 빼고 이동한다.
예를 들어 다섯 개의 풍선 안에 차례로 3, 2, 1, -3, -1이 적혀 있었다고 하자. 이 경우 3이 적혀 있는 1번 풍선, -3이 적혀 있는 4번 풍선, -1이 적혀 있는 5번 풍선, 1이 적혀 있는 3번 풍선, 2가 적혀 있는 2번 풍선의 순서대로 터지게 된다.
덱을 이용하여 양수면 first를 pop하여 뒤로 보내주고, 음수면 last를 pop하여 앞에 보내준 이후, 앞에 있는 원소를 추출한다.
=> [20240320] BAJ/실버3/풍선 터뜨리기/구범모

Yiseull/202403/20 PRG 파괴되지 않은 건물.md
https://school.programmers.co.kr/learn/courses/30/lessons/92344
40분
N x M 크기의 행렬 모양의 게임 맵이 있습니다. 이 맵에는 내구도를 가진 건물이 각 칸마다 하나씩 있습니다. 적은 이 건물들을 공격하여 파괴하려고 합니다. 건물은 적의 공격을 받으면 내구도가 감소하고 내구도가 0이하가 되면 파괴됩니다. 반대로, 아군은 회복 스킬을 사용하여 건물들의 내구도를 높이려고 합니다.
건물의 내구도를 나타내는 2차원 정수 배열 board와 적의 공격 혹은 아군의 회복 스킬을 나타내는 2차원 정수 배열 skill이 매개변수로 주어집니다. 적의 공격 혹은 아군의 회복 스킬이 모두 끝난 뒤 파괴되지 않은 건물의 개수를 return하는 solution함수를 완성해 주세요.
이 문제는 누적합 말고 다른 풀이로 시도한다면 시간초과가 나는 것 같습니다. 그리고 2차원 배열이기 때문에 누적합도 2차원으로 풀어야 합니다.
예를 들어, [1, 1, 1]에 대해서 0부터 1까지 2만큼의 내구도를 낮추려고 한다면, 최종 결과는 [-1, -1, 1]이 됩니다. 이때 누적합을 사용한다면 [0, 0, 0] 배열에 시작 인덱스에 +내구도, 마지막 인덱스 + 1 에 -내구도를 더하면, [-2, 0, 2]가 되고 시작 인덱스부터 누적합을 하면 [-2, -2, 0]이 됩니다. 그리고 원래의 배열과 합치면 [-1, -1, 0]이 되면서 원하는 결과를 얻을 수 있습니다.
이 방식을 2차원으로 확장하여, skill에 대하여 위와 같이 인덱스에 내구도를 더해놓고, 맨 마지막에 누적합을 계산하면 총 …
=> [20240320] PRG / lv3 /  파괴되지 않은 건물 / 박이슬

BeommoKoo-dev/202403/22 1833 고속철도 설계하기.md
https://www.acmicpc.net/problem/1833
20분
N(1≤N≤200)개의 도시로 이루어진 나라가 있다. 이 도시들 사이를 다니는 고속철도망을 만들어 도시 간의 이동을 편하게 하려고 한다. 단, 고속철도망을 만든 후에 임의의 도시에서 다른 임의의 도시로 고속철도를 이용하여 이동할 수 있게 하려고 한다.
시범 사업으로 몇 개의 도시 사이에 고속철도가 설치되었는데 그 결과가 매우 좋아 국가에서는 이 사업을 완성하기로 하였다. 이제 당신은 몇 개의 도시 사이에 고속철도를 추가로 설치하여, 임의의 도시에서 다른 임의의 도시로 고속철도를 이용하여 이동할 수 있게 하려고 한다.
그러나 이 사업은 워낙 돈이 많이 드는 사업이기 때문에, 이 사업에 드는 총 비용을 최소화 하려고 한다. 두 도시 사이에 고속철도를 설치할 때 드는 비용이 주어졌을 때, 총 비용을 최소로 하여 사업을 완성하여 보자.
예를 들어 아래와 같은 경우를 보자.
현재 1번 도시와 2번 도시, 2번 도시와 4번 도시, 1번 도시와 4번 도시 사이에 고속철도가 설치되어 있다. 각각의 수는 두 도시 사이에 고속철도를 설치하는데 드는 비용을 나타낸다. 예를 들어 2번 도시와 3번 도시 사이에 고속철도를 설치하면 10만큼의 비용이 든다는 것을 의미한다. 위의 그림에 나타나지 않은 비용은 다 1,000이라고 하자.
위와 같은 경우에는 2, 3번 도시 사이에 고속철도를 설치하고, 3, 5번 도시 사이에 고속철도를 설치하면, 임의의 도시에서 다른 임의의 도시로 고속철도를 이용하여 갈 수 있으며, 이 경우는 10+20+30+10+10=80만큼의 총 …
=> [20240322] BAJ/골드3/고속철도 설계하기/구범모

BeommoKoo-dev/202403/26 13334 철로.md
https://www.acmicpc.net/problem/13334
40분
집과 사무실을 통근하는 n명의 사람들이 있다. 각 사람의 집과 사무실은 수평선 상에 있는 서로 다른 점에 위치하고 있다. 임의의 두 사람 A, B에 대하여, A의 집 혹은 사무실의 위치가 B의 집 혹은 사무실의 위치와 같을 수 있다. 통근을 하는 사람들의 편의를 위하여 일직선 상의 어떤 두 점을 잇는 철로를 건설하여, 기차를 운행하려고 한다. 제한된 예산 때문에, 철로의 길이는 d로 정해져 있다. 집과 사무실의 위치 모두 철로 선분에 포함되는 사람들의 수가 최대가 되도록, 철로 선분을 정하고자 한다.
양의 정수 d와 n 개의 정수쌍, (hi, oi), 1 ≤ i ≤ n,이 주어져 있다. 여기서 hi와 oi는 사람 i의 집과 사무실의 위치이다. 길이 d의 모든 선분 L에 대하여, 집과 사무실의 위치가 모두 L에 포함되는 사람들의 최대 수를 구하는 프로그램을 작성하시오.
사무실 오름차순, 사무실의 위치가 같다면 집 위치 오름차순으로 정렬한다. 또한 집의 위치를 오름차순으로 갖는 우선순위큐를 선언한다.
이후 list를 순회하며 우선순위큐가 비어있지 않다면, top을 꺼내 현재 사무실의 위치의 차이와 비교하여 d보다 이하일때까지 꺼낸다.
위의 작업을 마치고 나면 pq에 있는 원소의 갯수(현재 확인하는 사무실까지 포함)가 답의 후보가 되기 때문에 답을 최댓값으로 갱신 시킨다.
스위핑 개념에 대해서 배울 수 있는 좋은 문제.
=> [20240326] BAJ/골드2/철로/구범모

born-A/202403/29 BAJ 회전하는 큐.md
https://www.acmicpc.net/problem/1021
35분
이 큐에서 다음과 같은 3가지 연산을 수행할 수 있다.
1. 첫 번째 원소를 뽑아낸다. 이 연산을 수행하면, 원래 큐의 원소가 a1, ..., ak이었던 것이 a2, ..., ak와 같이 된다.
2. 왼쪽으로 한 칸 이동시킨다. 이 연산을 수행하면, a1, ..., ak가 a2, ..., ak, a1이 된다.
3. 오른쪽으로 한 칸 이동시킨다. 이 연산을 수행하면, a1, ..., ak가 ak, a1, ..., ak-1이 된다.
큐에 처음에 포함되어 있던 수 N이 주어진다. 그리고 지민이가 뽑아내려고 하는 원소의 위치가 주어진다.
이때, 그 원소를 주어진 순서대로 뽑아내는데 드는 2번, 3번 연산의 최솟값을 출력하는 프로그램을 작성하시오.
q의 크기의 반보다 왼쪽에 있으면 왼쪽 연산, 오른쪽에 있으면 오른쪽 연산을 사용한다.
=> [20240329] BAJ / 실버3 / 회전하는 큐 / 신에진

Yiseull/202404/02 PRG 시소 짝궁.md
https://school.programmers.co.kr/learn/courses/30/lessons/49191?language=java
60분 이상
n명의 권투선수가 권투 대회에 참여했고 각각 1번부터 n번까지 번호를 받았습니다. 권투 경기는 1대1 방식으로 진행이 되고, 만약 A 선수가 B 선수보다 실력이 좋다면 A 선수는 B 선수를 항상 이깁니다. 심판은 주어진 경기 결과를 가지고 선수들의 순위를 매기려 합니다. 하지만 몇몇 경기 결과를 분실하여 정확하게 순위를 매길 수 없습니다.
선수의 수 n, 경기 결과를 담은 2차원 배열 results가 매개변수로 주어질 때 정확하게 순위를 매길 수 있는 선수의 수를 return 하도록 solution 함수를 작성해주세요.
=> [20240403] PRG / lv3 / 순위 / 박이슬

Curry4182/202404/03 이중우선순위큐.md
https://school.programmers.co.kr/learn/courses/30/lessons/42628
40분
이중 우선 순위를 지원하도록 입력된 연산에 따라 계산 결과를 반환
Priority Queue 라이브러리를 활용하여 이를 해결하였다.
다음에 라이브러리를 사용하지 않고 풀이 해봐야겠다.
=> [20240403] PRG / lv3 / 이중우선순위큐 / 강병곤

Yiseull/202404/04 PRG 길 찾기 게임.md
https://school.programmers.co.kr/learn/courses/30/lessons/42892?language=java
25분
곤경에 빠진 카카오 프렌즈를 위해 이진트리를 구성하는 노드들의 좌표가 담긴 배열 nodeinfo가 매개변수로 주어질 때,
노드들로 구성된 이진트리를 전위 순회, 후위 순회한 결과를 2차원 배열에 순서대로 담아 return 하도록 solution 함수를 완성하자.
- nodeinfo는 이진트리를 구성하는 각 노드의 좌표가 1번 노드부터 순서대로 들어있는 2차원 배열이다.
- nodeinfo의 길이는 1 이상 10,000 이하이다.
- nodeinfo[i] 는 i + 1번 노드의 좌표이며, [x축 좌표, y축 좌표] 순으로 들어있다.
- 모든 노드의 좌표 값은 0 이상 100,000 이하인 정수이다.
- 트리의 깊이가 1,000 이하인 경우만 입력으로 주어진다.
- 모든 노드의 좌표는 문제에 주어진 규칙을 따르며, 잘못된 노드 위치가 주어지는 경우는 없다.
1. 노드의 x좌표에 따라 정렬하면 y좌표를 무시한 이진트리의 순서가 나온다. 이때 y좌표가 가장 작은 노드가 루트 노드가 되고 루트 노드를 기준으로 왼쪽 이진트리, 루트 노드, 오른쪽 이진트리 3가지 구역으로 나눌 수 있다.
2. 전위 순회와 후위 순회의 차이는 루트 노드의 순회 순서에만 차이가 있다. 전위 순회는 루트 노드를 가장 먼저 방문하고, 후위 순회는 루트 노드를 가장 마지막에 방문한다. 결국 왼쪽 이진트리를 순회하고 그 다음 오른쪽 이진트리를 순회하는 것은 동일하기 때문에 아래와 같이 전위 순회와 후외 …
=> [20240404] PRG / lv3 / 길 찾기 게임 / 박이슬

Curry4182/202404/05 [PCCP 기출문제] 2번  석유 시추.md
https://school.programmers.co.kr/learn/courses/30/lessons/250136
60분
해당하는 전체 x에 구할 수 있는 전체 석유 값을 반환 하는 문제
bfs로 각각의 석유의 크기를 저장하고 이 후 x 단위로 석유 값을 가져올 때 활용한다.
문제를 풀면서 확실히 속도 보다 정확하게 풀이하는게 더 중요하다는 것을 느낍니다.
=> [20240405] PRG / lv3 / [PCCP 기출문제] 2번 석유시추 / 강병곤

born-A/202404/09 BAJ 스티커.md
https://www.acmicpc.net/problem/9465
35분
각 테스트 케이스 마다, 2n개의 스티커 중에서 두 변을 공유하지 않는 스티커 점수의 최댓값을 출력한다.
왼쪽 대각선 아래, 왼쪽 대각선 아래의 왼쪽만 확인해서 더 큰 값을 현재 위치에 넣어주면 된다.
=> [20240409] BAJ / 실버1 / 스티커 / 신예진

Curry4182/202404/10 왕의 기사 대결.md
https://www.codetree.ai/training-field/frequent-problems/problems/royal-knight-duel/description?page=1&pageSize=20
180분
/*
변수 정보
L: 체스판의 크기
N : 기사의 수
Q: 명령의 수
K : 기사의 체력
0: 빈칸
1: 함정
2: 벽
r,c : 위치
h,w : 크기
k : 체력
i: i번 기사 (1이상 N이하)
d: 방향(위, 오른쪽, 아래, 왼쪽)(0, 1, 2, 3)
*/
/*
기사 이동
- 상하좌우 중 하나로 이동 한다 (0, 1, 2, 3)
- 이동하는 위치에 다른 기사가 있다면 상호 작용 한다.
- 한 칸씩 밀리다가 벽이 있다면 전체가 이동할 수 없다.
- 체스판에 사라진 기사에게 명령해도 반응하지 않는다.
대결 데미지
- w*h 만큼의 방패의 크기 안에 있는 함정 수 만큼 피해를 입는다.
- 현재 체력 이상의 데미지를 받으면 사라진다.
Q 번에 걸쳐 왕의 명령이 주어졌을 때 Q번의 대결이 모두 끝난 후 생존한 기사들의 총 받은 대미지의 합을 출력한다.
각 항목에 대해 예외 상황을 생각하며 구현한다.
간단하지만 여러 요구사항이 있다보니 잘 못해서 빠뜨려 전체 결과가 잘 나오지 않았다.
이를 해결하기 위해 처음 부터 꼼꼼하게 요구사항을 체크하는 능력을 키워야 겠다고 생각합니다.
=> [20240410] Code Tree / Gold 2 / 왕의 기사 대결 / 강병곤
